package com.hongte.weixin.mybatis.map;

import com.hongte.weixin.mybatis.domain.AvwFileprocess;
import com.hongte.weixin.mybatis.domain.AvwFileprocessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AvwFileprocessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_FileProcess
     *
     * @mbggenerated
     */
    int countByExample(AvwFileprocessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_FileProcess
     *
     * @mbggenerated
     */
    int deleteByExample(AvwFileprocessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_FileProcess
     *
     * @mbggenerated
     */
    int insert(AvwFileprocess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_FileProcess
     *
     * @mbggenerated
     */
    int insertSelective(AvwFileprocess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_FileProcess
     *
     * @mbggenerated
     */
    List<AvwFileprocess> selectByExample(AvwFileprocessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_FileProcess
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AvwFileprocess record, @Param("example") AvwFileprocessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_FileProcess
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AvwFileprocess record, @Param("example") AvwFileprocessExample example);
}