package com.hongte.weixin.mybatis.map;

import com.hongte.weixin.mybatis.domain.AvwXdOther;
import com.hongte.weixin.mybatis.domain.AvwXdOtherExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AvwXdOtherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    int countByExample(AvwXdOtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    int deleteByExample(AvwXdOtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    int insert(AvwXdOther record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    int insertSelective(AvwXdOther record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    List<AvwXdOther> selectByExample(AvwXdOtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AvwXdOther record, @Param("example") AvwXdOtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AvwXdOther record, @Param("example") AvwXdOtherExample example);
}