package com.hongte.weixin.mybatis.map;

import com.hongte.weixin.mybatis.domain.TCar;
import com.hongte.weixin.mybatis.domain.TCarExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    int countByExample(TCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    int deleteByExample(TCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer fitemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    int insert(TCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    int insertSelective(TCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    List<TCar> selectByExample(TCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    TCar selectByPrimaryKey(Integer fitemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TCar record, @Param("example") TCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TCar record, @Param("example") TCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TCar record);
}