package com.hongte.weixin.mybatis.map;

import com.hongte.weixin.mybatis.domain.XdCustcarinfo;
import com.hongte.weixin.mybatis.domain.XdCustcarinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XdCustcarinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustCarInfo
     *
     * @mbggenerated
     */
    int countByExample(XdCustcarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustCarInfo
     *
     * @mbggenerated
     */
    int deleteByExample(XdCustcarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustCarInfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustCarInfo
     *
     * @mbggenerated
     */
    int insert(XdCustcarinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustCarInfo
     *
     * @mbggenerated
     */
    int insertSelective(XdCustcarinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustCarInfo
     *
     * @mbggenerated
     */
    List<XdCustcarinfo> selectByExample(XdCustcarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustCarInfo
     *
     * @mbggenerated
     */
    XdCustcarinfo selectByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustCarInfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") XdCustcarinfo record, @Param("example") XdCustcarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustCarInfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") XdCustcarinfo record, @Param("example") XdCustcarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustCarInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XdCustcarinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustCarInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XdCustcarinfo record);
}