package com.hongte.weixin.mybatis.map;

import com.hongte.weixin.mybatis.domain.XdCusthinfo;
import com.hongte.weixin.mybatis.domain.XdCusthinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XdCusthinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustHInfo
     *
     * @mbggenerated
     */
    int countByExample(XdCusthinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustHInfo
     *
     * @mbggenerated
     */
    int deleteByExample(XdCusthinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustHInfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustHInfo
     *
     * @mbggenerated
     */
    int insert(XdCusthinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustHInfo
     *
     * @mbggenerated
     */
    int insertSelective(XdCusthinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustHInfo
     *
     * @mbggenerated
     */
    List<XdCusthinfo> selectByExample(XdCusthinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustHInfo
     *
     * @mbggenerated
     */
    XdCusthinfo selectByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustHInfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") XdCusthinfo record, @Param("example") XdCusthinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustHInfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") XdCusthinfo record, @Param("example") XdCusthinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustHInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XdCusthinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustHInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XdCusthinfo record);
}