package com.hongte.weixin.mybatis.map;

import com.hongte.weixin.mybatis.domain.XdDkdetailtobank;
import com.hongte.weixin.mybatis.domain.XdDkdetailtobankExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XdDkdetailtobankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    int countByExample(XdDkdetailtobankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    int deleteByExample(XdDkdetailtobankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    int insert(XdDkdetailtobank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    int insertSelective(XdDkdetailtobank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    List<XdDkdetailtobank> selectByExample(XdDkdetailtobankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    XdDkdetailtobank selectByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") XdDkdetailtobank record, @Param("example") XdDkdetailtobankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") XdDkdetailtobank record, @Param("example") XdDkdetailtobankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XdDkdetailtobank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XdDkdetailtobank record);
}