package com.hongte.weixin.mybatis.map;

import com.hongte.weixin.mybatis.domain.XdKkdetail;
import com.hongte.weixin.mybatis.domain.XdKkdetailExample;
import com.hongte.weixin.mybatis.domain.XdKkdetailKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XdKkdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_KKDetail
     *
     * @mbggenerated
     */
    int countByExample(XdKkdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_KKDetail
     *
     * @mbggenerated
     */
    int deleteByExample(XdKkdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_KKDetail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(XdKkdetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_KKDetail
     *
     * @mbggenerated
     */
    int insert(XdKkdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_KKDetail
     *
     * @mbggenerated
     */
    int insertSelective(XdKkdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_KKDetail
     *
     * @mbggenerated
     */
    List<XdKkdetail> selectByExample(XdKkdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_KKDetail
     *
     * @mbggenerated
     */
    XdKkdetail selectByPrimaryKey(XdKkdetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_KKDetail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") XdKkdetail record, @Param("example") XdKkdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_KKDetail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") XdKkdetail record, @Param("example") XdKkdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_KKDetail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XdKkdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_KKDetail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XdKkdetail record);
}