package com.hongte.weixin.mybatis.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class AvwXdOther implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Avw_XD_Other.FID
     *
     * @mbggenerated
     */
    private Integer fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Avw_XD_Other.FLVFee
     *
     * @mbggenerated
     */
    private BigDecimal flvfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Avw_XD_Other.FFKDate
     *
     * @mbggenerated
     */
    private Date ffkdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Avw_XD_Other.FFKAmt
     *
     * @mbggenerated
     */
    private BigDecimal ffkamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Avw_XD_Other.FID
     *
     * @return the value of dbo.Avw_XD_Other.FID
     *
     * @mbggenerated
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Avw_XD_Other.FID
     *
     * @param fid the value for dbo.Avw_XD_Other.FID
     *
     * @mbggenerated
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Avw_XD_Other.FLVFee
     *
     * @return the value of dbo.Avw_XD_Other.FLVFee
     *
     * @mbggenerated
     */
    public BigDecimal getFlvfee() {
        return flvfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Avw_XD_Other.FLVFee
     *
     * @param flvfee the value for dbo.Avw_XD_Other.FLVFee
     *
     * @mbggenerated
     */
    public void setFlvfee(BigDecimal flvfee) {
        this.flvfee = flvfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Avw_XD_Other.FFKDate
     *
     * @return the value of dbo.Avw_XD_Other.FFKDate
     *
     * @mbggenerated
     */
    public Date getFfkdate() {
        return ffkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Avw_XD_Other.FFKDate
     *
     * @param ffkdate the value for dbo.Avw_XD_Other.FFKDate
     *
     * @mbggenerated
     */
    public void setFfkdate(Date ffkdate) {
        this.ffkdate = ffkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Avw_XD_Other.FFKAmt
     *
     * @return the value of dbo.Avw_XD_Other.FFKAmt
     *
     * @mbggenerated
     */
    public BigDecimal getFfkamt() {
        return ffkamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Avw_XD_Other.FFKAmt
     *
     * @param ffkamt the value for dbo.Avw_XD_Other.FFKAmt
     *
     * @mbggenerated
     */
    public void setFfkamt(BigDecimal ffkamt) {
        this.ffkamt = ffkamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AvwXdOther other = (AvwXdOther) that;
        return (this.getFid() == null ? other.getFid() == null : this.getFid().equals(other.getFid()))
            && (this.getFlvfee() == null ? other.getFlvfee() == null : this.getFlvfee().equals(other.getFlvfee()))
            && (this.getFfkdate() == null ? other.getFfkdate() == null : this.getFfkdate().equals(other.getFfkdate()))
            && (this.getFfkamt() == null ? other.getFfkamt() == null : this.getFfkamt().equals(other.getFfkamt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFid() == null) ? 0 : getFid().hashCode());
        result = prime * result + ((getFlvfee() == null) ? 0 : getFlvfee().hashCode());
        result = prime * result + ((getFfkdate() == null) ? 0 : getFfkdate().hashCode());
        result = prime * result + ((getFfkamt() == null) ? 0 : getFfkamt().hashCode());
        return result;
    }
}