package com.hongte.weixin.mybatis.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AvwXdOtherExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    public AvwXdOtherExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFidIsNull() {
            addCriterion("FID is null");
            return (Criteria) this;
        }

        public Criteria andFidIsNotNull() {
            addCriterion("FID is not null");
            return (Criteria) this;
        }

        public Criteria andFidEqualTo(Integer value) {
            addCriterion("FID =", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidNotEqualTo(Integer value) {
            addCriterion("FID <>", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidGreaterThan(Integer value) {
            addCriterion("FID >", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidGreaterThanOrEqualTo(Integer value) {
            addCriterion("FID >=", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidLessThan(Integer value) {
            addCriterion("FID <", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidLessThanOrEqualTo(Integer value) {
            addCriterion("FID <=", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidIn(List<Integer> values) {
            addCriterion("FID in", values, "fid");
            return (Criteria) this;
        }

        public Criteria andFidNotIn(List<Integer> values) {
            addCriterion("FID not in", values, "fid");
            return (Criteria) this;
        }

        public Criteria andFidBetween(Integer value1, Integer value2) {
            addCriterion("FID between", value1, value2, "fid");
            return (Criteria) this;
        }

        public Criteria andFidNotBetween(Integer value1, Integer value2) {
            addCriterion("FID not between", value1, value2, "fid");
            return (Criteria) this;
        }

        public Criteria andFlvfeeIsNull() {
            addCriterion("FLVFee is null");
            return (Criteria) this;
        }

        public Criteria andFlvfeeIsNotNull() {
            addCriterion("FLVFee is not null");
            return (Criteria) this;
        }

        public Criteria andFlvfeeEqualTo(BigDecimal value) {
            addCriterion("FLVFee =", value, "flvfee");
            return (Criteria) this;
        }

        public Criteria andFlvfeeNotEqualTo(BigDecimal value) {
            addCriterion("FLVFee <>", value, "flvfee");
            return (Criteria) this;
        }

        public Criteria andFlvfeeGreaterThan(BigDecimal value) {
            addCriterion("FLVFee >", value, "flvfee");
            return (Criteria) this;
        }

        public Criteria andFlvfeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FLVFee >=", value, "flvfee");
            return (Criteria) this;
        }

        public Criteria andFlvfeeLessThan(BigDecimal value) {
            addCriterion("FLVFee <", value, "flvfee");
            return (Criteria) this;
        }

        public Criteria andFlvfeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FLVFee <=", value, "flvfee");
            return (Criteria) this;
        }

        public Criteria andFlvfeeIn(List<BigDecimal> values) {
            addCriterion("FLVFee in", values, "flvfee");
            return (Criteria) this;
        }

        public Criteria andFlvfeeNotIn(List<BigDecimal> values) {
            addCriterion("FLVFee not in", values, "flvfee");
            return (Criteria) this;
        }

        public Criteria andFlvfeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FLVFee between", value1, value2, "flvfee");
            return (Criteria) this;
        }

        public Criteria andFlvfeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FLVFee not between", value1, value2, "flvfee");
            return (Criteria) this;
        }

        public Criteria andFfkdateIsNull() {
            addCriterion("FFKDate is null");
            return (Criteria) this;
        }

        public Criteria andFfkdateIsNotNull() {
            addCriterion("FFKDate is not null");
            return (Criteria) this;
        }

        public Criteria andFfkdateEqualTo(Date value) {
            addCriterion("FFKDate =", value, "ffkdate");
            return (Criteria) this;
        }

        public Criteria andFfkdateNotEqualTo(Date value) {
            addCriterion("FFKDate <>", value, "ffkdate");
            return (Criteria) this;
        }

        public Criteria andFfkdateGreaterThan(Date value) {
            addCriterion("FFKDate >", value, "ffkdate");
            return (Criteria) this;
        }

        public Criteria andFfkdateGreaterThanOrEqualTo(Date value) {
            addCriterion("FFKDate >=", value, "ffkdate");
            return (Criteria) this;
        }

        public Criteria andFfkdateLessThan(Date value) {
            addCriterion("FFKDate <", value, "ffkdate");
            return (Criteria) this;
        }

        public Criteria andFfkdateLessThanOrEqualTo(Date value) {
            addCriterion("FFKDate <=", value, "ffkdate");
            return (Criteria) this;
        }

        public Criteria andFfkdateIn(List<Date> values) {
            addCriterion("FFKDate in", values, "ffkdate");
            return (Criteria) this;
        }

        public Criteria andFfkdateNotIn(List<Date> values) {
            addCriterion("FFKDate not in", values, "ffkdate");
            return (Criteria) this;
        }

        public Criteria andFfkdateBetween(Date value1, Date value2) {
            addCriterion("FFKDate between", value1, value2, "ffkdate");
            return (Criteria) this;
        }

        public Criteria andFfkdateNotBetween(Date value1, Date value2) {
            addCriterion("FFKDate not between", value1, value2, "ffkdate");
            return (Criteria) this;
        }

        public Criteria andFfkamtIsNull() {
            addCriterion("FFKAmt is null");
            return (Criteria) this;
        }

        public Criteria andFfkamtIsNotNull() {
            addCriterion("FFKAmt is not null");
            return (Criteria) this;
        }

        public Criteria andFfkamtEqualTo(BigDecimal value) {
            addCriterion("FFKAmt =", value, "ffkamt");
            return (Criteria) this;
        }

        public Criteria andFfkamtNotEqualTo(BigDecimal value) {
            addCriterion("FFKAmt <>", value, "ffkamt");
            return (Criteria) this;
        }

        public Criteria andFfkamtGreaterThan(BigDecimal value) {
            addCriterion("FFKAmt >", value, "ffkamt");
            return (Criteria) this;
        }

        public Criteria andFfkamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FFKAmt >=", value, "ffkamt");
            return (Criteria) this;
        }

        public Criteria andFfkamtLessThan(BigDecimal value) {
            addCriterion("FFKAmt <", value, "ffkamt");
            return (Criteria) this;
        }

        public Criteria andFfkamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FFKAmt <=", value, "ffkamt");
            return (Criteria) this;
        }

        public Criteria andFfkamtIn(List<BigDecimal> values) {
            addCriterion("FFKAmt in", values, "ffkamt");
            return (Criteria) this;
        }

        public Criteria andFfkamtNotIn(List<BigDecimal> values) {
            addCriterion("FFKAmt not in", values, "ffkamt");
            return (Criteria) this;
        }

        public Criteria andFfkamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FFKAmt between", value1, value2, "ffkamt");
            return (Criteria) this;
        }

        public Criteria andFfkamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FFKAmt not between", value1, value2, "ffkamt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.Avw_XD_Other
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}