package com.hongte.weixin.mybatis.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TCarExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    public TCarExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFitemidIsNull() {
            addCriterion("FitemID is null");
            return (Criteria) this;
        }

        public Criteria andFitemidIsNotNull() {
            addCriterion("FitemID is not null");
            return (Criteria) this;
        }

        public Criteria andFitemidEqualTo(Integer value) {
            addCriterion("FitemID =", value, "fitemid");
            return (Criteria) this;
        }

        public Criteria andFitemidNotEqualTo(Integer value) {
            addCriterion("FitemID <>", value, "fitemid");
            return (Criteria) this;
        }

        public Criteria andFitemidGreaterThan(Integer value) {
            addCriterion("FitemID >", value, "fitemid");
            return (Criteria) this;
        }

        public Criteria andFitemidGreaterThanOrEqualTo(Integer value) {
            addCriterion("FitemID >=", value, "fitemid");
            return (Criteria) this;
        }

        public Criteria andFitemidLessThan(Integer value) {
            addCriterion("FitemID <", value, "fitemid");
            return (Criteria) this;
        }

        public Criteria andFitemidLessThanOrEqualTo(Integer value) {
            addCriterion("FitemID <=", value, "fitemid");
            return (Criteria) this;
        }

        public Criteria andFitemidIn(List<Integer> values) {
            addCriterion("FitemID in", values, "fitemid");
            return (Criteria) this;
        }

        public Criteria andFitemidNotIn(List<Integer> values) {
            addCriterion("FitemID not in", values, "fitemid");
            return (Criteria) this;
        }

        public Criteria andFitemidBetween(Integer value1, Integer value2) {
            addCriterion("FitemID between", value1, value2, "fitemid");
            return (Criteria) this;
        }

        public Criteria andFitemidNotBetween(Integer value1, Integer value2) {
            addCriterion("FitemID not between", value1, value2, "fitemid");
            return (Criteria) this;
        }

        public Criteria andFnumberIsNull() {
            addCriterion("FNumber is null");
            return (Criteria) this;
        }

        public Criteria andFnumberIsNotNull() {
            addCriterion("FNumber is not null");
            return (Criteria) this;
        }

        public Criteria andFnumberEqualTo(String value) {
            addCriterion("FNumber =", value, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnumberNotEqualTo(String value) {
            addCriterion("FNumber <>", value, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnumberGreaterThan(String value) {
            addCriterion("FNumber >", value, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnumberGreaterThanOrEqualTo(String value) {
            addCriterion("FNumber >=", value, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnumberLessThan(String value) {
            addCriterion("FNumber <", value, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnumberLessThanOrEqualTo(String value) {
            addCriterion("FNumber <=", value, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnumberLike(String value) {
            addCriterion("FNumber like", value, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnumberNotLike(String value) {
            addCriterion("FNumber not like", value, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnumberIn(List<String> values) {
            addCriterion("FNumber in", values, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnumberNotIn(List<String> values) {
            addCriterion("FNumber not in", values, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnumberBetween(String value1, String value2) {
            addCriterion("FNumber between", value1, value2, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnumberNotBetween(String value1, String value2) {
            addCriterion("FNumber not between", value1, value2, "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnameIsNull() {
            addCriterion("FName is null");
            return (Criteria) this;
        }

        public Criteria andFnameIsNotNull() {
            addCriterion("FName is not null");
            return (Criteria) this;
        }

        public Criteria andFnameEqualTo(String value) {
            addCriterion("FName =", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameNotEqualTo(String value) {
            addCriterion("FName <>", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameGreaterThan(String value) {
            addCriterion("FName >", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameGreaterThanOrEqualTo(String value) {
            addCriterion("FName >=", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameLessThan(String value) {
            addCriterion("FName <", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameLessThanOrEqualTo(String value) {
            addCriterion("FName <=", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameLike(String value) {
            addCriterion("FName like", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameNotLike(String value) {
            addCriterion("FName not like", value, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameIn(List<String> values) {
            addCriterion("FName in", values, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameNotIn(List<String> values) {
            addCriterion("FName not in", values, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameBetween(String value1, String value2) {
            addCriterion("FName between", value1, value2, "fname");
            return (Criteria) this;
        }

        public Criteria andFnameNotBetween(String value1, String value2) {
            addCriterion("FName not between", value1, value2, "fname");
            return (Criteria) this;
        }

        public Criteria andFparentidIsNull() {
            addCriterion("FParentID is null");
            return (Criteria) this;
        }

        public Criteria andFparentidIsNotNull() {
            addCriterion("FParentID is not null");
            return (Criteria) this;
        }

        public Criteria andFparentidEqualTo(Integer value) {
            addCriterion("FParentID =", value, "fparentid");
            return (Criteria) this;
        }

        public Criteria andFparentidNotEqualTo(Integer value) {
            addCriterion("FParentID <>", value, "fparentid");
            return (Criteria) this;
        }

        public Criteria andFparentidGreaterThan(Integer value) {
            addCriterion("FParentID >", value, "fparentid");
            return (Criteria) this;
        }

        public Criteria andFparentidGreaterThanOrEqualTo(Integer value) {
            addCriterion("FParentID >=", value, "fparentid");
            return (Criteria) this;
        }

        public Criteria andFparentidLessThan(Integer value) {
            addCriterion("FParentID <", value, "fparentid");
            return (Criteria) this;
        }

        public Criteria andFparentidLessThanOrEqualTo(Integer value) {
            addCriterion("FParentID <=", value, "fparentid");
            return (Criteria) this;
        }

        public Criteria andFparentidIn(List<Integer> values) {
            addCriterion("FParentID in", values, "fparentid");
            return (Criteria) this;
        }

        public Criteria andFparentidNotIn(List<Integer> values) {
            addCriterion("FParentID not in", values, "fparentid");
            return (Criteria) this;
        }

        public Criteria andFparentidBetween(Integer value1, Integer value2) {
            addCriterion("FParentID between", value1, value2, "fparentid");
            return (Criteria) this;
        }

        public Criteria andFparentidNotBetween(Integer value1, Integer value2) {
            addCriterion("FParentID not between", value1, value2, "fparentid");
            return (Criteria) this;
        }

        public Criteria andFdetailIsNull() {
            addCriterion("FDetail is null");
            return (Criteria) this;
        }

        public Criteria andFdetailIsNotNull() {
            addCriterion("FDetail is not null");
            return (Criteria) this;
        }

        public Criteria andFdetailEqualTo(Boolean value) {
            addCriterion("FDetail =", value, "fdetail");
            return (Criteria) this;
        }

        public Criteria andFdetailNotEqualTo(Boolean value) {
            addCriterion("FDetail <>", value, "fdetail");
            return (Criteria) this;
        }

        public Criteria andFdetailGreaterThan(Boolean value) {
            addCriterion("FDetail >", value, "fdetail");
            return (Criteria) this;
        }

        public Criteria andFdetailGreaterThanOrEqualTo(Boolean value) {
            addCriterion("FDetail >=", value, "fdetail");
            return (Criteria) this;
        }

        public Criteria andFdetailLessThan(Boolean value) {
            addCriterion("FDetail <", value, "fdetail");
            return (Criteria) this;
        }

        public Criteria andFdetailLessThanOrEqualTo(Boolean value) {
            addCriterion("FDetail <=", value, "fdetail");
            return (Criteria) this;
        }

        public Criteria andFdetailIn(List<Boolean> values) {
            addCriterion("FDetail in", values, "fdetail");
            return (Criteria) this;
        }

        public Criteria andFdetailNotIn(List<Boolean> values) {
            addCriterion("FDetail not in", values, "fdetail");
            return (Criteria) this;
        }

        public Criteria andFdetailBetween(Boolean value1, Boolean value2) {
            addCriterion("FDetail between", value1, value2, "fdetail");
            return (Criteria) this;
        }

        public Criteria andFdetailNotBetween(Boolean value1, Boolean value2) {
            addCriterion("FDetail not between", value1, value2, "fdetail");
            return (Criteria) this;
        }

        public Criteria andFunusedIsNull() {
            addCriterion("FUnused is null");
            return (Criteria) this;
        }

        public Criteria andFunusedIsNotNull() {
            addCriterion("FUnused is not null");
            return (Criteria) this;
        }

        public Criteria andFunusedEqualTo(Boolean value) {
            addCriterion("FUnused =", value, "funused");
            return (Criteria) this;
        }

        public Criteria andFunusedNotEqualTo(Boolean value) {
            addCriterion("FUnused <>", value, "funused");
            return (Criteria) this;
        }

        public Criteria andFunusedGreaterThan(Boolean value) {
            addCriterion("FUnused >", value, "funused");
            return (Criteria) this;
        }

        public Criteria andFunusedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("FUnused >=", value, "funused");
            return (Criteria) this;
        }

        public Criteria andFunusedLessThan(Boolean value) {
            addCriterion("FUnused <", value, "funused");
            return (Criteria) this;
        }

        public Criteria andFunusedLessThanOrEqualTo(Boolean value) {
            addCriterion("FUnused <=", value, "funused");
            return (Criteria) this;
        }

        public Criteria andFunusedIn(List<Boolean> values) {
            addCriterion("FUnused in", values, "funused");
            return (Criteria) this;
        }

        public Criteria andFunusedNotIn(List<Boolean> values) {
            addCriterion("FUnused not in", values, "funused");
            return (Criteria) this;
        }

        public Criteria andFunusedBetween(Boolean value1, Boolean value2) {
            addCriterion("FUnused between", value1, value2, "funused");
            return (Criteria) this;
        }

        public Criteria andFunusedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("FUnused not between", value1, value2, "funused");
            return (Criteria) this;
        }

        public Criteria andFstatusIsNull() {
            addCriterion("FStatus is null");
            return (Criteria) this;
        }

        public Criteria andFstatusIsNotNull() {
            addCriterion("FStatus is not null");
            return (Criteria) this;
        }

        public Criteria andFstatusEqualTo(String value) {
            addCriterion("FStatus =", value, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusNotEqualTo(String value) {
            addCriterion("FStatus <>", value, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusGreaterThan(String value) {
            addCriterion("FStatus >", value, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusGreaterThanOrEqualTo(String value) {
            addCriterion("FStatus >=", value, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusLessThan(String value) {
            addCriterion("FStatus <", value, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusLessThanOrEqualTo(String value) {
            addCriterion("FStatus <=", value, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusLike(String value) {
            addCriterion("FStatus like", value, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusNotLike(String value) {
            addCriterion("FStatus not like", value, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusIn(List<String> values) {
            addCriterion("FStatus in", values, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusNotIn(List<String> values) {
            addCriterion("FStatus not in", values, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusBetween(String value1, String value2) {
            addCriterion("FStatus between", value1, value2, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusNotBetween(String value1, String value2) {
            addCriterion("FStatus not between", value1, value2, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFlevelIsNull() {
            addCriterion("FLevel is null");
            return (Criteria) this;
        }

        public Criteria andFlevelIsNotNull() {
            addCriterion("FLevel is not null");
            return (Criteria) this;
        }

        public Criteria andFlevelEqualTo(BigDecimal value) {
            addCriterion("FLevel =", value, "flevel");
            return (Criteria) this;
        }

        public Criteria andFlevelNotEqualTo(BigDecimal value) {
            addCriterion("FLevel <>", value, "flevel");
            return (Criteria) this;
        }

        public Criteria andFlevelGreaterThan(BigDecimal value) {
            addCriterion("FLevel >", value, "flevel");
            return (Criteria) this;
        }

        public Criteria andFlevelGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FLevel >=", value, "flevel");
            return (Criteria) this;
        }

        public Criteria andFlevelLessThan(BigDecimal value) {
            addCriterion("FLevel <", value, "flevel");
            return (Criteria) this;
        }

        public Criteria andFlevelLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FLevel <=", value, "flevel");
            return (Criteria) this;
        }

        public Criteria andFlevelIn(List<BigDecimal> values) {
            addCriterion("FLevel in", values, "flevel");
            return (Criteria) this;
        }

        public Criteria andFlevelNotIn(List<BigDecimal> values) {
            addCriterion("FLevel not in", values, "flevel");
            return (Criteria) this;
        }

        public Criteria andFlevelBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FLevel between", value1, value2, "flevel");
            return (Criteria) this;
        }

        public Criteria andFlevelNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FLevel not between", value1, value2, "flevel");
            return (Criteria) this;
        }

        public Criteria andFhelpnumberIsNull() {
            addCriterion("FHelpNumber is null");
            return (Criteria) this;
        }

        public Criteria andFhelpnumberIsNotNull() {
            addCriterion("FHelpNumber is not null");
            return (Criteria) this;
        }

        public Criteria andFhelpnumberEqualTo(String value) {
            addCriterion("FHelpNumber =", value, "fhelpnumber");
            return (Criteria) this;
        }

        public Criteria andFhelpnumberNotEqualTo(String value) {
            addCriterion("FHelpNumber <>", value, "fhelpnumber");
            return (Criteria) this;
        }

        public Criteria andFhelpnumberGreaterThan(String value) {
            addCriterion("FHelpNumber >", value, "fhelpnumber");
            return (Criteria) this;
        }

        public Criteria andFhelpnumberGreaterThanOrEqualTo(String value) {
            addCriterion("FHelpNumber >=", value, "fhelpnumber");
            return (Criteria) this;
        }

        public Criteria andFhelpnumberLessThan(String value) {
            addCriterion("FHelpNumber <", value, "fhelpnumber");
            return (Criteria) this;
        }

        public Criteria andFhelpnumberLessThanOrEqualTo(String value) {
            addCriterion("FHelpNumber <=", value, "fhelpnumber");
            return (Criteria) this;
        }

        public Criteria andFhelpnumberLike(String value) {
            addCriterion("FHelpNumber like", value, "fhelpnumber");
            return (Criteria) this;
        }

        public Criteria andFhelpnumberNotLike(String value) {
            addCriterion("FHelpNumber not like", value, "fhelpnumber");
            return (Criteria) this;
        }

        public Criteria andFhelpnumberIn(List<String> values) {
            addCriterion("FHelpNumber in", values, "fhelpnumber");
            return (Criteria) this;
        }

        public Criteria andFhelpnumberNotIn(List<String> values) {
            addCriterion("FHelpNumber not in", values, "fhelpnumber");
            return (Criteria) this;
        }

        public Criteria andFhelpnumberBetween(String value1, String value2) {
            addCriterion("FHelpNumber between", value1, value2, "fhelpnumber");
            return (Criteria) this;
        }

        public Criteria andFhelpnumberNotBetween(String value1, String value2) {
            addCriterion("FHelpNumber not between", value1, value2, "fhelpnumber");
            return (Criteria) this;
        }

        public Criteria andFseatnumberIsNull() {
            addCriterion("FSeatNumber is null");
            return (Criteria) this;
        }

        public Criteria andFseatnumberIsNotNull() {
            addCriterion("FSeatNumber is not null");
            return (Criteria) this;
        }

        public Criteria andFseatnumberEqualTo(BigDecimal value) {
            addCriterion("FSeatNumber =", value, "fseatnumber");
            return (Criteria) this;
        }

        public Criteria andFseatnumberNotEqualTo(BigDecimal value) {
            addCriterion("FSeatNumber <>", value, "fseatnumber");
            return (Criteria) this;
        }

        public Criteria andFseatnumberGreaterThan(BigDecimal value) {
            addCriterion("FSeatNumber >", value, "fseatnumber");
            return (Criteria) this;
        }

        public Criteria andFseatnumberGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FSeatNumber >=", value, "fseatnumber");
            return (Criteria) this;
        }

        public Criteria andFseatnumberLessThan(BigDecimal value) {
            addCriterion("FSeatNumber <", value, "fseatnumber");
            return (Criteria) this;
        }

        public Criteria andFseatnumberLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FSeatNumber <=", value, "fseatnumber");
            return (Criteria) this;
        }

        public Criteria andFseatnumberIn(List<BigDecimal> values) {
            addCriterion("FSeatNumber in", values, "fseatnumber");
            return (Criteria) this;
        }

        public Criteria andFseatnumberNotIn(List<BigDecimal> values) {
            addCriterion("FSeatNumber not in", values, "fseatnumber");
            return (Criteria) this;
        }

        public Criteria andFseatnumberBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FSeatNumber between", value1, value2, "fseatnumber");
            return (Criteria) this;
        }

        public Criteria andFseatnumberNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FSeatNumber not between", value1, value2, "fseatnumber");
            return (Criteria) this;
        }

        public Criteria andFpriceIsNull() {
            addCriterion("FPrice is null");
            return (Criteria) this;
        }

        public Criteria andFpriceIsNotNull() {
            addCriterion("FPrice is not null");
            return (Criteria) this;
        }

        public Criteria andFpriceEqualTo(BigDecimal value) {
            addCriterion("FPrice =", value, "fprice");
            return (Criteria) this;
        }

        public Criteria andFpriceNotEqualTo(BigDecimal value) {
            addCriterion("FPrice <>", value, "fprice");
            return (Criteria) this;
        }

        public Criteria andFpriceGreaterThan(BigDecimal value) {
            addCriterion("FPrice >", value, "fprice");
            return (Criteria) this;
        }

        public Criteria andFpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FPrice >=", value, "fprice");
            return (Criteria) this;
        }

        public Criteria andFpriceLessThan(BigDecimal value) {
            addCriterion("FPrice <", value, "fprice");
            return (Criteria) this;
        }

        public Criteria andFpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FPrice <=", value, "fprice");
            return (Criteria) this;
        }

        public Criteria andFpriceIn(List<BigDecimal> values) {
            addCriterion("FPrice in", values, "fprice");
            return (Criteria) this;
        }

        public Criteria andFpriceNotIn(List<BigDecimal> values) {
            addCriterion("FPrice not in", values, "fprice");
            return (Criteria) this;
        }

        public Criteria andFpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FPrice between", value1, value2, "fprice");
            return (Criteria) this;
        }

        public Criteria andFpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FPrice not between", value1, value2, "fprice");
            return (Criteria) this;
        }

        public Criteria andFtypeIsNull() {
            addCriterion("FType is null");
            return (Criteria) this;
        }

        public Criteria andFtypeIsNotNull() {
            addCriterion("FType is not null");
            return (Criteria) this;
        }

        public Criteria andFtypeEqualTo(String value) {
            addCriterion("FType =", value, "ftype");
            return (Criteria) this;
        }

        public Criteria andFtypeNotEqualTo(String value) {
            addCriterion("FType <>", value, "ftype");
            return (Criteria) this;
        }

        public Criteria andFtypeGreaterThan(String value) {
            addCriterion("FType >", value, "ftype");
            return (Criteria) this;
        }

        public Criteria andFtypeGreaterThanOrEqualTo(String value) {
            addCriterion("FType >=", value, "ftype");
            return (Criteria) this;
        }

        public Criteria andFtypeLessThan(String value) {
            addCriterion("FType <", value, "ftype");
            return (Criteria) this;
        }

        public Criteria andFtypeLessThanOrEqualTo(String value) {
            addCriterion("FType <=", value, "ftype");
            return (Criteria) this;
        }

        public Criteria andFtypeLike(String value) {
            addCriterion("FType like", value, "ftype");
            return (Criteria) this;
        }

        public Criteria andFtypeNotLike(String value) {
            addCriterion("FType not like", value, "ftype");
            return (Criteria) this;
        }

        public Criteria andFtypeIn(List<String> values) {
            addCriterion("FType in", values, "ftype");
            return (Criteria) this;
        }

        public Criteria andFtypeNotIn(List<String> values) {
            addCriterion("FType not in", values, "ftype");
            return (Criteria) this;
        }

        public Criteria andFtypeBetween(String value1, String value2) {
            addCriterion("FType between", value1, value2, "ftype");
            return (Criteria) this;
        }

        public Criteria andFtypeNotBetween(String value1, String value2) {
            addCriterion("FType not between", value1, value2, "ftype");
            return (Criteria) this;
        }

        public Criteria andFnumberLikeInsensitive(String value) {
            addCriterion("upper(FNumber) like", value.toUpperCase(), "fnumber");
            return (Criteria) this;
        }

        public Criteria andFnameLikeInsensitive(String value) {
            addCriterion("upper(FName) like", value.toUpperCase(), "fname");
            return (Criteria) this;
        }

        public Criteria andFstatusLikeInsensitive(String value) {
            addCriterion("upper(FStatus) like", value.toUpperCase(), "fstatus");
            return (Criteria) this;
        }

        public Criteria andFhelpnumberLikeInsensitive(String value) {
            addCriterion("upper(FHelpNumber) like", value.toUpperCase(), "fhelpnumber");
            return (Criteria) this;
        }

        public Criteria andFtypeLikeInsensitive(String value) {
            addCriterion("upper(FType) like", value.toUpperCase(), "ftype");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.T_Car
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}