package com.hongte.weixin.mybatis.domain;

import java.io.Serializable;

public class TCar implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.T_Car.FitemID
     *
     * @mbggenerated
     */
    private Integer id;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.T_Car.FName
     *
     * @mbggenerated
     */
    private String value;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.T_Car
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;


	public Integer getId() {
		return id;
	}


	public String getValue() {
		return value;
	}


	public void setId(Integer id) {
		this.id = id;
	}


	public void setValue(String value) {
		this.value = value;
	}

}