package com.hongte.weixin.mybatis.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class XdCusthinfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FID
     *
     * @mbggenerated
     */
    private Integer fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFOwer
     *
     * @mbggenerated
     */
    private String ffower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFRelation
     *
     * @mbggenerated
     */
    private Integer ffrelation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFArea
     *
     * @mbggenerated
     */
    private String ffarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFType
     *
     * @mbggenerated
     */
    private Integer fftype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFAdd
     *
     * @mbggenerated
     */
    private String ffadd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFPrice
     *
     * @mbggenerated
     */
    private BigDecimal ffprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFFirstPay
     *
     * @mbggenerated
     */
    private BigDecimal fffirstpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFDebitAmt
     *
     * @mbggenerated
     */
    private BigDecimal ffdebitamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FHPayMonth
     *
     * @mbggenerated
     */
    private BigDecimal fhpaymonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFPledgeMonth
     *
     * @mbggenerated
     */
    private BigDecimal ffpledgemonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFPledgeDate
     *
     * @mbggenerated
     */
    private Date ffpledgedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FHomeGet
     *
     * @mbggenerated
     */
    private BigDecimal fhomeget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FHomePGet
     *
     * @mbggenerated
     */
    private BigDecimal fhomepget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FSRHDB
     *
     * @mbggenerated
     */
    private BigDecimal fsrhdb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FJTJSR
     *
     * @mbggenerated
     */
    private BigDecimal fjtjsr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FHomeDebit
     *
     * @mbggenerated
     */
    private BigDecimal fhomedebit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FJZCDK
     *
     * @mbggenerated
     */
    private BigDecimal fjzcdk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFNJCK
     *
     * @mbggenerated
     */
    private BigDecimal ffnjck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FRJZFMJ
     *
     * @mbggenerated
     */
    private BigDecimal frjzfmj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FJZFCK
     *
     * @mbggenerated
     */
    private BigDecimal fjzfck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FJYJZQ
     *
     * @mbggenerated
     */
    private BigDecimal fjyjzq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FJSWZC
     *
     * @mbggenerated
     */
    private BigDecimal fjswzc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FJDWTZ
     *
     * @mbggenerated
     */
    private BigDecimal fjdwtz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FJZJF
     *
     * @mbggenerated
     */
    private BigDecimal fjzjf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FHomeNote
     *
     * @mbggenerated
     */
    private String fhomenote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFFC
     *
     * @mbggenerated
     */
    private BigDecimal fffc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFCar
     *
     * @mbggenerated
     */
    private String ffcar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFGP
     *
     * @mbggenerated
     */
    private BigDecimal ffgp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFJJ
     *
     * @mbggenerated
     */
    private BigDecimal ffjj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFInsure
     *
     * @mbggenerated
     */
    private BigDecimal ffinsure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFJYZH
     *
     * @mbggenerated
     */
    private BigDecimal ffjyzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFOther
     *
     * @mbggenerated
     */
    private BigDecimal ffother;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FOwnTotal
     *
     * @mbggenerated
     */
    private BigDecimal fowntotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFHDebit
     *
     * @mbggenerated
     */
    private BigDecimal ffhdebit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFCDebit
     *
     * @mbggenerated
     */
    private BigDecimal ffcdebit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFCardDebit
     *
     * @mbggenerated
     */
    private BigDecimal ffcarddebit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFGRDebit
     *
     * @mbggenerated
     */
    private BigDecimal ffgrdebit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFOtherDebit
     *
     * @mbggenerated
     */
    private BigDecimal ffotherdebit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFDebitTotal
     *
     * @mbggenerated
     */
    private BigDecimal ffdebittotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FTotal
     *
     * @mbggenerated
     */
    private BigDecimal ftotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FJKRecord
     *
     * @mbggenerated
     */
    private Integer fjkrecord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FDKCS
     *
     * @mbggenerated
     */
    private BigDecimal fdkcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FOwner
     *
     * @mbggenerated
     */
    private String fowner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FRelationship
     *
     * @mbggenerated
     */
    private String frelationship;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FArea
     *
     * @mbggenerated
     */
    private String farea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFWAdd
     *
     * @mbggenerated
     */
    private String ffwadd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FPostZJ
     *
     * @mbggenerated
     */
    private String fpostzj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FSum
     *
     * @mbggenerated
     */
    private BigDecimal fsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FHType
     *
     * @mbggenerated
     */
    private Integer fhtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FHCarNO
     *
     * @mbggenerated
     */
    private String fhcarno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FHNote
     *
     * @mbggenerated
     */
    private String fhnote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FArea1
     *
     * @mbggenerated
     */
    private String farea1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FAreaGT
     *
     * @mbggenerated
     */
    private String fareagt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFInsure2
     *
     * @mbggenerated
     */
    private String ffinsure2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFInsure1
     *
     * @mbggenerated
     */
    private String ffinsure1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FCarQty
     *
     * @mbggenerated
     */
    private BigDecimal fcarqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FFPCX
     *
     * @mbggenerated
     */
    private String ffpcx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FOwner1
     *
     * @mbggenerated
     */
    private String fowner1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FHRelation1
     *
     * @mbggenerated
     */
    private String fhrelation1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustHInfo.FHouseAdd1
     *
     * @mbggenerated
     */
    private String fhouseadd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.XD_CustHInfo
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FID
     *
     * @return the value of dbo.XD_CustHInfo.FID
     *
     * @mbggenerated
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FID
     *
     * @param fid the value for dbo.XD_CustHInfo.FID
     *
     * @mbggenerated
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFOwer
     *
     * @return the value of dbo.XD_CustHInfo.FFOwer
     *
     * @mbggenerated
     */
    public String getFfower() {
        return ffower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFOwer
     *
     * @param ffower the value for dbo.XD_CustHInfo.FFOwer
     *
     * @mbggenerated
     */
    public void setFfower(String ffower) {
        this.ffower = ffower == null ? null : ffower.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFRelation
     *
     * @return the value of dbo.XD_CustHInfo.FFRelation
     *
     * @mbggenerated
     */
    public Integer getFfrelation() {
        return ffrelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFRelation
     *
     * @param ffrelation the value for dbo.XD_CustHInfo.FFRelation
     *
     * @mbggenerated
     */
    public void setFfrelation(Integer ffrelation) {
        this.ffrelation = ffrelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFArea
     *
     * @return the value of dbo.XD_CustHInfo.FFArea
     *
     * @mbggenerated
     */
    public String getFfarea() {
        return ffarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFArea
     *
     * @param ffarea the value for dbo.XD_CustHInfo.FFArea
     *
     * @mbggenerated
     */
    public void setFfarea(String ffarea) {
        this.ffarea = ffarea == null ? null : ffarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFType
     *
     * @return the value of dbo.XD_CustHInfo.FFType
     *
     * @mbggenerated
     */
    public Integer getFftype() {
        return fftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFType
     *
     * @param fftype the value for dbo.XD_CustHInfo.FFType
     *
     * @mbggenerated
     */
    public void setFftype(Integer fftype) {
        this.fftype = fftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFAdd
     *
     * @return the value of dbo.XD_CustHInfo.FFAdd
     *
     * @mbggenerated
     */
    public String getFfadd() {
        return ffadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFAdd
     *
     * @param ffadd the value for dbo.XD_CustHInfo.FFAdd
     *
     * @mbggenerated
     */
    public void setFfadd(String ffadd) {
        this.ffadd = ffadd == null ? null : ffadd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFPrice
     *
     * @return the value of dbo.XD_CustHInfo.FFPrice
     *
     * @mbggenerated
     */
    public BigDecimal getFfprice() {
        return ffprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFPrice
     *
     * @param ffprice the value for dbo.XD_CustHInfo.FFPrice
     *
     * @mbggenerated
     */
    public void setFfprice(BigDecimal ffprice) {
        this.ffprice = ffprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFFirstPay
     *
     * @return the value of dbo.XD_CustHInfo.FFFirstPay
     *
     * @mbggenerated
     */
    public BigDecimal getFffirstpay() {
        return fffirstpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFFirstPay
     *
     * @param fffirstpay the value for dbo.XD_CustHInfo.FFFirstPay
     *
     * @mbggenerated
     */
    public void setFffirstpay(BigDecimal fffirstpay) {
        this.fffirstpay = fffirstpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFDebitAmt
     *
     * @return the value of dbo.XD_CustHInfo.FFDebitAmt
     *
     * @mbggenerated
     */
    public BigDecimal getFfdebitamt() {
        return ffdebitamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFDebitAmt
     *
     * @param ffdebitamt the value for dbo.XD_CustHInfo.FFDebitAmt
     *
     * @mbggenerated
     */
    public void setFfdebitamt(BigDecimal ffdebitamt) {
        this.ffdebitamt = ffdebitamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FHPayMonth
     *
     * @return the value of dbo.XD_CustHInfo.FHPayMonth
     *
     * @mbggenerated
     */
    public BigDecimal getFhpaymonth() {
        return fhpaymonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FHPayMonth
     *
     * @param fhpaymonth the value for dbo.XD_CustHInfo.FHPayMonth
     *
     * @mbggenerated
     */
    public void setFhpaymonth(BigDecimal fhpaymonth) {
        this.fhpaymonth = fhpaymonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFPledgeMonth
     *
     * @return the value of dbo.XD_CustHInfo.FFPledgeMonth
     *
     * @mbggenerated
     */
    public BigDecimal getFfpledgemonth() {
        return ffpledgemonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFPledgeMonth
     *
     * @param ffpledgemonth the value for dbo.XD_CustHInfo.FFPledgeMonth
     *
     * @mbggenerated
     */
    public void setFfpledgemonth(BigDecimal ffpledgemonth) {
        this.ffpledgemonth = ffpledgemonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFPledgeDate
     *
     * @return the value of dbo.XD_CustHInfo.FFPledgeDate
     *
     * @mbggenerated
     */
    public Date getFfpledgedate() {
        return ffpledgedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFPledgeDate
     *
     * @param ffpledgedate the value for dbo.XD_CustHInfo.FFPledgeDate
     *
     * @mbggenerated
     */
    public void setFfpledgedate(Date ffpledgedate) {
        this.ffpledgedate = ffpledgedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FHomeGet
     *
     * @return the value of dbo.XD_CustHInfo.FHomeGet
     *
     * @mbggenerated
     */
    public BigDecimal getFhomeget() {
        return fhomeget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FHomeGet
     *
     * @param fhomeget the value for dbo.XD_CustHInfo.FHomeGet
     *
     * @mbggenerated
     */
    public void setFhomeget(BigDecimal fhomeget) {
        this.fhomeget = fhomeget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FHomePGet
     *
     * @return the value of dbo.XD_CustHInfo.FHomePGet
     *
     * @mbggenerated
     */
    public BigDecimal getFhomepget() {
        return fhomepget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FHomePGet
     *
     * @param fhomepget the value for dbo.XD_CustHInfo.FHomePGet
     *
     * @mbggenerated
     */
    public void setFhomepget(BigDecimal fhomepget) {
        this.fhomepget = fhomepget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FSRHDB
     *
     * @return the value of dbo.XD_CustHInfo.FSRHDB
     *
     * @mbggenerated
     */
    public BigDecimal getFsrhdb() {
        return fsrhdb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FSRHDB
     *
     * @param fsrhdb the value for dbo.XD_CustHInfo.FSRHDB
     *
     * @mbggenerated
     */
    public void setFsrhdb(BigDecimal fsrhdb) {
        this.fsrhdb = fsrhdb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FJTJSR
     *
     * @return the value of dbo.XD_CustHInfo.FJTJSR
     *
     * @mbggenerated
     */
    public BigDecimal getFjtjsr() {
        return fjtjsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FJTJSR
     *
     * @param fjtjsr the value for dbo.XD_CustHInfo.FJTJSR
     *
     * @mbggenerated
     */
    public void setFjtjsr(BigDecimal fjtjsr) {
        this.fjtjsr = fjtjsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FHomeDebit
     *
     * @return the value of dbo.XD_CustHInfo.FHomeDebit
     *
     * @mbggenerated
     */
    public BigDecimal getFhomedebit() {
        return fhomedebit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FHomeDebit
     *
     * @param fhomedebit the value for dbo.XD_CustHInfo.FHomeDebit
     *
     * @mbggenerated
     */
    public void setFhomedebit(BigDecimal fhomedebit) {
        this.fhomedebit = fhomedebit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FJZCDK
     *
     * @return the value of dbo.XD_CustHInfo.FJZCDK
     *
     * @mbggenerated
     */
    public BigDecimal getFjzcdk() {
        return fjzcdk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FJZCDK
     *
     * @param fjzcdk the value for dbo.XD_CustHInfo.FJZCDK
     *
     * @mbggenerated
     */
    public void setFjzcdk(BigDecimal fjzcdk) {
        this.fjzcdk = fjzcdk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFNJCK
     *
     * @return the value of dbo.XD_CustHInfo.FFNJCK
     *
     * @mbggenerated
     */
    public BigDecimal getFfnjck() {
        return ffnjck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFNJCK
     *
     * @param ffnjck the value for dbo.XD_CustHInfo.FFNJCK
     *
     * @mbggenerated
     */
    public void setFfnjck(BigDecimal ffnjck) {
        this.ffnjck = ffnjck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FRJZFMJ
     *
     * @return the value of dbo.XD_CustHInfo.FRJZFMJ
     *
     * @mbggenerated
     */
    public BigDecimal getFrjzfmj() {
        return frjzfmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FRJZFMJ
     *
     * @param frjzfmj the value for dbo.XD_CustHInfo.FRJZFMJ
     *
     * @mbggenerated
     */
    public void setFrjzfmj(BigDecimal frjzfmj) {
        this.frjzfmj = frjzfmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FJZFCK
     *
     * @return the value of dbo.XD_CustHInfo.FJZFCK
     *
     * @mbggenerated
     */
    public BigDecimal getFjzfck() {
        return fjzfck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FJZFCK
     *
     * @param fjzfck the value for dbo.XD_CustHInfo.FJZFCK
     *
     * @mbggenerated
     */
    public void setFjzfck(BigDecimal fjzfck) {
        this.fjzfck = fjzfck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FJYJZQ
     *
     * @return the value of dbo.XD_CustHInfo.FJYJZQ
     *
     * @mbggenerated
     */
    public BigDecimal getFjyjzq() {
        return fjyjzq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FJYJZQ
     *
     * @param fjyjzq the value for dbo.XD_CustHInfo.FJYJZQ
     *
     * @mbggenerated
     */
    public void setFjyjzq(BigDecimal fjyjzq) {
        this.fjyjzq = fjyjzq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FJSWZC
     *
     * @return the value of dbo.XD_CustHInfo.FJSWZC
     *
     * @mbggenerated
     */
    public BigDecimal getFjswzc() {
        return fjswzc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FJSWZC
     *
     * @param fjswzc the value for dbo.XD_CustHInfo.FJSWZC
     *
     * @mbggenerated
     */
    public void setFjswzc(BigDecimal fjswzc) {
        this.fjswzc = fjswzc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FJDWTZ
     *
     * @return the value of dbo.XD_CustHInfo.FJDWTZ
     *
     * @mbggenerated
     */
    public BigDecimal getFjdwtz() {
        return fjdwtz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FJDWTZ
     *
     * @param fjdwtz the value for dbo.XD_CustHInfo.FJDWTZ
     *
     * @mbggenerated
     */
    public void setFjdwtz(BigDecimal fjdwtz) {
        this.fjdwtz = fjdwtz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FJZJF
     *
     * @return the value of dbo.XD_CustHInfo.FJZJF
     *
     * @mbggenerated
     */
    public BigDecimal getFjzjf() {
        return fjzjf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FJZJF
     *
     * @param fjzjf the value for dbo.XD_CustHInfo.FJZJF
     *
     * @mbggenerated
     */
    public void setFjzjf(BigDecimal fjzjf) {
        this.fjzjf = fjzjf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FHomeNote
     *
     * @return the value of dbo.XD_CustHInfo.FHomeNote
     *
     * @mbggenerated
     */
    public String getFhomenote() {
        return fhomenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FHomeNote
     *
     * @param fhomenote the value for dbo.XD_CustHInfo.FHomeNote
     *
     * @mbggenerated
     */
    public void setFhomenote(String fhomenote) {
        this.fhomenote = fhomenote == null ? null : fhomenote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFFC
     *
     * @return the value of dbo.XD_CustHInfo.FFFC
     *
     * @mbggenerated
     */
    public BigDecimal getFffc() {
        return fffc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFFC
     *
     * @param fffc the value for dbo.XD_CustHInfo.FFFC
     *
     * @mbggenerated
     */
    public void setFffc(BigDecimal fffc) {
        this.fffc = fffc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFCar
     *
     * @return the value of dbo.XD_CustHInfo.FFCar
     *
     * @mbggenerated
     */
    public String getFfcar() {
        return ffcar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFCar
     *
     * @param ffcar the value for dbo.XD_CustHInfo.FFCar
     *
     * @mbggenerated
     */
    public void setFfcar(String ffcar) {
        this.ffcar = ffcar == null ? null : ffcar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFGP
     *
     * @return the value of dbo.XD_CustHInfo.FFGP
     *
     * @mbggenerated
     */
    public BigDecimal getFfgp() {
        return ffgp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFGP
     *
     * @param ffgp the value for dbo.XD_CustHInfo.FFGP
     *
     * @mbggenerated
     */
    public void setFfgp(BigDecimal ffgp) {
        this.ffgp = ffgp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFJJ
     *
     * @return the value of dbo.XD_CustHInfo.FFJJ
     *
     * @mbggenerated
     */
    public BigDecimal getFfjj() {
        return ffjj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFJJ
     *
     * @param ffjj the value for dbo.XD_CustHInfo.FFJJ
     *
     * @mbggenerated
     */
    public void setFfjj(BigDecimal ffjj) {
        this.ffjj = ffjj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFInsure
     *
     * @return the value of dbo.XD_CustHInfo.FFInsure
     *
     * @mbggenerated
     */
    public BigDecimal getFfinsure() {
        return ffinsure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFInsure
     *
     * @param ffinsure the value for dbo.XD_CustHInfo.FFInsure
     *
     * @mbggenerated
     */
    public void setFfinsure(BigDecimal ffinsure) {
        this.ffinsure = ffinsure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFJYZH
     *
     * @return the value of dbo.XD_CustHInfo.FFJYZH
     *
     * @mbggenerated
     */
    public BigDecimal getFfjyzh() {
        return ffjyzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFJYZH
     *
     * @param ffjyzh the value for dbo.XD_CustHInfo.FFJYZH
     *
     * @mbggenerated
     */
    public void setFfjyzh(BigDecimal ffjyzh) {
        this.ffjyzh = ffjyzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFOther
     *
     * @return the value of dbo.XD_CustHInfo.FFOther
     *
     * @mbggenerated
     */
    public BigDecimal getFfother() {
        return ffother;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFOther
     *
     * @param ffother the value for dbo.XD_CustHInfo.FFOther
     *
     * @mbggenerated
     */
    public void setFfother(BigDecimal ffother) {
        this.ffother = ffother;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FOwnTotal
     *
     * @return the value of dbo.XD_CustHInfo.FOwnTotal
     *
     * @mbggenerated
     */
    public BigDecimal getFowntotal() {
        return fowntotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FOwnTotal
     *
     * @param fowntotal the value for dbo.XD_CustHInfo.FOwnTotal
     *
     * @mbggenerated
     */
    public void setFowntotal(BigDecimal fowntotal) {
        this.fowntotal = fowntotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFHDebit
     *
     * @return the value of dbo.XD_CustHInfo.FFHDebit
     *
     * @mbggenerated
     */
    public BigDecimal getFfhdebit() {
        return ffhdebit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFHDebit
     *
     * @param ffhdebit the value for dbo.XD_CustHInfo.FFHDebit
     *
     * @mbggenerated
     */
    public void setFfhdebit(BigDecimal ffhdebit) {
        this.ffhdebit = ffhdebit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFCDebit
     *
     * @return the value of dbo.XD_CustHInfo.FFCDebit
     *
     * @mbggenerated
     */
    public BigDecimal getFfcdebit() {
        return ffcdebit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFCDebit
     *
     * @param ffcdebit the value for dbo.XD_CustHInfo.FFCDebit
     *
     * @mbggenerated
     */
    public void setFfcdebit(BigDecimal ffcdebit) {
        this.ffcdebit = ffcdebit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFCardDebit
     *
     * @return the value of dbo.XD_CustHInfo.FFCardDebit
     *
     * @mbggenerated
     */
    public BigDecimal getFfcarddebit() {
        return ffcarddebit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFCardDebit
     *
     * @param ffcarddebit the value for dbo.XD_CustHInfo.FFCardDebit
     *
     * @mbggenerated
     */
    public void setFfcarddebit(BigDecimal ffcarddebit) {
        this.ffcarddebit = ffcarddebit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFGRDebit
     *
     * @return the value of dbo.XD_CustHInfo.FFGRDebit
     *
     * @mbggenerated
     */
    public BigDecimal getFfgrdebit() {
        return ffgrdebit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFGRDebit
     *
     * @param ffgrdebit the value for dbo.XD_CustHInfo.FFGRDebit
     *
     * @mbggenerated
     */
    public void setFfgrdebit(BigDecimal ffgrdebit) {
        this.ffgrdebit = ffgrdebit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFOtherDebit
     *
     * @return the value of dbo.XD_CustHInfo.FFOtherDebit
     *
     * @mbggenerated
     */
    public BigDecimal getFfotherdebit() {
        return ffotherdebit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFOtherDebit
     *
     * @param ffotherdebit the value for dbo.XD_CustHInfo.FFOtherDebit
     *
     * @mbggenerated
     */
    public void setFfotherdebit(BigDecimal ffotherdebit) {
        this.ffotherdebit = ffotherdebit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFDebitTotal
     *
     * @return the value of dbo.XD_CustHInfo.FFDebitTotal
     *
     * @mbggenerated
     */
    public BigDecimal getFfdebittotal() {
        return ffdebittotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFDebitTotal
     *
     * @param ffdebittotal the value for dbo.XD_CustHInfo.FFDebitTotal
     *
     * @mbggenerated
     */
    public void setFfdebittotal(BigDecimal ffdebittotal) {
        this.ffdebittotal = ffdebittotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FTotal
     *
     * @return the value of dbo.XD_CustHInfo.FTotal
     *
     * @mbggenerated
     */
    public BigDecimal getFtotal() {
        return ftotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FTotal
     *
     * @param ftotal the value for dbo.XD_CustHInfo.FTotal
     *
     * @mbggenerated
     */
    public void setFtotal(BigDecimal ftotal) {
        this.ftotal = ftotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FJKRecord
     *
     * @return the value of dbo.XD_CustHInfo.FJKRecord
     *
     * @mbggenerated
     */
    public Integer getFjkrecord() {
        return fjkrecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FJKRecord
     *
     * @param fjkrecord the value for dbo.XD_CustHInfo.FJKRecord
     *
     * @mbggenerated
     */
    public void setFjkrecord(Integer fjkrecord) {
        this.fjkrecord = fjkrecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FDKCS
     *
     * @return the value of dbo.XD_CustHInfo.FDKCS
     *
     * @mbggenerated
     */
    public BigDecimal getFdkcs() {
        return fdkcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FDKCS
     *
     * @param fdkcs the value for dbo.XD_CustHInfo.FDKCS
     *
     * @mbggenerated
     */
    public void setFdkcs(BigDecimal fdkcs) {
        this.fdkcs = fdkcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FOwner
     *
     * @return the value of dbo.XD_CustHInfo.FOwner
     *
     * @mbggenerated
     */
    public String getFowner() {
        return fowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FOwner
     *
     * @param fowner the value for dbo.XD_CustHInfo.FOwner
     *
     * @mbggenerated
     */
    public void setFowner(String fowner) {
        this.fowner = fowner == null ? null : fowner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FRelationship
     *
     * @return the value of dbo.XD_CustHInfo.FRelationship
     *
     * @mbggenerated
     */
    public String getFrelationship() {
        return frelationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FRelationship
     *
     * @param frelationship the value for dbo.XD_CustHInfo.FRelationship
     *
     * @mbggenerated
     */
    public void setFrelationship(String frelationship) {
        this.frelationship = frelationship == null ? null : frelationship.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FArea
     *
     * @return the value of dbo.XD_CustHInfo.FArea
     *
     * @mbggenerated
     */
    public String getFarea() {
        return farea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FArea
     *
     * @param farea the value for dbo.XD_CustHInfo.FArea
     *
     * @mbggenerated
     */
    public void setFarea(String farea) {
        this.farea = farea == null ? null : farea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFWAdd
     *
     * @return the value of dbo.XD_CustHInfo.FFWAdd
     *
     * @mbggenerated
     */
    public String getFfwadd() {
        return ffwadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFWAdd
     *
     * @param ffwadd the value for dbo.XD_CustHInfo.FFWAdd
     *
     * @mbggenerated
     */
    public void setFfwadd(String ffwadd) {
        this.ffwadd = ffwadd == null ? null : ffwadd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FPostZJ
     *
     * @return the value of dbo.XD_CustHInfo.FPostZJ
     *
     * @mbggenerated
     */
    public String getFpostzj() {
        return fpostzj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FPostZJ
     *
     * @param fpostzj the value for dbo.XD_CustHInfo.FPostZJ
     *
     * @mbggenerated
     */
    public void setFpostzj(String fpostzj) {
        this.fpostzj = fpostzj == null ? null : fpostzj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FSum
     *
     * @return the value of dbo.XD_CustHInfo.FSum
     *
     * @mbggenerated
     */
    public BigDecimal getFsum() {
        return fsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FSum
     *
     * @param fsum the value for dbo.XD_CustHInfo.FSum
     *
     * @mbggenerated
     */
    public void setFsum(BigDecimal fsum) {
        this.fsum = fsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FHType
     *
     * @return the value of dbo.XD_CustHInfo.FHType
     *
     * @mbggenerated
     */
    public Integer getFhtype() {
        return fhtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FHType
     *
     * @param fhtype the value for dbo.XD_CustHInfo.FHType
     *
     * @mbggenerated
     */
    public void setFhtype(Integer fhtype) {
        this.fhtype = fhtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FHCarNO
     *
     * @return the value of dbo.XD_CustHInfo.FHCarNO
     *
     * @mbggenerated
     */
    public String getFhcarno() {
        return fhcarno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FHCarNO
     *
     * @param fhcarno the value for dbo.XD_CustHInfo.FHCarNO
     *
     * @mbggenerated
     */
    public void setFhcarno(String fhcarno) {
        this.fhcarno = fhcarno == null ? null : fhcarno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FHNote
     *
     * @return the value of dbo.XD_CustHInfo.FHNote
     *
     * @mbggenerated
     */
    public String getFhnote() {
        return fhnote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FHNote
     *
     * @param fhnote the value for dbo.XD_CustHInfo.FHNote
     *
     * @mbggenerated
     */
    public void setFhnote(String fhnote) {
        this.fhnote = fhnote == null ? null : fhnote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FArea1
     *
     * @return the value of dbo.XD_CustHInfo.FArea1
     *
     * @mbggenerated
     */
    public String getFarea1() {
        return farea1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FArea1
     *
     * @param farea1 the value for dbo.XD_CustHInfo.FArea1
     *
     * @mbggenerated
     */
    public void setFarea1(String farea1) {
        this.farea1 = farea1 == null ? null : farea1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FAreaGT
     *
     * @return the value of dbo.XD_CustHInfo.FAreaGT
     *
     * @mbggenerated
     */
    public String getFareagt() {
        return fareagt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FAreaGT
     *
     * @param fareagt the value for dbo.XD_CustHInfo.FAreaGT
     *
     * @mbggenerated
     */
    public void setFareagt(String fareagt) {
        this.fareagt = fareagt == null ? null : fareagt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFInsure2
     *
     * @return the value of dbo.XD_CustHInfo.FFInsure2
     *
     * @mbggenerated
     */
    public String getFfinsure2() {
        return ffinsure2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFInsure2
     *
     * @param ffinsure2 the value for dbo.XD_CustHInfo.FFInsure2
     *
     * @mbggenerated
     */
    public void setFfinsure2(String ffinsure2) {
        this.ffinsure2 = ffinsure2 == null ? null : ffinsure2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFInsure1
     *
     * @return the value of dbo.XD_CustHInfo.FFInsure1
     *
     * @mbggenerated
     */
    public String getFfinsure1() {
        return ffinsure1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFInsure1
     *
     * @param ffinsure1 the value for dbo.XD_CustHInfo.FFInsure1
     *
     * @mbggenerated
     */
    public void setFfinsure1(String ffinsure1) {
        this.ffinsure1 = ffinsure1 == null ? null : ffinsure1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FCarQty
     *
     * @return the value of dbo.XD_CustHInfo.FCarQty
     *
     * @mbggenerated
     */
    public BigDecimal getFcarqty() {
        return fcarqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FCarQty
     *
     * @param fcarqty the value for dbo.XD_CustHInfo.FCarQty
     *
     * @mbggenerated
     */
    public void setFcarqty(BigDecimal fcarqty) {
        this.fcarqty = fcarqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FFPCX
     *
     * @return the value of dbo.XD_CustHInfo.FFPCX
     *
     * @mbggenerated
     */
    public String getFfpcx() {
        return ffpcx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FFPCX
     *
     * @param ffpcx the value for dbo.XD_CustHInfo.FFPCX
     *
     * @mbggenerated
     */
    public void setFfpcx(String ffpcx) {
        this.ffpcx = ffpcx == null ? null : ffpcx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FOwner1
     *
     * @return the value of dbo.XD_CustHInfo.FOwner1
     *
     * @mbggenerated
     */
    public String getFowner1() {
        return fowner1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FOwner1
     *
     * @param fowner1 the value for dbo.XD_CustHInfo.FOwner1
     *
     * @mbggenerated
     */
    public void setFowner1(String fowner1) {
        this.fowner1 = fowner1 == null ? null : fowner1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FHRelation1
     *
     * @return the value of dbo.XD_CustHInfo.FHRelation1
     *
     * @mbggenerated
     */
    public String getFhrelation1() {
        return fhrelation1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FHRelation1
     *
     * @param fhrelation1 the value for dbo.XD_CustHInfo.FHRelation1
     *
     * @mbggenerated
     */
    public void setFhrelation1(String fhrelation1) {
        this.fhrelation1 = fhrelation1 == null ? null : fhrelation1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustHInfo.FHouseAdd1
     *
     * @return the value of dbo.XD_CustHInfo.FHouseAdd1
     *
     * @mbggenerated
     */
    public String getFhouseadd1() {
        return fhouseadd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustHInfo.FHouseAdd1
     *
     * @param fhouseadd1 the value for dbo.XD_CustHInfo.FHouseAdd1
     *
     * @mbggenerated
     */
    public void setFhouseadd1(String fhouseadd1) {
        this.fhouseadd1 = fhouseadd1 == null ? null : fhouseadd1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustHInfo
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        XdCusthinfo other = (XdCusthinfo) that;
        return (this.getFid() == null ? other.getFid() == null : this.getFid().equals(other.getFid()))
            && (this.getFfower() == null ? other.getFfower() == null : this.getFfower().equals(other.getFfower()))
            && (this.getFfrelation() == null ? other.getFfrelation() == null : this.getFfrelation().equals(other.getFfrelation()))
            && (this.getFfarea() == null ? other.getFfarea() == null : this.getFfarea().equals(other.getFfarea()))
            && (this.getFftype() == null ? other.getFftype() == null : this.getFftype().equals(other.getFftype()))
            && (this.getFfadd() == null ? other.getFfadd() == null : this.getFfadd().equals(other.getFfadd()))
            && (this.getFfprice() == null ? other.getFfprice() == null : this.getFfprice().equals(other.getFfprice()))
            && (this.getFffirstpay() == null ? other.getFffirstpay() == null : this.getFffirstpay().equals(other.getFffirstpay()))
            && (this.getFfdebitamt() == null ? other.getFfdebitamt() == null : this.getFfdebitamt().equals(other.getFfdebitamt()))
            && (this.getFhpaymonth() == null ? other.getFhpaymonth() == null : this.getFhpaymonth().equals(other.getFhpaymonth()))
            && (this.getFfpledgemonth() == null ? other.getFfpledgemonth() == null : this.getFfpledgemonth().equals(other.getFfpledgemonth()))
            && (this.getFfpledgedate() == null ? other.getFfpledgedate() == null : this.getFfpledgedate().equals(other.getFfpledgedate()))
            && (this.getFhomeget() == null ? other.getFhomeget() == null : this.getFhomeget().equals(other.getFhomeget()))
            && (this.getFhomepget() == null ? other.getFhomepget() == null : this.getFhomepget().equals(other.getFhomepget()))
            && (this.getFsrhdb() == null ? other.getFsrhdb() == null : this.getFsrhdb().equals(other.getFsrhdb()))
            && (this.getFjtjsr() == null ? other.getFjtjsr() == null : this.getFjtjsr().equals(other.getFjtjsr()))
            && (this.getFhomedebit() == null ? other.getFhomedebit() == null : this.getFhomedebit().equals(other.getFhomedebit()))
            && (this.getFjzcdk() == null ? other.getFjzcdk() == null : this.getFjzcdk().equals(other.getFjzcdk()))
            && (this.getFfnjck() == null ? other.getFfnjck() == null : this.getFfnjck().equals(other.getFfnjck()))
            && (this.getFrjzfmj() == null ? other.getFrjzfmj() == null : this.getFrjzfmj().equals(other.getFrjzfmj()))
            && (this.getFjzfck() == null ? other.getFjzfck() == null : this.getFjzfck().equals(other.getFjzfck()))
            && (this.getFjyjzq() == null ? other.getFjyjzq() == null : this.getFjyjzq().equals(other.getFjyjzq()))
            && (this.getFjswzc() == null ? other.getFjswzc() == null : this.getFjswzc().equals(other.getFjswzc()))
            && (this.getFjdwtz() == null ? other.getFjdwtz() == null : this.getFjdwtz().equals(other.getFjdwtz()))
            && (this.getFjzjf() == null ? other.getFjzjf() == null : this.getFjzjf().equals(other.getFjzjf()))
            && (this.getFhomenote() == null ? other.getFhomenote() == null : this.getFhomenote().equals(other.getFhomenote()))
            && (this.getFffc() == null ? other.getFffc() == null : this.getFffc().equals(other.getFffc()))
            && (this.getFfcar() == null ? other.getFfcar() == null : this.getFfcar().equals(other.getFfcar()))
            && (this.getFfgp() == null ? other.getFfgp() == null : this.getFfgp().equals(other.getFfgp()))
            && (this.getFfjj() == null ? other.getFfjj() == null : this.getFfjj().equals(other.getFfjj()))
            && (this.getFfinsure() == null ? other.getFfinsure() == null : this.getFfinsure().equals(other.getFfinsure()))
            && (this.getFfjyzh() == null ? other.getFfjyzh() == null : this.getFfjyzh().equals(other.getFfjyzh()))
            && (this.getFfother() == null ? other.getFfother() == null : this.getFfother().equals(other.getFfother()))
            && (this.getFowntotal() == null ? other.getFowntotal() == null : this.getFowntotal().equals(other.getFowntotal()))
            && (this.getFfhdebit() == null ? other.getFfhdebit() == null : this.getFfhdebit().equals(other.getFfhdebit()))
            && (this.getFfcdebit() == null ? other.getFfcdebit() == null : this.getFfcdebit().equals(other.getFfcdebit()))
            && (this.getFfcarddebit() == null ? other.getFfcarddebit() == null : this.getFfcarddebit().equals(other.getFfcarddebit()))
            && (this.getFfgrdebit() == null ? other.getFfgrdebit() == null : this.getFfgrdebit().equals(other.getFfgrdebit()))
            && (this.getFfotherdebit() == null ? other.getFfotherdebit() == null : this.getFfotherdebit().equals(other.getFfotherdebit()))
            && (this.getFfdebittotal() == null ? other.getFfdebittotal() == null : this.getFfdebittotal().equals(other.getFfdebittotal()))
            && (this.getFtotal() == null ? other.getFtotal() == null : this.getFtotal().equals(other.getFtotal()))
            && (this.getFjkrecord() == null ? other.getFjkrecord() == null : this.getFjkrecord().equals(other.getFjkrecord()))
            && (this.getFdkcs() == null ? other.getFdkcs() == null : this.getFdkcs().equals(other.getFdkcs()))
            && (this.getFowner() == null ? other.getFowner() == null : this.getFowner().equals(other.getFowner()))
            && (this.getFrelationship() == null ? other.getFrelationship() == null : this.getFrelationship().equals(other.getFrelationship()))
            && (this.getFarea() == null ? other.getFarea() == null : this.getFarea().equals(other.getFarea()))
            && (this.getFfwadd() == null ? other.getFfwadd() == null : this.getFfwadd().equals(other.getFfwadd()))
            && (this.getFpostzj() == null ? other.getFpostzj() == null : this.getFpostzj().equals(other.getFpostzj()))
            && (this.getFsum() == null ? other.getFsum() == null : this.getFsum().equals(other.getFsum()))
            && (this.getFhtype() == null ? other.getFhtype() == null : this.getFhtype().equals(other.getFhtype()))
            && (this.getFhcarno() == null ? other.getFhcarno() == null : this.getFhcarno().equals(other.getFhcarno()))
            && (this.getFhnote() == null ? other.getFhnote() == null : this.getFhnote().equals(other.getFhnote()))
            && (this.getFarea1() == null ? other.getFarea1() == null : this.getFarea1().equals(other.getFarea1()))
            && (this.getFareagt() == null ? other.getFareagt() == null : this.getFareagt().equals(other.getFareagt()))
            && (this.getFfinsure2() == null ? other.getFfinsure2() == null : this.getFfinsure2().equals(other.getFfinsure2()))
            && (this.getFfinsure1() == null ? other.getFfinsure1() == null : this.getFfinsure1().equals(other.getFfinsure1()))
            && (this.getFcarqty() == null ? other.getFcarqty() == null : this.getFcarqty().equals(other.getFcarqty()))
            && (this.getFfpcx() == null ? other.getFfpcx() == null : this.getFfpcx().equals(other.getFfpcx()))
            && (this.getFowner1() == null ? other.getFowner1() == null : this.getFowner1().equals(other.getFowner1()))
            && (this.getFhrelation1() == null ? other.getFhrelation1() == null : this.getFhrelation1().equals(other.getFhrelation1()))
            && (this.getFhouseadd1() == null ? other.getFhouseadd1() == null : this.getFhouseadd1().equals(other.getFhouseadd1()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustHInfo
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFid() == null) ? 0 : getFid().hashCode());
        result = prime * result + ((getFfower() == null) ? 0 : getFfower().hashCode());
        result = prime * result + ((getFfrelation() == null) ? 0 : getFfrelation().hashCode());
        result = prime * result + ((getFfarea() == null) ? 0 : getFfarea().hashCode());
        result = prime * result + ((getFftype() == null) ? 0 : getFftype().hashCode());
        result = prime * result + ((getFfadd() == null) ? 0 : getFfadd().hashCode());
        result = prime * result + ((getFfprice() == null) ? 0 : getFfprice().hashCode());
        result = prime * result + ((getFffirstpay() == null) ? 0 : getFffirstpay().hashCode());
        result = prime * result + ((getFfdebitamt() == null) ? 0 : getFfdebitamt().hashCode());
        result = prime * result + ((getFhpaymonth() == null) ? 0 : getFhpaymonth().hashCode());
        result = prime * result + ((getFfpledgemonth() == null) ? 0 : getFfpledgemonth().hashCode());
        result = prime * result + ((getFfpledgedate() == null) ? 0 : getFfpledgedate().hashCode());
        result = prime * result + ((getFhomeget() == null) ? 0 : getFhomeget().hashCode());
        result = prime * result + ((getFhomepget() == null) ? 0 : getFhomepget().hashCode());
        result = prime * result + ((getFsrhdb() == null) ? 0 : getFsrhdb().hashCode());
        result = prime * result + ((getFjtjsr() == null) ? 0 : getFjtjsr().hashCode());
        result = prime * result + ((getFhomedebit() == null) ? 0 : getFhomedebit().hashCode());
        result = prime * result + ((getFjzcdk() == null) ? 0 : getFjzcdk().hashCode());
        result = prime * result + ((getFfnjck() == null) ? 0 : getFfnjck().hashCode());
        result = prime * result + ((getFrjzfmj() == null) ? 0 : getFrjzfmj().hashCode());
        result = prime * result + ((getFjzfck() == null) ? 0 : getFjzfck().hashCode());
        result = prime * result + ((getFjyjzq() == null) ? 0 : getFjyjzq().hashCode());
        result = prime * result + ((getFjswzc() == null) ? 0 : getFjswzc().hashCode());
        result = prime * result + ((getFjdwtz() == null) ? 0 : getFjdwtz().hashCode());
        result = prime * result + ((getFjzjf() == null) ? 0 : getFjzjf().hashCode());
        result = prime * result + ((getFhomenote() == null) ? 0 : getFhomenote().hashCode());
        result = prime * result + ((getFffc() == null) ? 0 : getFffc().hashCode());
        result = prime * result + ((getFfcar() == null) ? 0 : getFfcar().hashCode());
        result = prime * result + ((getFfgp() == null) ? 0 : getFfgp().hashCode());
        result = prime * result + ((getFfjj() == null) ? 0 : getFfjj().hashCode());
        result = prime * result + ((getFfinsure() == null) ? 0 : getFfinsure().hashCode());
        result = prime * result + ((getFfjyzh() == null) ? 0 : getFfjyzh().hashCode());
        result = prime * result + ((getFfother() == null) ? 0 : getFfother().hashCode());
        result = prime * result + ((getFowntotal() == null) ? 0 : getFowntotal().hashCode());
        result = prime * result + ((getFfhdebit() == null) ? 0 : getFfhdebit().hashCode());
        result = prime * result + ((getFfcdebit() == null) ? 0 : getFfcdebit().hashCode());
        result = prime * result + ((getFfcarddebit() == null) ? 0 : getFfcarddebit().hashCode());
        result = prime * result + ((getFfgrdebit() == null) ? 0 : getFfgrdebit().hashCode());
        result = prime * result + ((getFfotherdebit() == null) ? 0 : getFfotherdebit().hashCode());
        result = prime * result + ((getFfdebittotal() == null) ? 0 : getFfdebittotal().hashCode());
        result = prime * result + ((getFtotal() == null) ? 0 : getFtotal().hashCode());
        result = prime * result + ((getFjkrecord() == null) ? 0 : getFjkrecord().hashCode());
        result = prime * result + ((getFdkcs() == null) ? 0 : getFdkcs().hashCode());
        result = prime * result + ((getFowner() == null) ? 0 : getFowner().hashCode());
        result = prime * result + ((getFrelationship() == null) ? 0 : getFrelationship().hashCode());
        result = prime * result + ((getFarea() == null) ? 0 : getFarea().hashCode());
        result = prime * result + ((getFfwadd() == null) ? 0 : getFfwadd().hashCode());
        result = prime * result + ((getFpostzj() == null) ? 0 : getFpostzj().hashCode());
        result = prime * result + ((getFsum() == null) ? 0 : getFsum().hashCode());
        result = prime * result + ((getFhtype() == null) ? 0 : getFhtype().hashCode());
        result = prime * result + ((getFhcarno() == null) ? 0 : getFhcarno().hashCode());
        result = prime * result + ((getFhnote() == null) ? 0 : getFhnote().hashCode());
        result = prime * result + ((getFarea1() == null) ? 0 : getFarea1().hashCode());
        result = prime * result + ((getFareagt() == null) ? 0 : getFareagt().hashCode());
        result = prime * result + ((getFfinsure2() == null) ? 0 : getFfinsure2().hashCode());
        result = prime * result + ((getFfinsure1() == null) ? 0 : getFfinsure1().hashCode());
        result = prime * result + ((getFcarqty() == null) ? 0 : getFcarqty().hashCode());
        result = prime * result + ((getFfpcx() == null) ? 0 : getFfpcx().hashCode());
        result = prime * result + ((getFowner1() == null) ? 0 : getFowner1().hashCode());
        result = prime * result + ((getFhrelation1() == null) ? 0 : getFhrelation1().hashCode());
        result = prime * result + ((getFhouseadd1() == null) ? 0 : getFhouseadd1().hashCode());
        return result;
    }
}