package com.hongte.weixin.mybatis.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class XdCustcarinfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FID
     *
     * @mbggenerated
     */
    private Integer fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FVType
     *
     * @mbggenerated
     */
    private Integer fvtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FVPayType
     *
     * @mbggenerated
     */
    private Integer fvpaytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FVPrice
     *
     * @mbggenerated
     */
    private BigDecimal fvprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FVFirstScale
     *
     * @mbggenerated
     */
    private BigDecimal fvfirstscale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FVFirstPay
     *
     * @mbggenerated
     */
    private BigDecimal fvfirstpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FVDebitAmt
     *
     * @mbggenerated
     */
    private BigDecimal fvdebitamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FVPeriod
     *
     * @mbggenerated
     */
    private Integer fvperiod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FVPayMonth
     *
     * @mbggenerated
     */
    private BigDecimal fvpaymonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FVCardType
     *
     * @mbggenerated
     */
    private Integer fvcardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FVSelf
     *
     * @mbggenerated
     */
    private String fvself;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FVBillNo
     *
     * @mbggenerated
     */
    private String fvbillno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FVCJ
     *
     * @mbggenerated
     */
    private String fvcj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FVHost
     *
     * @mbggenerated
     */
    private String fvhost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FVBankID
     *
     * @mbggenerated
     */
    private Integer fvbankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FVNote
     *
     * @mbggenerated
     */
    private String fvnote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FVInsureID
     *
     * @mbggenerated
     */
    private Integer fvinsureid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FVStyle
     *
     * @mbggenerated
     */
    private String fvstyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FCarDetailModel
     *
     * @mbggenerated
     */
    private String fcardetailmodel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.T_CarDetailModel
     *
     * @mbggenerated
     */
    private Integer tCardetailmodel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FSArea
     *
     * @mbggenerated
     */
    private Integer fsarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FFeeType
     *
     * @mbggenerated
     */
    private String ffeetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FCountry
     *
     * @mbggenerated
     */
    private String fcountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FMonthRate
     *
     * @mbggenerated
     */
    private BigDecimal fmonthrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FColor
     *
     * @mbggenerated
     */
    private String fcolor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FDBType
     *
     * @mbggenerated
     */
    private Integer fdbtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FDBStyle
     *
     * @mbggenerated
     */
    private Integer fdbstyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FLYFee
     *
     * @mbggenerated
     */
    private BigDecimal flyfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FFirstMonthPay
     *
     * @mbggenerated
     */
    private BigDecimal ffirstmonthpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FCarDescript
     *
     * @mbggenerated
     */
    private String fcardescript;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FMCardNo
     *
     * @mbggenerated
     */
    private String fmcardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FBRate
     *
     * @mbggenerated
     */
    private BigDecimal fbrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FFWFee
     *
     * @mbggenerated
     */
    private BigDecimal ffwfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FStandard
     *
     * @mbggenerated
     */
    private BigDecimal fstandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FVInsureID1
     *
     * @mbggenerated
     */
    private Integer fvinsureid1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FCJVPrice
     *
     * @mbggenerated
     */
    private BigDecimal fcjvprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FCJVFirstPay
     *
     * @mbggenerated
     */
    private BigDecimal fcjvfirstpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FCJVFirstScale
     *
     * @mbggenerated
     */
    private BigDecimal fcjvfirstscale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FIsLock
     *
     * @mbggenerated
     */
    private String fislock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FMCardInDate
     *
     * @mbggenerated
     */
    private Date fmcardindate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.GPSH
     *
     * @mbggenerated
     */
    private String gpsh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.CLPZ
     *
     * @mbggenerated
     */
    private String clpz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.CLPL
     *
     * @mbggenerated
     */
    private String clpl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FTCYW
     *
     * @mbggenerated
     */
    private String ftcyw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FZSD
     *
     * @mbggenerated
     */
    private String fzsd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FSDD
     *
     * @mbggenerated
     */
    private Boolean fsdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_CustCarInfo.FCZD
     *
     * @mbggenerated
     */
    private Boolean fczd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.XD_CustCarInfo
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FID
     *
     * @return the value of dbo.XD_CustCarInfo.FID
     *
     * @mbggenerated
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FID
     *
     * @param fid the value for dbo.XD_CustCarInfo.FID
     *
     * @mbggenerated
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FVType
     *
     * @return the value of dbo.XD_CustCarInfo.FVType
     *
     * @mbggenerated
     */
    public Integer getFvtype() {
        return fvtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FVType
     *
     * @param fvtype the value for dbo.XD_CustCarInfo.FVType
     *
     * @mbggenerated
     */
    public void setFvtype(Integer fvtype) {
        this.fvtype = fvtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FVPayType
     *
     * @return the value of dbo.XD_CustCarInfo.FVPayType
     *
     * @mbggenerated
     */
    public Integer getFvpaytype() {
        return fvpaytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FVPayType
     *
     * @param fvpaytype the value for dbo.XD_CustCarInfo.FVPayType
     *
     * @mbggenerated
     */
    public void setFvpaytype(Integer fvpaytype) {
        this.fvpaytype = fvpaytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FVPrice
     *
     * @return the value of dbo.XD_CustCarInfo.FVPrice
     *
     * @mbggenerated
     */
    public BigDecimal getFvprice() {
        return fvprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FVPrice
     *
     * @param fvprice the value for dbo.XD_CustCarInfo.FVPrice
     *
     * @mbggenerated
     */
    public void setFvprice(BigDecimal fvprice) {
        this.fvprice = fvprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FVFirstScale
     *
     * @return the value of dbo.XD_CustCarInfo.FVFirstScale
     *
     * @mbggenerated
     */
    public BigDecimal getFvfirstscale() {
        return fvfirstscale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FVFirstScale
     *
     * @param fvfirstscale the value for dbo.XD_CustCarInfo.FVFirstScale
     *
     * @mbggenerated
     */
    public void setFvfirstscale(BigDecimal fvfirstscale) {
        this.fvfirstscale = fvfirstscale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FVFirstPay
     *
     * @return the value of dbo.XD_CustCarInfo.FVFirstPay
     *
     * @mbggenerated
     */
    public BigDecimal getFvfirstpay() {
        return fvfirstpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FVFirstPay
     *
     * @param fvfirstpay the value for dbo.XD_CustCarInfo.FVFirstPay
     *
     * @mbggenerated
     */
    public void setFvfirstpay(BigDecimal fvfirstpay) {
        this.fvfirstpay = fvfirstpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FVDebitAmt
     *
     * @return the value of dbo.XD_CustCarInfo.FVDebitAmt
     *
     * @mbggenerated
     */
    public BigDecimal getFvdebitamt() {
        return fvdebitamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FVDebitAmt
     *
     * @param fvdebitamt the value for dbo.XD_CustCarInfo.FVDebitAmt
     *
     * @mbggenerated
     */
    public void setFvdebitamt(BigDecimal fvdebitamt) {
        this.fvdebitamt = fvdebitamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FVPeriod
     *
     * @return the value of dbo.XD_CustCarInfo.FVPeriod
     *
     * @mbggenerated
     */
    public Integer getFvperiod() {
        return fvperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FVPeriod
     *
     * @param fvperiod the value for dbo.XD_CustCarInfo.FVPeriod
     *
     * @mbggenerated
     */
    public void setFvperiod(Integer fvperiod) {
        this.fvperiod = fvperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FVPayMonth
     *
     * @return the value of dbo.XD_CustCarInfo.FVPayMonth
     *
     * @mbggenerated
     */
    public BigDecimal getFvpaymonth() {
        return fvpaymonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FVPayMonth
     *
     * @param fvpaymonth the value for dbo.XD_CustCarInfo.FVPayMonth
     *
     * @mbggenerated
     */
    public void setFvpaymonth(BigDecimal fvpaymonth) {
        this.fvpaymonth = fvpaymonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FVCardType
     *
     * @return the value of dbo.XD_CustCarInfo.FVCardType
     *
     * @mbggenerated
     */
    public Integer getFvcardtype() {
        return fvcardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FVCardType
     *
     * @param fvcardtype the value for dbo.XD_CustCarInfo.FVCardType
     *
     * @mbggenerated
     */
    public void setFvcardtype(Integer fvcardtype) {
        this.fvcardtype = fvcardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FVSelf
     *
     * @return the value of dbo.XD_CustCarInfo.FVSelf
     *
     * @mbggenerated
     */
    public String getFvself() {
        return fvself;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FVSelf
     *
     * @param fvself the value for dbo.XD_CustCarInfo.FVSelf
     *
     * @mbggenerated
     */
    public void setFvself(String fvself) {
        this.fvself = fvself == null ? null : fvself.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FVBillNo
     *
     * @return the value of dbo.XD_CustCarInfo.FVBillNo
     *
     * @mbggenerated
     */
    public String getFvbillno() {
        return fvbillno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FVBillNo
     *
     * @param fvbillno the value for dbo.XD_CustCarInfo.FVBillNo
     *
     * @mbggenerated
     */
    public void setFvbillno(String fvbillno) {
        this.fvbillno = fvbillno == null ? null : fvbillno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FVCJ
     *
     * @return the value of dbo.XD_CustCarInfo.FVCJ
     *
     * @mbggenerated
     */
    public String getFvcj() {
        return fvcj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FVCJ
     *
     * @param fvcj the value for dbo.XD_CustCarInfo.FVCJ
     *
     * @mbggenerated
     */
    public void setFvcj(String fvcj) {
        this.fvcj = fvcj == null ? null : fvcj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FVHost
     *
     * @return the value of dbo.XD_CustCarInfo.FVHost
     *
     * @mbggenerated
     */
    public String getFvhost() {
        return fvhost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FVHost
     *
     * @param fvhost the value for dbo.XD_CustCarInfo.FVHost
     *
     * @mbggenerated
     */
    public void setFvhost(String fvhost) {
        this.fvhost = fvhost == null ? null : fvhost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FVBankID
     *
     * @return the value of dbo.XD_CustCarInfo.FVBankID
     *
     * @mbggenerated
     */
    public Integer getFvbankid() {
        return fvbankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FVBankID
     *
     * @param fvbankid the value for dbo.XD_CustCarInfo.FVBankID
     *
     * @mbggenerated
     */
    public void setFvbankid(Integer fvbankid) {
        this.fvbankid = fvbankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FVNote
     *
     * @return the value of dbo.XD_CustCarInfo.FVNote
     *
     * @mbggenerated
     */
    public String getFvnote() {
        return fvnote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FVNote
     *
     * @param fvnote the value for dbo.XD_CustCarInfo.FVNote
     *
     * @mbggenerated
     */
    public void setFvnote(String fvnote) {
        this.fvnote = fvnote == null ? null : fvnote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FVInsureID
     *
     * @return the value of dbo.XD_CustCarInfo.FVInsureID
     *
     * @mbggenerated
     */
    public Integer getFvinsureid() {
        return fvinsureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FVInsureID
     *
     * @param fvinsureid the value for dbo.XD_CustCarInfo.FVInsureID
     *
     * @mbggenerated
     */
    public void setFvinsureid(Integer fvinsureid) {
        this.fvinsureid = fvinsureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FVStyle
     *
     * @return the value of dbo.XD_CustCarInfo.FVStyle
     *
     * @mbggenerated
     */
    public String getFvstyle() {
        return fvstyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FVStyle
     *
     * @param fvstyle the value for dbo.XD_CustCarInfo.FVStyle
     *
     * @mbggenerated
     */
    public void setFvstyle(String fvstyle) {
        this.fvstyle = fvstyle == null ? null : fvstyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FCarDetailModel
     *
     * @return the value of dbo.XD_CustCarInfo.FCarDetailModel
     *
     * @mbggenerated
     */
    public String getFcardetailmodel() {
        return fcardetailmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FCarDetailModel
     *
     * @param fcardetailmodel the value for dbo.XD_CustCarInfo.FCarDetailModel
     *
     * @mbggenerated
     */
    public void setFcardetailmodel(String fcardetailmodel) {
        this.fcardetailmodel = fcardetailmodel == null ? null : fcardetailmodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.T_CarDetailModel
     *
     * @return the value of dbo.XD_CustCarInfo.T_CarDetailModel
     *
     * @mbggenerated
     */
    public Integer gettCardetailmodel() {
        return tCardetailmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.T_CarDetailModel
     *
     * @param tCardetailmodel the value for dbo.XD_CustCarInfo.T_CarDetailModel
     *
     * @mbggenerated
     */
    public void settCardetailmodel(Integer tCardetailmodel) {
        this.tCardetailmodel = tCardetailmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FSArea
     *
     * @return the value of dbo.XD_CustCarInfo.FSArea
     *
     * @mbggenerated
     */
    public Integer getFsarea() {
        return fsarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FSArea
     *
     * @param fsarea the value for dbo.XD_CustCarInfo.FSArea
     *
     * @mbggenerated
     */
    public void setFsarea(Integer fsarea) {
        this.fsarea = fsarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FFeeType
     *
     * @return the value of dbo.XD_CustCarInfo.FFeeType
     *
     * @mbggenerated
     */
    public String getFfeetype() {
        return ffeetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FFeeType
     *
     * @param ffeetype the value for dbo.XD_CustCarInfo.FFeeType
     *
     * @mbggenerated
     */
    public void setFfeetype(String ffeetype) {
        this.ffeetype = ffeetype == null ? null : ffeetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FCountry
     *
     * @return the value of dbo.XD_CustCarInfo.FCountry
     *
     * @mbggenerated
     */
    public String getFcountry() {
        return fcountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FCountry
     *
     * @param fcountry the value for dbo.XD_CustCarInfo.FCountry
     *
     * @mbggenerated
     */
    public void setFcountry(String fcountry) {
        this.fcountry = fcountry == null ? null : fcountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FMonthRate
     *
     * @return the value of dbo.XD_CustCarInfo.FMonthRate
     *
     * @mbggenerated
     */
    public BigDecimal getFmonthrate() {
        return fmonthrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FMonthRate
     *
     * @param fmonthrate the value for dbo.XD_CustCarInfo.FMonthRate
     *
     * @mbggenerated
     */
    public void setFmonthrate(BigDecimal fmonthrate) {
        this.fmonthrate = fmonthrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FColor
     *
     * @return the value of dbo.XD_CustCarInfo.FColor
     *
     * @mbggenerated
     */
    public String getFcolor() {
        return fcolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FColor
     *
     * @param fcolor the value for dbo.XD_CustCarInfo.FColor
     *
     * @mbggenerated
     */
    public void setFcolor(String fcolor) {
        this.fcolor = fcolor == null ? null : fcolor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FDBType
     *
     * @return the value of dbo.XD_CustCarInfo.FDBType
     *
     * @mbggenerated
     */
    public Integer getFdbtype() {
        return fdbtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FDBType
     *
     * @param fdbtype the value for dbo.XD_CustCarInfo.FDBType
     *
     * @mbggenerated
     */
    public void setFdbtype(Integer fdbtype) {
        this.fdbtype = fdbtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FDBStyle
     *
     * @return the value of dbo.XD_CustCarInfo.FDBStyle
     *
     * @mbggenerated
     */
    public Integer getFdbstyle() {
        return fdbstyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FDBStyle
     *
     * @param fdbstyle the value for dbo.XD_CustCarInfo.FDBStyle
     *
     * @mbggenerated
     */
    public void setFdbstyle(Integer fdbstyle) {
        this.fdbstyle = fdbstyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FLYFee
     *
     * @return the value of dbo.XD_CustCarInfo.FLYFee
     *
     * @mbggenerated
     */
    public BigDecimal getFlyfee() {
        return flyfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FLYFee
     *
     * @param flyfee the value for dbo.XD_CustCarInfo.FLYFee
     *
     * @mbggenerated
     */
    public void setFlyfee(BigDecimal flyfee) {
        this.flyfee = flyfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FFirstMonthPay
     *
     * @return the value of dbo.XD_CustCarInfo.FFirstMonthPay
     *
     * @mbggenerated
     */
    public BigDecimal getFfirstmonthpay() {
        return ffirstmonthpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FFirstMonthPay
     *
     * @param ffirstmonthpay the value for dbo.XD_CustCarInfo.FFirstMonthPay
     *
     * @mbggenerated
     */
    public void setFfirstmonthpay(BigDecimal ffirstmonthpay) {
        this.ffirstmonthpay = ffirstmonthpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FCarDescript
     *
     * @return the value of dbo.XD_CustCarInfo.FCarDescript
     *
     * @mbggenerated
     */
    public String getFcardescript() {
        return fcardescript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FCarDescript
     *
     * @param fcardescript the value for dbo.XD_CustCarInfo.FCarDescript
     *
     * @mbggenerated
     */
    public void setFcardescript(String fcardescript) {
        this.fcardescript = fcardescript == null ? null : fcardescript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FMCardNo
     *
     * @return the value of dbo.XD_CustCarInfo.FMCardNo
     *
     * @mbggenerated
     */
    public String getFmcardno() {
        return fmcardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FMCardNo
     *
     * @param fmcardno the value for dbo.XD_CustCarInfo.FMCardNo
     *
     * @mbggenerated
     */
    public void setFmcardno(String fmcardno) {
        this.fmcardno = fmcardno == null ? null : fmcardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FBRate
     *
     * @return the value of dbo.XD_CustCarInfo.FBRate
     *
     * @mbggenerated
     */
    public BigDecimal getFbrate() {
        return fbrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FBRate
     *
     * @param fbrate the value for dbo.XD_CustCarInfo.FBRate
     *
     * @mbggenerated
     */
    public void setFbrate(BigDecimal fbrate) {
        this.fbrate = fbrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FFWFee
     *
     * @return the value of dbo.XD_CustCarInfo.FFWFee
     *
     * @mbggenerated
     */
    public BigDecimal getFfwfee() {
        return ffwfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FFWFee
     *
     * @param ffwfee the value for dbo.XD_CustCarInfo.FFWFee
     *
     * @mbggenerated
     */
    public void setFfwfee(BigDecimal ffwfee) {
        this.ffwfee = ffwfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FStandard
     *
     * @return the value of dbo.XD_CustCarInfo.FStandard
     *
     * @mbggenerated
     */
    public BigDecimal getFstandard() {
        return fstandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FStandard
     *
     * @param fstandard the value for dbo.XD_CustCarInfo.FStandard
     *
     * @mbggenerated
     */
    public void setFstandard(BigDecimal fstandard) {
        this.fstandard = fstandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FVInsureID1
     *
     * @return the value of dbo.XD_CustCarInfo.FVInsureID1
     *
     * @mbggenerated
     */
    public Integer getFvinsureid1() {
        return fvinsureid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FVInsureID1
     *
     * @param fvinsureid1 the value for dbo.XD_CustCarInfo.FVInsureID1
     *
     * @mbggenerated
     */
    public void setFvinsureid1(Integer fvinsureid1) {
        this.fvinsureid1 = fvinsureid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FCJVPrice
     *
     * @return the value of dbo.XD_CustCarInfo.FCJVPrice
     *
     * @mbggenerated
     */
    public BigDecimal getFcjvprice() {
        return fcjvprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FCJVPrice
     *
     * @param fcjvprice the value for dbo.XD_CustCarInfo.FCJVPrice
     *
     * @mbggenerated
     */
    public void setFcjvprice(BigDecimal fcjvprice) {
        this.fcjvprice = fcjvprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FCJVFirstPay
     *
     * @return the value of dbo.XD_CustCarInfo.FCJVFirstPay
     *
     * @mbggenerated
     */
    public BigDecimal getFcjvfirstpay() {
        return fcjvfirstpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FCJVFirstPay
     *
     * @param fcjvfirstpay the value for dbo.XD_CustCarInfo.FCJVFirstPay
     *
     * @mbggenerated
     */
    public void setFcjvfirstpay(BigDecimal fcjvfirstpay) {
        this.fcjvfirstpay = fcjvfirstpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FCJVFirstScale
     *
     * @return the value of dbo.XD_CustCarInfo.FCJVFirstScale
     *
     * @mbggenerated
     */
    public BigDecimal getFcjvfirstscale() {
        return fcjvfirstscale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FCJVFirstScale
     *
     * @param fcjvfirstscale the value for dbo.XD_CustCarInfo.FCJVFirstScale
     *
     * @mbggenerated
     */
    public void setFcjvfirstscale(BigDecimal fcjvfirstscale) {
        this.fcjvfirstscale = fcjvfirstscale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FIsLock
     *
     * @return the value of dbo.XD_CustCarInfo.FIsLock
     *
     * @mbggenerated
     */
    public String getFislock() {
        return fislock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FIsLock
     *
     * @param fislock the value for dbo.XD_CustCarInfo.FIsLock
     *
     * @mbggenerated
     */
    public void setFislock(String fislock) {
        this.fislock = fislock == null ? null : fislock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FMCardInDate
     *
     * @return the value of dbo.XD_CustCarInfo.FMCardInDate
     *
     * @mbggenerated
     */
    public Date getFmcardindate() {
        return fmcardindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FMCardInDate
     *
     * @param fmcardindate the value for dbo.XD_CustCarInfo.FMCardInDate
     *
     * @mbggenerated
     */
    public void setFmcardindate(Date fmcardindate) {
        this.fmcardindate = fmcardindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.GPSH
     *
     * @return the value of dbo.XD_CustCarInfo.GPSH
     *
     * @mbggenerated
     */
    public String getGpsh() {
        return gpsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.GPSH
     *
     * @param gpsh the value for dbo.XD_CustCarInfo.GPSH
     *
     * @mbggenerated
     */
    public void setGpsh(String gpsh) {
        this.gpsh = gpsh == null ? null : gpsh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.CLPZ
     *
     * @return the value of dbo.XD_CustCarInfo.CLPZ
     *
     * @mbggenerated
     */
    public String getClpz() {
        return clpz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.CLPZ
     *
     * @param clpz the value for dbo.XD_CustCarInfo.CLPZ
     *
     * @mbggenerated
     */
    public void setClpz(String clpz) {
        this.clpz = clpz == null ? null : clpz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.CLPL
     *
     * @return the value of dbo.XD_CustCarInfo.CLPL
     *
     * @mbggenerated
     */
    public String getClpl() {
        return clpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.CLPL
     *
     * @param clpl the value for dbo.XD_CustCarInfo.CLPL
     *
     * @mbggenerated
     */
    public void setClpl(String clpl) {
        this.clpl = clpl == null ? null : clpl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FTCYW
     *
     * @return the value of dbo.XD_CustCarInfo.FTCYW
     *
     * @mbggenerated
     */
    public String getFtcyw() {
        return ftcyw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FTCYW
     *
     * @param ftcyw the value for dbo.XD_CustCarInfo.FTCYW
     *
     * @mbggenerated
     */
    public void setFtcyw(String ftcyw) {
        this.ftcyw = ftcyw == null ? null : ftcyw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FZSD
     *
     * @return the value of dbo.XD_CustCarInfo.FZSD
     *
     * @mbggenerated
     */
    public String getFzsd() {
        return fzsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FZSD
     *
     * @param fzsd the value for dbo.XD_CustCarInfo.FZSD
     *
     * @mbggenerated
     */
    public void setFzsd(String fzsd) {
        this.fzsd = fzsd == null ? null : fzsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FSDD
     *
     * @return the value of dbo.XD_CustCarInfo.FSDD
     *
     * @mbggenerated
     */
    public Boolean getFsdd() {
        return fsdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FSDD
     *
     * @param fsdd the value for dbo.XD_CustCarInfo.FSDD
     *
     * @mbggenerated
     */
    public void setFsdd(Boolean fsdd) {
        this.fsdd = fsdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_CustCarInfo.FCZD
     *
     * @return the value of dbo.XD_CustCarInfo.FCZD
     *
     * @mbggenerated
     */
    public Boolean getFczd() {
        return fczd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_CustCarInfo.FCZD
     *
     * @param fczd the value for dbo.XD_CustCarInfo.FCZD
     *
     * @mbggenerated
     */
    public void setFczd(Boolean fczd) {
        this.fczd = fczd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustCarInfo
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        XdCustcarinfo other = (XdCustcarinfo) that;
        return (this.getFid() == null ? other.getFid() == null : this.getFid().equals(other.getFid()))
            && (this.getFvtype() == null ? other.getFvtype() == null : this.getFvtype().equals(other.getFvtype()))
            && (this.getFvpaytype() == null ? other.getFvpaytype() == null : this.getFvpaytype().equals(other.getFvpaytype()))
            && (this.getFvprice() == null ? other.getFvprice() == null : this.getFvprice().equals(other.getFvprice()))
            && (this.getFvfirstscale() == null ? other.getFvfirstscale() == null : this.getFvfirstscale().equals(other.getFvfirstscale()))
            && (this.getFvfirstpay() == null ? other.getFvfirstpay() == null : this.getFvfirstpay().equals(other.getFvfirstpay()))
            && (this.getFvdebitamt() == null ? other.getFvdebitamt() == null : this.getFvdebitamt().equals(other.getFvdebitamt()))
            && (this.getFvperiod() == null ? other.getFvperiod() == null : this.getFvperiod().equals(other.getFvperiod()))
            && (this.getFvpaymonth() == null ? other.getFvpaymonth() == null : this.getFvpaymonth().equals(other.getFvpaymonth()))
            && (this.getFvcardtype() == null ? other.getFvcardtype() == null : this.getFvcardtype().equals(other.getFvcardtype()))
            && (this.getFvself() == null ? other.getFvself() == null : this.getFvself().equals(other.getFvself()))
            && (this.getFvbillno() == null ? other.getFvbillno() == null : this.getFvbillno().equals(other.getFvbillno()))
            && (this.getFvcj() == null ? other.getFvcj() == null : this.getFvcj().equals(other.getFvcj()))
            && (this.getFvhost() == null ? other.getFvhost() == null : this.getFvhost().equals(other.getFvhost()))
            && (this.getFvbankid() == null ? other.getFvbankid() == null : this.getFvbankid().equals(other.getFvbankid()))
            && (this.getFvnote() == null ? other.getFvnote() == null : this.getFvnote().equals(other.getFvnote()))
            && (this.getFvinsureid() == null ? other.getFvinsureid() == null : this.getFvinsureid().equals(other.getFvinsureid()))
            && (this.getFvstyle() == null ? other.getFvstyle() == null : this.getFvstyle().equals(other.getFvstyle()))
            && (this.getFcardetailmodel() == null ? other.getFcardetailmodel() == null : this.getFcardetailmodel().equals(other.getFcardetailmodel()))
            && (this.gettCardetailmodel() == null ? other.gettCardetailmodel() == null : this.gettCardetailmodel().equals(other.gettCardetailmodel()))
            && (this.getFsarea() == null ? other.getFsarea() == null : this.getFsarea().equals(other.getFsarea()))
            && (this.getFfeetype() == null ? other.getFfeetype() == null : this.getFfeetype().equals(other.getFfeetype()))
            && (this.getFcountry() == null ? other.getFcountry() == null : this.getFcountry().equals(other.getFcountry()))
            && (this.getFmonthrate() == null ? other.getFmonthrate() == null : this.getFmonthrate().equals(other.getFmonthrate()))
            && (this.getFcolor() == null ? other.getFcolor() == null : this.getFcolor().equals(other.getFcolor()))
            && (this.getFdbtype() == null ? other.getFdbtype() == null : this.getFdbtype().equals(other.getFdbtype()))
            && (this.getFdbstyle() == null ? other.getFdbstyle() == null : this.getFdbstyle().equals(other.getFdbstyle()))
            && (this.getFlyfee() == null ? other.getFlyfee() == null : this.getFlyfee().equals(other.getFlyfee()))
            && (this.getFfirstmonthpay() == null ? other.getFfirstmonthpay() == null : this.getFfirstmonthpay().equals(other.getFfirstmonthpay()))
            && (this.getFcardescript() == null ? other.getFcardescript() == null : this.getFcardescript().equals(other.getFcardescript()))
            && (this.getFmcardno() == null ? other.getFmcardno() == null : this.getFmcardno().equals(other.getFmcardno()))
            && (this.getFbrate() == null ? other.getFbrate() == null : this.getFbrate().equals(other.getFbrate()))
            && (this.getFfwfee() == null ? other.getFfwfee() == null : this.getFfwfee().equals(other.getFfwfee()))
            && (this.getFstandard() == null ? other.getFstandard() == null : this.getFstandard().equals(other.getFstandard()))
            && (this.getFvinsureid1() == null ? other.getFvinsureid1() == null : this.getFvinsureid1().equals(other.getFvinsureid1()))
            && (this.getFcjvprice() == null ? other.getFcjvprice() == null : this.getFcjvprice().equals(other.getFcjvprice()))
            && (this.getFcjvfirstpay() == null ? other.getFcjvfirstpay() == null : this.getFcjvfirstpay().equals(other.getFcjvfirstpay()))
            && (this.getFcjvfirstscale() == null ? other.getFcjvfirstscale() == null : this.getFcjvfirstscale().equals(other.getFcjvfirstscale()))
            && (this.getFislock() == null ? other.getFislock() == null : this.getFislock().equals(other.getFislock()))
            && (this.getFmcardindate() == null ? other.getFmcardindate() == null : this.getFmcardindate().equals(other.getFmcardindate()))
            && (this.getGpsh() == null ? other.getGpsh() == null : this.getGpsh().equals(other.getGpsh()))
            && (this.getClpz() == null ? other.getClpz() == null : this.getClpz().equals(other.getClpz()))
            && (this.getClpl() == null ? other.getClpl() == null : this.getClpl().equals(other.getClpl()))
            && (this.getFtcyw() == null ? other.getFtcyw() == null : this.getFtcyw().equals(other.getFtcyw()))
            && (this.getFzsd() == null ? other.getFzsd() == null : this.getFzsd().equals(other.getFzsd()))
            && (this.getFsdd() == null ? other.getFsdd() == null : this.getFsdd().equals(other.getFsdd()))
            && (this.getFczd() == null ? other.getFczd() == null : this.getFczd().equals(other.getFczd()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_CustCarInfo
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFid() == null) ? 0 : getFid().hashCode());
        result = prime * result + ((getFvtype() == null) ? 0 : getFvtype().hashCode());
        result = prime * result + ((getFvpaytype() == null) ? 0 : getFvpaytype().hashCode());
        result = prime * result + ((getFvprice() == null) ? 0 : getFvprice().hashCode());
        result = prime * result + ((getFvfirstscale() == null) ? 0 : getFvfirstscale().hashCode());
        result = prime * result + ((getFvfirstpay() == null) ? 0 : getFvfirstpay().hashCode());
        result = prime * result + ((getFvdebitamt() == null) ? 0 : getFvdebitamt().hashCode());
        result = prime * result + ((getFvperiod() == null) ? 0 : getFvperiod().hashCode());
        result = prime * result + ((getFvpaymonth() == null) ? 0 : getFvpaymonth().hashCode());
        result = prime * result + ((getFvcardtype() == null) ? 0 : getFvcardtype().hashCode());
        result = prime * result + ((getFvself() == null) ? 0 : getFvself().hashCode());
        result = prime * result + ((getFvbillno() == null) ? 0 : getFvbillno().hashCode());
        result = prime * result + ((getFvcj() == null) ? 0 : getFvcj().hashCode());
        result = prime * result + ((getFvhost() == null) ? 0 : getFvhost().hashCode());
        result = prime * result + ((getFvbankid() == null) ? 0 : getFvbankid().hashCode());
        result = prime * result + ((getFvnote() == null) ? 0 : getFvnote().hashCode());
        result = prime * result + ((getFvinsureid() == null) ? 0 : getFvinsureid().hashCode());
        result = prime * result + ((getFvstyle() == null) ? 0 : getFvstyle().hashCode());
        result = prime * result + ((getFcardetailmodel() == null) ? 0 : getFcardetailmodel().hashCode());
        result = prime * result + ((gettCardetailmodel() == null) ? 0 : gettCardetailmodel().hashCode());
        result = prime * result + ((getFsarea() == null) ? 0 : getFsarea().hashCode());
        result = prime * result + ((getFfeetype() == null) ? 0 : getFfeetype().hashCode());
        result = prime * result + ((getFcountry() == null) ? 0 : getFcountry().hashCode());
        result = prime * result + ((getFmonthrate() == null) ? 0 : getFmonthrate().hashCode());
        result = prime * result + ((getFcolor() == null) ? 0 : getFcolor().hashCode());
        result = prime * result + ((getFdbtype() == null) ? 0 : getFdbtype().hashCode());
        result = prime * result + ((getFdbstyle() == null) ? 0 : getFdbstyle().hashCode());
        result = prime * result + ((getFlyfee() == null) ? 0 : getFlyfee().hashCode());
        result = prime * result + ((getFfirstmonthpay() == null) ? 0 : getFfirstmonthpay().hashCode());
        result = prime * result + ((getFcardescript() == null) ? 0 : getFcardescript().hashCode());
        result = prime * result + ((getFmcardno() == null) ? 0 : getFmcardno().hashCode());
        result = prime * result + ((getFbrate() == null) ? 0 : getFbrate().hashCode());
        result = prime * result + ((getFfwfee() == null) ? 0 : getFfwfee().hashCode());
        result = prime * result + ((getFstandard() == null) ? 0 : getFstandard().hashCode());
        result = prime * result + ((getFvinsureid1() == null) ? 0 : getFvinsureid1().hashCode());
        result = prime * result + ((getFcjvprice() == null) ? 0 : getFcjvprice().hashCode());
        result = prime * result + ((getFcjvfirstpay() == null) ? 0 : getFcjvfirstpay().hashCode());
        result = prime * result + ((getFcjvfirstscale() == null) ? 0 : getFcjvfirstscale().hashCode());
        result = prime * result + ((getFislock() == null) ? 0 : getFislock().hashCode());
        result = prime * result + ((getFmcardindate() == null) ? 0 : getFmcardindate().hashCode());
        result = prime * result + ((getGpsh() == null) ? 0 : getGpsh().hashCode());
        result = prime * result + ((getClpz() == null) ? 0 : getClpz().hashCode());
        result = prime * result + ((getClpl() == null) ? 0 : getClpl().hashCode());
        result = prime * result + ((getFtcyw() == null) ? 0 : getFtcyw().hashCode());
        result = prime * result + ((getFzsd() == null) ? 0 : getFzsd().hashCode());
        result = prime * result + ((getFsdd() == null) ? 0 : getFsdd().hashCode());
        result = prime * result + ((getFczd() == null) ? 0 : getFczd().hashCode());
        return result;
    }
}