package com.hongte.weixin.mybatis.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class XdDkdetailtobankExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    public XdDkdetailtobankExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFidIsNull() {
            addCriterion("FID is null");
            return (Criteria) this;
        }

        public Criteria andFidIsNotNull() {
            addCriterion("FID is not null");
            return (Criteria) this;
        }

        public Criteria andFidEqualTo(Integer value) {
            addCriterion("FID =", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidNotEqualTo(Integer value) {
            addCriterion("FID <>", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidGreaterThan(Integer value) {
            addCriterion("FID >", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidGreaterThanOrEqualTo(Integer value) {
            addCriterion("FID >=", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidLessThan(Integer value) {
            addCriterion("FID <", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidLessThanOrEqualTo(Integer value) {
            addCriterion("FID <=", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidIn(List<Integer> values) {
            addCriterion("FID in", values, "fid");
            return (Criteria) this;
        }

        public Criteria andFidNotIn(List<Integer> values) {
            addCriterion("FID not in", values, "fid");
            return (Criteria) this;
        }

        public Criteria andFidBetween(Integer value1, Integer value2) {
            addCriterion("FID between", value1, value2, "fid");
            return (Criteria) this;
        }

        public Criteria andFidNotBetween(Integer value1, Integer value2) {
            addCriterion("FID not between", value1, value2, "fid");
            return (Criteria) this;
        }

        public Criteria andFstatusIsNull() {
            addCriterion("FStatus is null");
            return (Criteria) this;
        }

        public Criteria andFstatusIsNotNull() {
            addCriterion("FStatus is not null");
            return (Criteria) this;
        }

        public Criteria andFstatusEqualTo(String value) {
            addCriterion("FStatus =", value, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusNotEqualTo(String value) {
            addCriterion("FStatus <>", value, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusGreaterThan(String value) {
            addCriterion("FStatus >", value, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusGreaterThanOrEqualTo(String value) {
            addCriterion("FStatus >=", value, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusLessThan(String value) {
            addCriterion("FStatus <", value, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusLessThanOrEqualTo(String value) {
            addCriterion("FStatus <=", value, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusLike(String value) {
            addCriterion("FStatus like", value, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusNotLike(String value) {
            addCriterion("FStatus not like", value, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusIn(List<String> values) {
            addCriterion("FStatus in", values, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusNotIn(List<String> values) {
            addCriterion("FStatus not in", values, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusBetween(String value1, String value2) {
            addCriterion("FStatus between", value1, value2, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFstatusNotBetween(String value1, String value2) {
            addCriterion("FStatus not between", value1, value2, "fstatus");
            return (Criteria) this;
        }

        public Criteria andFbillnoIsNull() {
            addCriterion("FBillNo is null");
            return (Criteria) this;
        }

        public Criteria andFbillnoIsNotNull() {
            addCriterion("FBillNo is not null");
            return (Criteria) this;
        }

        public Criteria andFbillnoEqualTo(String value) {
            addCriterion("FBillNo =", value, "fbillno");
            return (Criteria) this;
        }

        public Criteria andFbillnoNotEqualTo(String value) {
            addCriterion("FBillNo <>", value, "fbillno");
            return (Criteria) this;
        }

        public Criteria andFbillnoGreaterThan(String value) {
            addCriterion("FBillNo >", value, "fbillno");
            return (Criteria) this;
        }

        public Criteria andFbillnoGreaterThanOrEqualTo(String value) {
            addCriterion("FBillNo >=", value, "fbillno");
            return (Criteria) this;
        }

        public Criteria andFbillnoLessThan(String value) {
            addCriterion("FBillNo <", value, "fbillno");
            return (Criteria) this;
        }

        public Criteria andFbillnoLessThanOrEqualTo(String value) {
            addCriterion("FBillNo <=", value, "fbillno");
            return (Criteria) this;
        }

        public Criteria andFbillnoLike(String value) {
            addCriterion("FBillNo like", value, "fbillno");
            return (Criteria) this;
        }

        public Criteria andFbillnoNotLike(String value) {
            addCriterion("FBillNo not like", value, "fbillno");
            return (Criteria) this;
        }

        public Criteria andFbillnoIn(List<String> values) {
            addCriterion("FBillNo in", values, "fbillno");
            return (Criteria) this;
        }

        public Criteria andFbillnoNotIn(List<String> values) {
            addCriterion("FBillNo not in", values, "fbillno");
            return (Criteria) this;
        }

        public Criteria andFbillnoBetween(String value1, String value2) {
            addCriterion("FBillNo between", value1, value2, "fbillno");
            return (Criteria) this;
        }

        public Criteria andFbillnoNotBetween(String value1, String value2) {
            addCriterion("FBillNo not between", value1, value2, "fbillno");
            return (Criteria) this;
        }

        public Criteria andFcustidIsNull() {
            addCriterion("FCustID is null");
            return (Criteria) this;
        }

        public Criteria andFcustidIsNotNull() {
            addCriterion("FCustID is not null");
            return (Criteria) this;
        }

        public Criteria andFcustidEqualTo(String value) {
            addCriterion("FCustID =", value, "fcustid");
            return (Criteria) this;
        }

        public Criteria andFcustidNotEqualTo(String value) {
            addCriterion("FCustID <>", value, "fcustid");
            return (Criteria) this;
        }

        public Criteria andFcustidGreaterThan(String value) {
            addCriterion("FCustID >", value, "fcustid");
            return (Criteria) this;
        }

        public Criteria andFcustidGreaterThanOrEqualTo(String value) {
            addCriterion("FCustID >=", value, "fcustid");
            return (Criteria) this;
        }

        public Criteria andFcustidLessThan(String value) {
            addCriterion("FCustID <", value, "fcustid");
            return (Criteria) this;
        }

        public Criteria andFcustidLessThanOrEqualTo(String value) {
            addCriterion("FCustID <=", value, "fcustid");
            return (Criteria) this;
        }

        public Criteria andFcustidLike(String value) {
            addCriterion("FCustID like", value, "fcustid");
            return (Criteria) this;
        }

        public Criteria andFcustidNotLike(String value) {
            addCriterion("FCustID not like", value, "fcustid");
            return (Criteria) this;
        }

        public Criteria andFcustidIn(List<String> values) {
            addCriterion("FCustID in", values, "fcustid");
            return (Criteria) this;
        }

        public Criteria andFcustidNotIn(List<String> values) {
            addCriterion("FCustID not in", values, "fcustid");
            return (Criteria) this;
        }

        public Criteria andFcustidBetween(String value1, String value2) {
            addCriterion("FCustID between", value1, value2, "fcustid");
            return (Criteria) this;
        }

        public Criteria andFcustidNotBetween(String value1, String value2) {
            addCriterion("FCustID not between", value1, value2, "fcustid");
            return (Criteria) this;
        }

        public Criteria andFcustidFnameIsNull() {
            addCriterion("FCustID_FName is null");
            return (Criteria) this;
        }

        public Criteria andFcustidFnameIsNotNull() {
            addCriterion("FCustID_FName is not null");
            return (Criteria) this;
        }

        public Criteria andFcustidFnameEqualTo(String value) {
            addCriterion("FCustID_FName =", value, "fcustidFname");
            return (Criteria) this;
        }

        public Criteria andFcustidFnameNotEqualTo(String value) {
            addCriterion("FCustID_FName <>", value, "fcustidFname");
            return (Criteria) this;
        }

        public Criteria andFcustidFnameGreaterThan(String value) {
            addCriterion("FCustID_FName >", value, "fcustidFname");
            return (Criteria) this;
        }

        public Criteria andFcustidFnameGreaterThanOrEqualTo(String value) {
            addCriterion("FCustID_FName >=", value, "fcustidFname");
            return (Criteria) this;
        }

        public Criteria andFcustidFnameLessThan(String value) {
            addCriterion("FCustID_FName <", value, "fcustidFname");
            return (Criteria) this;
        }

        public Criteria andFcustidFnameLessThanOrEqualTo(String value) {
            addCriterion("FCustID_FName <=", value, "fcustidFname");
            return (Criteria) this;
        }

        public Criteria andFcustidFnameLike(String value) {
            addCriterion("FCustID_FName like", value, "fcustidFname");
            return (Criteria) this;
        }

        public Criteria andFcustidFnameNotLike(String value) {
            addCriterion("FCustID_FName not like", value, "fcustidFname");
            return (Criteria) this;
        }

        public Criteria andFcustidFnameIn(List<String> values) {
            addCriterion("FCustID_FName in", values, "fcustidFname");
            return (Criteria) this;
        }

        public Criteria andFcustidFnameNotIn(List<String> values) {
            addCriterion("FCustID_FName not in", values, "fcustidFname");
            return (Criteria) this;
        }

        public Criteria andFcustidFnameBetween(String value1, String value2) {
            addCriterion("FCustID_FName between", value1, value2, "fcustidFname");
            return (Criteria) this;
        }

        public Criteria andFcustidFnameNotBetween(String value1, String value2) {
            addCriterion("FCustID_FName not between", value1, value2, "fcustidFname");
            return (Criteria) this;
        }

        public Criteria andFdeptidIsNull() {
            addCriterion("FDeptID is null");
            return (Criteria) this;
        }

        public Criteria andFdeptidIsNotNull() {
            addCriterion("FDeptID is not null");
            return (Criteria) this;
        }

        public Criteria andFdeptidEqualTo(Integer value) {
            addCriterion("FDeptID =", value, "fdeptid");
            return (Criteria) this;
        }

        public Criteria andFdeptidNotEqualTo(Integer value) {
            addCriterion("FDeptID <>", value, "fdeptid");
            return (Criteria) this;
        }

        public Criteria andFdeptidGreaterThan(Integer value) {
            addCriterion("FDeptID >", value, "fdeptid");
            return (Criteria) this;
        }

        public Criteria andFdeptidGreaterThanOrEqualTo(Integer value) {
            addCriterion("FDeptID >=", value, "fdeptid");
            return (Criteria) this;
        }

        public Criteria andFdeptidLessThan(Integer value) {
            addCriterion("FDeptID <", value, "fdeptid");
            return (Criteria) this;
        }

        public Criteria andFdeptidLessThanOrEqualTo(Integer value) {
            addCriterion("FDeptID <=", value, "fdeptid");
            return (Criteria) this;
        }

        public Criteria andFdeptidIn(List<Integer> values) {
            addCriterion("FDeptID in", values, "fdeptid");
            return (Criteria) this;
        }

        public Criteria andFdeptidNotIn(List<Integer> values) {
            addCriterion("FDeptID not in", values, "fdeptid");
            return (Criteria) this;
        }

        public Criteria andFdeptidBetween(Integer value1, Integer value2) {
            addCriterion("FDeptID between", value1, value2, "fdeptid");
            return (Criteria) this;
        }

        public Criteria andFdeptidNotBetween(Integer value1, Integer value2) {
            addCriterion("FDeptID not between", value1, value2, "fdeptid");
            return (Criteria) this;
        }

        public Criteria andFdeptidFnameIsNull() {
            addCriterion("FDeptID_FName is null");
            return (Criteria) this;
        }

        public Criteria andFdeptidFnameIsNotNull() {
            addCriterion("FDeptID_FName is not null");
            return (Criteria) this;
        }

        public Criteria andFdeptidFnameEqualTo(String value) {
            addCriterion("FDeptID_FName =", value, "fdeptidFname");
            return (Criteria) this;
        }

        public Criteria andFdeptidFnameNotEqualTo(String value) {
            addCriterion("FDeptID_FName <>", value, "fdeptidFname");
            return (Criteria) this;
        }

        public Criteria andFdeptidFnameGreaterThan(String value) {
            addCriterion("FDeptID_FName >", value, "fdeptidFname");
            return (Criteria) this;
        }

        public Criteria andFdeptidFnameGreaterThanOrEqualTo(String value) {
            addCriterion("FDeptID_FName >=", value, "fdeptidFname");
            return (Criteria) this;
        }

        public Criteria andFdeptidFnameLessThan(String value) {
            addCriterion("FDeptID_FName <", value, "fdeptidFname");
            return (Criteria) this;
        }

        public Criteria andFdeptidFnameLessThanOrEqualTo(String value) {
            addCriterion("FDeptID_FName <=", value, "fdeptidFname");
            return (Criteria) this;
        }

        public Criteria andFdeptidFnameLike(String value) {
            addCriterion("FDeptID_FName like", value, "fdeptidFname");
            return (Criteria) this;
        }

        public Criteria andFdeptidFnameNotLike(String value) {
            addCriterion("FDeptID_FName not like", value, "fdeptidFname");
            return (Criteria) this;
        }

        public Criteria andFdeptidFnameIn(List<String> values) {
            addCriterion("FDeptID_FName in", values, "fdeptidFname");
            return (Criteria) this;
        }

        public Criteria andFdeptidFnameNotIn(List<String> values) {
            addCriterion("FDeptID_FName not in", values, "fdeptidFname");
            return (Criteria) this;
        }

        public Criteria andFdeptidFnameBetween(String value1, String value2) {
            addCriterion("FDeptID_FName between", value1, value2, "fdeptidFname");
            return (Criteria) this;
        }

        public Criteria andFdeptidFnameNotBetween(String value1, String value2) {
            addCriterion("FDeptID_FName not between", value1, value2, "fdeptidFname");
            return (Criteria) this;
        }

        public Criteria andFvbankidIsNull() {
            addCriterion("FVBankID is null");
            return (Criteria) this;
        }

        public Criteria andFvbankidIsNotNull() {
            addCriterion("FVBankID is not null");
            return (Criteria) this;
        }

        public Criteria andFvbankidEqualTo(Integer value) {
            addCriterion("FVBankID =", value, "fvbankid");
            return (Criteria) this;
        }

        public Criteria andFvbankidNotEqualTo(Integer value) {
            addCriterion("FVBankID <>", value, "fvbankid");
            return (Criteria) this;
        }

        public Criteria andFvbankidGreaterThan(Integer value) {
            addCriterion("FVBankID >", value, "fvbankid");
            return (Criteria) this;
        }

        public Criteria andFvbankidGreaterThanOrEqualTo(Integer value) {
            addCriterion("FVBankID >=", value, "fvbankid");
            return (Criteria) this;
        }

        public Criteria andFvbankidLessThan(Integer value) {
            addCriterion("FVBankID <", value, "fvbankid");
            return (Criteria) this;
        }

        public Criteria andFvbankidLessThanOrEqualTo(Integer value) {
            addCriterion("FVBankID <=", value, "fvbankid");
            return (Criteria) this;
        }

        public Criteria andFvbankidIn(List<Integer> values) {
            addCriterion("FVBankID in", values, "fvbankid");
            return (Criteria) this;
        }

        public Criteria andFvbankidNotIn(List<Integer> values) {
            addCriterion("FVBankID not in", values, "fvbankid");
            return (Criteria) this;
        }

        public Criteria andFvbankidBetween(Integer value1, Integer value2) {
            addCriterion("FVBankID between", value1, value2, "fvbankid");
            return (Criteria) this;
        }

        public Criteria andFvbankidNotBetween(Integer value1, Integer value2) {
            addCriterion("FVBankID not between", value1, value2, "fvbankid");
            return (Criteria) this;
        }

        public Criteria andFvtypeIsNull() {
            addCriterion("FVType is null");
            return (Criteria) this;
        }

        public Criteria andFvtypeIsNotNull() {
            addCriterion("FVType is not null");
            return (Criteria) this;
        }

        public Criteria andFvtypeEqualTo(Integer value) {
            addCriterion("FVType =", value, "fvtype");
            return (Criteria) this;
        }

        public Criteria andFvtypeNotEqualTo(Integer value) {
            addCriterion("FVType <>", value, "fvtype");
            return (Criteria) this;
        }

        public Criteria andFvtypeGreaterThan(Integer value) {
            addCriterion("FVType >", value, "fvtype");
            return (Criteria) this;
        }

        public Criteria andFvtypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("FVType >=", value, "fvtype");
            return (Criteria) this;
        }

        public Criteria andFvtypeLessThan(Integer value) {
            addCriterion("FVType <", value, "fvtype");
            return (Criteria) this;
        }

        public Criteria andFvtypeLessThanOrEqualTo(Integer value) {
            addCriterion("FVType <=", value, "fvtype");
            return (Criteria) this;
        }

        public Criteria andFvtypeIn(List<Integer> values) {
            addCriterion("FVType in", values, "fvtype");
            return (Criteria) this;
        }

        public Criteria andFvtypeNotIn(List<Integer> values) {
            addCriterion("FVType not in", values, "fvtype");
            return (Criteria) this;
        }

        public Criteria andFvtypeBetween(Integer value1, Integer value2) {
            addCriterion("FVType between", value1, value2, "fvtype");
            return (Criteria) this;
        }

        public Criteria andFvtypeNotBetween(Integer value1, Integer value2) {
            addCriterion("FVType not between", value1, value2, "fvtype");
            return (Criteria) this;
        }

        public Criteria andFvperiodIsNull() {
            addCriterion("FVPeriod is null");
            return (Criteria) this;
        }

        public Criteria andFvperiodIsNotNull() {
            addCriterion("FVPeriod is not null");
            return (Criteria) this;
        }

        public Criteria andFvperiodEqualTo(BigDecimal value) {
            addCriterion("FVPeriod =", value, "fvperiod");
            return (Criteria) this;
        }

        public Criteria andFvperiodNotEqualTo(BigDecimal value) {
            addCriterion("FVPeriod <>", value, "fvperiod");
            return (Criteria) this;
        }

        public Criteria andFvperiodGreaterThan(BigDecimal value) {
            addCriterion("FVPeriod >", value, "fvperiod");
            return (Criteria) this;
        }

        public Criteria andFvperiodGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FVPeriod >=", value, "fvperiod");
            return (Criteria) this;
        }

        public Criteria andFvperiodLessThan(BigDecimal value) {
            addCriterion("FVPeriod <", value, "fvperiod");
            return (Criteria) this;
        }

        public Criteria andFvperiodLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FVPeriod <=", value, "fvperiod");
            return (Criteria) this;
        }

        public Criteria andFvperiodIn(List<BigDecimal> values) {
            addCriterion("FVPeriod in", values, "fvperiod");
            return (Criteria) this;
        }

        public Criteria andFvperiodNotIn(List<BigDecimal> values) {
            addCriterion("FVPeriod not in", values, "fvperiod");
            return (Criteria) this;
        }

        public Criteria andFvperiodBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FVPeriod between", value1, value2, "fvperiod");
            return (Criteria) this;
        }

        public Criteria andFvperiodNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FVPeriod not between", value1, value2, "fvperiod");
            return (Criteria) this;
        }

        public Criteria andFvdebitamtIsNull() {
            addCriterion("FVDebitAmt is null");
            return (Criteria) this;
        }

        public Criteria andFvdebitamtIsNotNull() {
            addCriterion("FVDebitAmt is not null");
            return (Criteria) this;
        }

        public Criteria andFvdebitamtEqualTo(BigDecimal value) {
            addCriterion("FVDebitAmt =", value, "fvdebitamt");
            return (Criteria) this;
        }

        public Criteria andFvdebitamtNotEqualTo(BigDecimal value) {
            addCriterion("FVDebitAmt <>", value, "fvdebitamt");
            return (Criteria) this;
        }

        public Criteria andFvdebitamtGreaterThan(BigDecimal value) {
            addCriterion("FVDebitAmt >", value, "fvdebitamt");
            return (Criteria) this;
        }

        public Criteria andFvdebitamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FVDebitAmt >=", value, "fvdebitamt");
            return (Criteria) this;
        }

        public Criteria andFvdebitamtLessThan(BigDecimal value) {
            addCriterion("FVDebitAmt <", value, "fvdebitamt");
            return (Criteria) this;
        }

        public Criteria andFvdebitamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FVDebitAmt <=", value, "fvdebitamt");
            return (Criteria) this;
        }

        public Criteria andFvdebitamtIn(List<BigDecimal> values) {
            addCriterion("FVDebitAmt in", values, "fvdebitamt");
            return (Criteria) this;
        }

        public Criteria andFvdebitamtNotIn(List<BigDecimal> values) {
            addCriterion("FVDebitAmt not in", values, "fvdebitamt");
            return (Criteria) this;
        }

        public Criteria andFvdebitamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FVDebitAmt between", value1, value2, "fvdebitamt");
            return (Criteria) this;
        }

        public Criteria andFvdebitamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FVDebitAmt not between", value1, value2, "fvdebitamt");
            return (Criteria) this;
        }

        public Criteria andFreceivedateIsNull() {
            addCriterion("FReceiveDate is null");
            return (Criteria) this;
        }

        public Criteria andFreceivedateIsNotNull() {
            addCriterion("FReceiveDate is not null");
            return (Criteria) this;
        }

        public Criteria andFreceivedateEqualTo(Date value) {
            addCriterion("FReceiveDate =", value, "freceivedate");
            return (Criteria) this;
        }

        public Criteria andFreceivedateNotEqualTo(Date value) {
            addCriterion("FReceiveDate <>", value, "freceivedate");
            return (Criteria) this;
        }

        public Criteria andFreceivedateGreaterThan(Date value) {
            addCriterion("FReceiveDate >", value, "freceivedate");
            return (Criteria) this;
        }

        public Criteria andFreceivedateGreaterThanOrEqualTo(Date value) {
            addCriterion("FReceiveDate >=", value, "freceivedate");
            return (Criteria) this;
        }

        public Criteria andFreceivedateLessThan(Date value) {
            addCriterion("FReceiveDate <", value, "freceivedate");
            return (Criteria) this;
        }

        public Criteria andFreceivedateLessThanOrEqualTo(Date value) {
            addCriterion("FReceiveDate <=", value, "freceivedate");
            return (Criteria) this;
        }

        public Criteria andFreceivedateIn(List<Date> values) {
            addCriterion("FReceiveDate in", values, "freceivedate");
            return (Criteria) this;
        }

        public Criteria andFreceivedateNotIn(List<Date> values) {
            addCriterion("FReceiveDate not in", values, "freceivedate");
            return (Criteria) this;
        }

        public Criteria andFreceivedateBetween(Date value1, Date value2) {
            addCriterion("FReceiveDate between", value1, value2, "freceivedate");
            return (Criteria) this;
        }

        public Criteria andFreceivedateNotBetween(Date value1, Date value2) {
            addCriterion("FReceiveDate not between", value1, value2, "freceivedate");
            return (Criteria) this;
        }

        public Criteria andFalldateIsNull() {
            addCriterion("FAllDate is null");
            return (Criteria) this;
        }

        public Criteria andFalldateIsNotNull() {
            addCriterion("FAllDate is not null");
            return (Criteria) this;
        }

        public Criteria andFalldateEqualTo(Date value) {
            addCriterion("FAllDate =", value, "falldate");
            return (Criteria) this;
        }

        public Criteria andFalldateNotEqualTo(Date value) {
            addCriterion("FAllDate <>", value, "falldate");
            return (Criteria) this;
        }

        public Criteria andFalldateGreaterThan(Date value) {
            addCriterion("FAllDate >", value, "falldate");
            return (Criteria) this;
        }

        public Criteria andFalldateGreaterThanOrEqualTo(Date value) {
            addCriterion("FAllDate >=", value, "falldate");
            return (Criteria) this;
        }

        public Criteria andFalldateLessThan(Date value) {
            addCriterion("FAllDate <", value, "falldate");
            return (Criteria) this;
        }

        public Criteria andFalldateLessThanOrEqualTo(Date value) {
            addCriterion("FAllDate <=", value, "falldate");
            return (Criteria) this;
        }

        public Criteria andFalldateIn(List<Date> values) {
            addCriterion("FAllDate in", values, "falldate");
            return (Criteria) this;
        }

        public Criteria andFalldateNotIn(List<Date> values) {
            addCriterion("FAllDate not in", values, "falldate");
            return (Criteria) this;
        }

        public Criteria andFalldateBetween(Date value1, Date value2) {
            addCriterion("FAllDate between", value1, value2, "falldate");
            return (Criteria) this;
        }

        public Criteria andFalldateNotBetween(Date value1, Date value2) {
            addCriterion("FAllDate not between", value1, value2, "falldate");
            return (Criteria) this;
        }

        public Criteria andFsenddateIsNull() {
            addCriterion("FSendDate is null");
            return (Criteria) this;
        }

        public Criteria andFsenddateIsNotNull() {
            addCriterion("FSendDate is not null");
            return (Criteria) this;
        }

        public Criteria andFsenddateEqualTo(Date value) {
            addCriterion("FSendDate =", value, "fsenddate");
            return (Criteria) this;
        }

        public Criteria andFsenddateNotEqualTo(Date value) {
            addCriterion("FSendDate <>", value, "fsenddate");
            return (Criteria) this;
        }

        public Criteria andFsenddateGreaterThan(Date value) {
            addCriterion("FSendDate >", value, "fsenddate");
            return (Criteria) this;
        }

        public Criteria andFsenddateGreaterThanOrEqualTo(Date value) {
            addCriterion("FSendDate >=", value, "fsenddate");
            return (Criteria) this;
        }

        public Criteria andFsenddateLessThan(Date value) {
            addCriterion("FSendDate <", value, "fsenddate");
            return (Criteria) this;
        }

        public Criteria andFsenddateLessThanOrEqualTo(Date value) {
            addCriterion("FSendDate <=", value, "fsenddate");
            return (Criteria) this;
        }

        public Criteria andFsenddateIn(List<Date> values) {
            addCriterion("FSendDate in", values, "fsenddate");
            return (Criteria) this;
        }

        public Criteria andFsenddateNotIn(List<Date> values) {
            addCriterion("FSendDate not in", values, "fsenddate");
            return (Criteria) this;
        }

        public Criteria andFsenddateBetween(Date value1, Date value2) {
            addCriterion("FSendDate between", value1, value2, "fsenddate");
            return (Criteria) this;
        }

        public Criteria andFsenddateNotBetween(Date value1, Date value2) {
            addCriterion("FSendDate not between", value1, value2, "fsenddate");
            return (Criteria) this;
        }

        public Criteria andFbilleridIsNull() {
            addCriterion("FBillerID is null");
            return (Criteria) this;
        }

        public Criteria andFbilleridIsNotNull() {
            addCriterion("FBillerID is not null");
            return (Criteria) this;
        }

        public Criteria andFbilleridEqualTo(Integer value) {
            addCriterion("FBillerID =", value, "fbillerid");
            return (Criteria) this;
        }

        public Criteria andFbilleridNotEqualTo(Integer value) {
            addCriterion("FBillerID <>", value, "fbillerid");
            return (Criteria) this;
        }

        public Criteria andFbilleridGreaterThan(Integer value) {
            addCriterion("FBillerID >", value, "fbillerid");
            return (Criteria) this;
        }

        public Criteria andFbilleridGreaterThanOrEqualTo(Integer value) {
            addCriterion("FBillerID >=", value, "fbillerid");
            return (Criteria) this;
        }

        public Criteria andFbilleridLessThan(Integer value) {
            addCriterion("FBillerID <", value, "fbillerid");
            return (Criteria) this;
        }

        public Criteria andFbilleridLessThanOrEqualTo(Integer value) {
            addCriterion("FBillerID <=", value, "fbillerid");
            return (Criteria) this;
        }

        public Criteria andFbilleridIn(List<Integer> values) {
            addCriterion("FBillerID in", values, "fbillerid");
            return (Criteria) this;
        }

        public Criteria andFbilleridNotIn(List<Integer> values) {
            addCriterion("FBillerID not in", values, "fbillerid");
            return (Criteria) this;
        }

        public Criteria andFbilleridBetween(Integer value1, Integer value2) {
            addCriterion("FBillerID between", value1, value2, "fbillerid");
            return (Criteria) this;
        }

        public Criteria andFbilleridNotBetween(Integer value1, Integer value2) {
            addCriterion("FBillerID not between", value1, value2, "fbillerid");
            return (Criteria) this;
        }

        public Criteria andFbillerdateIsNull() {
            addCriterion("FBillerDate is null");
            return (Criteria) this;
        }

        public Criteria andFbillerdateIsNotNull() {
            addCriterion("FBillerDate is not null");
            return (Criteria) this;
        }

        public Criteria andFbillerdateEqualTo(Date value) {
            addCriterion("FBillerDate =", value, "fbillerdate");
            return (Criteria) this;
        }

        public Criteria andFbillerdateNotEqualTo(Date value) {
            addCriterion("FBillerDate <>", value, "fbillerdate");
            return (Criteria) this;
        }

        public Criteria andFbillerdateGreaterThan(Date value) {
            addCriterion("FBillerDate >", value, "fbillerdate");
            return (Criteria) this;
        }

        public Criteria andFbillerdateGreaterThanOrEqualTo(Date value) {
            addCriterion("FBillerDate >=", value, "fbillerdate");
            return (Criteria) this;
        }

        public Criteria andFbillerdateLessThan(Date value) {
            addCriterion("FBillerDate <", value, "fbillerdate");
            return (Criteria) this;
        }

        public Criteria andFbillerdateLessThanOrEqualTo(Date value) {
            addCriterion("FBillerDate <=", value, "fbillerdate");
            return (Criteria) this;
        }

        public Criteria andFbillerdateIn(List<Date> values) {
            addCriterion("FBillerDate in", values, "fbillerdate");
            return (Criteria) this;
        }

        public Criteria andFbillerdateNotIn(List<Date> values) {
            addCriterion("FBillerDate not in", values, "fbillerdate");
            return (Criteria) this;
        }

        public Criteria andFbillerdateBetween(Date value1, Date value2) {
            addCriterion("FBillerDate between", value1, value2, "fbillerdate");
            return (Criteria) this;
        }

        public Criteria andFbillerdateNotBetween(Date value1, Date value2) {
            addCriterion("FBillerDate not between", value1, value2, "fbillerdate");
            return (Criteria) this;
        }

        public Criteria andFcheckeridIsNull() {
            addCriterion("FCheckerID is null");
            return (Criteria) this;
        }

        public Criteria andFcheckeridIsNotNull() {
            addCriterion("FCheckerID is not null");
            return (Criteria) this;
        }

        public Criteria andFcheckeridEqualTo(Integer value) {
            addCriterion("FCheckerID =", value, "fcheckerid");
            return (Criteria) this;
        }

        public Criteria andFcheckeridNotEqualTo(Integer value) {
            addCriterion("FCheckerID <>", value, "fcheckerid");
            return (Criteria) this;
        }

        public Criteria andFcheckeridGreaterThan(Integer value) {
            addCriterion("FCheckerID >", value, "fcheckerid");
            return (Criteria) this;
        }

        public Criteria andFcheckeridGreaterThanOrEqualTo(Integer value) {
            addCriterion("FCheckerID >=", value, "fcheckerid");
            return (Criteria) this;
        }

        public Criteria andFcheckeridLessThan(Integer value) {
            addCriterion("FCheckerID <", value, "fcheckerid");
            return (Criteria) this;
        }

        public Criteria andFcheckeridLessThanOrEqualTo(Integer value) {
            addCriterion("FCheckerID <=", value, "fcheckerid");
            return (Criteria) this;
        }

        public Criteria andFcheckeridIn(List<Integer> values) {
            addCriterion("FCheckerID in", values, "fcheckerid");
            return (Criteria) this;
        }

        public Criteria andFcheckeridNotIn(List<Integer> values) {
            addCriterion("FCheckerID not in", values, "fcheckerid");
            return (Criteria) this;
        }

        public Criteria andFcheckeridBetween(Integer value1, Integer value2) {
            addCriterion("FCheckerID between", value1, value2, "fcheckerid");
            return (Criteria) this;
        }

        public Criteria andFcheckeridNotBetween(Integer value1, Integer value2) {
            addCriterion("FCheckerID not between", value1, value2, "fcheckerid");
            return (Criteria) this;
        }

        public Criteria andFcheckerdateIsNull() {
            addCriterion("FCheckerDate is null");
            return (Criteria) this;
        }

        public Criteria andFcheckerdateIsNotNull() {
            addCriterion("FCheckerDate is not null");
            return (Criteria) this;
        }

        public Criteria andFcheckerdateEqualTo(Date value) {
            addCriterion("FCheckerDate =", value, "fcheckerdate");
            return (Criteria) this;
        }

        public Criteria andFcheckerdateNotEqualTo(Date value) {
            addCriterion("FCheckerDate <>", value, "fcheckerdate");
            return (Criteria) this;
        }

        public Criteria andFcheckerdateGreaterThan(Date value) {
            addCriterion("FCheckerDate >", value, "fcheckerdate");
            return (Criteria) this;
        }

        public Criteria andFcheckerdateGreaterThanOrEqualTo(Date value) {
            addCriterion("FCheckerDate >=", value, "fcheckerdate");
            return (Criteria) this;
        }

        public Criteria andFcheckerdateLessThan(Date value) {
            addCriterion("FCheckerDate <", value, "fcheckerdate");
            return (Criteria) this;
        }

        public Criteria andFcheckerdateLessThanOrEqualTo(Date value) {
            addCriterion("FCheckerDate <=", value, "fcheckerdate");
            return (Criteria) this;
        }

        public Criteria andFcheckerdateIn(List<Date> values) {
            addCriterion("FCheckerDate in", values, "fcheckerdate");
            return (Criteria) this;
        }

        public Criteria andFcheckerdateNotIn(List<Date> values) {
            addCriterion("FCheckerDate not in", values, "fcheckerdate");
            return (Criteria) this;
        }

        public Criteria andFcheckerdateBetween(Date value1, Date value2) {
            addCriterion("FCheckerDate between", value1, value2, "fcheckerdate");
            return (Criteria) this;
        }

        public Criteria andFcheckerdateNotBetween(Date value1, Date value2) {
            addCriterion("FCheckerDate not between", value1, value2, "fcheckerdate");
            return (Criteria) this;
        }

        public Criteria andFcustidfnameIsNull() {
            addCriterion("FCustIDFName is null");
            return (Criteria) this;
        }

        public Criteria andFcustidfnameIsNotNull() {
            addCriterion("FCustIDFName is not null");
            return (Criteria) this;
        }

        public Criteria andFcustidfnameEqualTo(String value) {
            addCriterion("FCustIDFName =", value, "fcustidfname");
            return (Criteria) this;
        }

        public Criteria andFcustidfnameNotEqualTo(String value) {
            addCriterion("FCustIDFName <>", value, "fcustidfname");
            return (Criteria) this;
        }

        public Criteria andFcustidfnameGreaterThan(String value) {
            addCriterion("FCustIDFName >", value, "fcustidfname");
            return (Criteria) this;
        }

        public Criteria andFcustidfnameGreaterThanOrEqualTo(String value) {
            addCriterion("FCustIDFName >=", value, "fcustidfname");
            return (Criteria) this;
        }

        public Criteria andFcustidfnameLessThan(String value) {
            addCriterion("FCustIDFName <", value, "fcustidfname");
            return (Criteria) this;
        }

        public Criteria andFcustidfnameLessThanOrEqualTo(String value) {
            addCriterion("FCustIDFName <=", value, "fcustidfname");
            return (Criteria) this;
        }

        public Criteria andFcustidfnameLike(String value) {
            addCriterion("FCustIDFName like", value, "fcustidfname");
            return (Criteria) this;
        }

        public Criteria andFcustidfnameNotLike(String value) {
            addCriterion("FCustIDFName not like", value, "fcustidfname");
            return (Criteria) this;
        }

        public Criteria andFcustidfnameIn(List<String> values) {
            addCriterion("FCustIDFName in", values, "fcustidfname");
            return (Criteria) this;
        }

        public Criteria andFcustidfnameNotIn(List<String> values) {
            addCriterion("FCustIDFName not in", values, "fcustidfname");
            return (Criteria) this;
        }

        public Criteria andFcustidfnameBetween(String value1, String value2) {
            addCriterion("FCustIDFName between", value1, value2, "fcustidfname");
            return (Criteria) this;
        }

        public Criteria andFcustidfnameNotBetween(String value1, String value2) {
            addCriterion("FCustIDFName not between", value1, value2, "fcustidfname");
            return (Criteria) this;
        }

        public Criteria andFnoteIsNull() {
            addCriterion("FNote is null");
            return (Criteria) this;
        }

        public Criteria andFnoteIsNotNull() {
            addCriterion("FNote is not null");
            return (Criteria) this;
        }

        public Criteria andFnoteEqualTo(String value) {
            addCriterion("FNote =", value, "fnote");
            return (Criteria) this;
        }

        public Criteria andFnoteNotEqualTo(String value) {
            addCriterion("FNote <>", value, "fnote");
            return (Criteria) this;
        }

        public Criteria andFnoteGreaterThan(String value) {
            addCriterion("FNote >", value, "fnote");
            return (Criteria) this;
        }

        public Criteria andFnoteGreaterThanOrEqualTo(String value) {
            addCriterion("FNote >=", value, "fnote");
            return (Criteria) this;
        }

        public Criteria andFnoteLessThan(String value) {
            addCriterion("FNote <", value, "fnote");
            return (Criteria) this;
        }

        public Criteria andFnoteLessThanOrEqualTo(String value) {
            addCriterion("FNote <=", value, "fnote");
            return (Criteria) this;
        }

        public Criteria andFnoteLike(String value) {
            addCriterion("FNote like", value, "fnote");
            return (Criteria) this;
        }

        public Criteria andFnoteNotLike(String value) {
            addCriterion("FNote not like", value, "fnote");
            return (Criteria) this;
        }

        public Criteria andFnoteIn(List<String> values) {
            addCriterion("FNote in", values, "fnote");
            return (Criteria) this;
        }

        public Criteria andFnoteNotIn(List<String> values) {
            addCriterion("FNote not in", values, "fnote");
            return (Criteria) this;
        }

        public Criteria andFnoteBetween(String value1, String value2) {
            addCriterion("FNote between", value1, value2, "fnote");
            return (Criteria) this;
        }

        public Criteria andFnoteNotBetween(String value1, String value2) {
            addCriterion("FNote not between", value1, value2, "fnote");
            return (Criteria) this;
        }

        public Criteria andFrateIsNull() {
            addCriterion("FRate is null");
            return (Criteria) this;
        }

        public Criteria andFrateIsNotNull() {
            addCriterion("FRate is not null");
            return (Criteria) this;
        }

        public Criteria andFrateEqualTo(BigDecimal value) {
            addCriterion("FRate =", value, "frate");
            return (Criteria) this;
        }

        public Criteria andFrateNotEqualTo(BigDecimal value) {
            addCriterion("FRate <>", value, "frate");
            return (Criteria) this;
        }

        public Criteria andFrateGreaterThan(BigDecimal value) {
            addCriterion("FRate >", value, "frate");
            return (Criteria) this;
        }

        public Criteria andFrateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FRate >=", value, "frate");
            return (Criteria) this;
        }

        public Criteria andFrateLessThan(BigDecimal value) {
            addCriterion("FRate <", value, "frate");
            return (Criteria) this;
        }

        public Criteria andFrateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FRate <=", value, "frate");
            return (Criteria) this;
        }

        public Criteria andFrateIn(List<BigDecimal> values) {
            addCriterion("FRate in", values, "frate");
            return (Criteria) this;
        }

        public Criteria andFrateNotIn(List<BigDecimal> values) {
            addCriterion("FRate not in", values, "frate");
            return (Criteria) this;
        }

        public Criteria andFrateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FRate between", value1, value2, "frate");
            return (Criteria) this;
        }

        public Criteria andFrateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FRate not between", value1, value2, "frate");
            return (Criteria) this;
        }

        public Criteria andFstandardIsNull() {
            addCriterion("FStandard is null");
            return (Criteria) this;
        }

        public Criteria andFstandardIsNotNull() {
            addCriterion("FStandard is not null");
            return (Criteria) this;
        }

        public Criteria andFstandardEqualTo(BigDecimal value) {
            addCriterion("FStandard =", value, "fstandard");
            return (Criteria) this;
        }

        public Criteria andFstandardNotEqualTo(BigDecimal value) {
            addCriterion("FStandard <>", value, "fstandard");
            return (Criteria) this;
        }

        public Criteria andFstandardGreaterThan(BigDecimal value) {
            addCriterion("FStandard >", value, "fstandard");
            return (Criteria) this;
        }

        public Criteria andFstandardGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FStandard >=", value, "fstandard");
            return (Criteria) this;
        }

        public Criteria andFstandardLessThan(BigDecimal value) {
            addCriterion("FStandard <", value, "fstandard");
            return (Criteria) this;
        }

        public Criteria andFstandardLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FStandard <=", value, "fstandard");
            return (Criteria) this;
        }

        public Criteria andFstandardIn(List<BigDecimal> values) {
            addCriterion("FStandard in", values, "fstandard");
            return (Criteria) this;
        }

        public Criteria andFstandardNotIn(List<BigDecimal> values) {
            addCriterion("FStandard not in", values, "fstandard");
            return (Criteria) this;
        }

        public Criteria andFstandardBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FStandard between", value1, value2, "fstandard");
            return (Criteria) this;
        }

        public Criteria andFstandardNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FStandard not between", value1, value2, "fstandard");
            return (Criteria) this;
        }

        public Criteria andFcheckerid2IsNull() {
            addCriterion("FCheckerID2 is null");
            return (Criteria) this;
        }

        public Criteria andFcheckerid2IsNotNull() {
            addCriterion("FCheckerID2 is not null");
            return (Criteria) this;
        }

        public Criteria andFcheckerid2EqualTo(Integer value) {
            addCriterion("FCheckerID2 =", value, "fcheckerid2");
            return (Criteria) this;
        }

        public Criteria andFcheckerid2NotEqualTo(Integer value) {
            addCriterion("FCheckerID2 <>", value, "fcheckerid2");
            return (Criteria) this;
        }

        public Criteria andFcheckerid2GreaterThan(Integer value) {
            addCriterion("FCheckerID2 >", value, "fcheckerid2");
            return (Criteria) this;
        }

        public Criteria andFcheckerid2GreaterThanOrEqualTo(Integer value) {
            addCriterion("FCheckerID2 >=", value, "fcheckerid2");
            return (Criteria) this;
        }

        public Criteria andFcheckerid2LessThan(Integer value) {
            addCriterion("FCheckerID2 <", value, "fcheckerid2");
            return (Criteria) this;
        }

        public Criteria andFcheckerid2LessThanOrEqualTo(Integer value) {
            addCriterion("FCheckerID2 <=", value, "fcheckerid2");
            return (Criteria) this;
        }

        public Criteria andFcheckerid2In(List<Integer> values) {
            addCriterion("FCheckerID2 in", values, "fcheckerid2");
            return (Criteria) this;
        }

        public Criteria andFcheckerid2NotIn(List<Integer> values) {
            addCriterion("FCheckerID2 not in", values, "fcheckerid2");
            return (Criteria) this;
        }

        public Criteria andFcheckerid2Between(Integer value1, Integer value2) {
            addCriterion("FCheckerID2 between", value1, value2, "fcheckerid2");
            return (Criteria) this;
        }

        public Criteria andFcheckerid2NotBetween(Integer value1, Integer value2) {
            addCriterion("FCheckerID2 not between", value1, value2, "fcheckerid2");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate2IsNull() {
            addCriterion("FCheckerDate2 is null");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate2IsNotNull() {
            addCriterion("FCheckerDate2 is not null");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate2EqualTo(Date value) {
            addCriterion("FCheckerDate2 =", value, "fcheckerdate2");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate2NotEqualTo(Date value) {
            addCriterion("FCheckerDate2 <>", value, "fcheckerdate2");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate2GreaterThan(Date value) {
            addCriterion("FCheckerDate2 >", value, "fcheckerdate2");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate2GreaterThanOrEqualTo(Date value) {
            addCriterion("FCheckerDate2 >=", value, "fcheckerdate2");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate2LessThan(Date value) {
            addCriterion("FCheckerDate2 <", value, "fcheckerdate2");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate2LessThanOrEqualTo(Date value) {
            addCriterion("FCheckerDate2 <=", value, "fcheckerdate2");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate2In(List<Date> values) {
            addCriterion("FCheckerDate2 in", values, "fcheckerdate2");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate2NotIn(List<Date> values) {
            addCriterion("FCheckerDate2 not in", values, "fcheckerdate2");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate2Between(Date value1, Date value2) {
            addCriterion("FCheckerDate2 between", value1, value2, "fcheckerdate2");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate2NotBetween(Date value1, Date value2) {
            addCriterion("FCheckerDate2 not between", value1, value2, "fcheckerdate2");
            return (Criteria) this;
        }

        public Criteria andFvpriceIsNull() {
            addCriterion("FVPrice is null");
            return (Criteria) this;
        }

        public Criteria andFvpriceIsNotNull() {
            addCriterion("FVPrice is not null");
            return (Criteria) this;
        }

        public Criteria andFvpriceEqualTo(BigDecimal value) {
            addCriterion("FVPrice =", value, "fvprice");
            return (Criteria) this;
        }

        public Criteria andFvpriceNotEqualTo(BigDecimal value) {
            addCriterion("FVPrice <>", value, "fvprice");
            return (Criteria) this;
        }

        public Criteria andFvpriceGreaterThan(BigDecimal value) {
            addCriterion("FVPrice >", value, "fvprice");
            return (Criteria) this;
        }

        public Criteria andFvpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FVPrice >=", value, "fvprice");
            return (Criteria) this;
        }

        public Criteria andFvpriceLessThan(BigDecimal value) {
            addCriterion("FVPrice <", value, "fvprice");
            return (Criteria) this;
        }

        public Criteria andFvpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FVPrice <=", value, "fvprice");
            return (Criteria) this;
        }

        public Criteria andFvpriceIn(List<BigDecimal> values) {
            addCriterion("FVPrice in", values, "fvprice");
            return (Criteria) this;
        }

        public Criteria andFvpriceNotIn(List<BigDecimal> values) {
            addCriterion("FVPrice not in", values, "fvprice");
            return (Criteria) this;
        }

        public Criteria andFvpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FVPrice between", value1, value2, "fvprice");
            return (Criteria) this;
        }

        public Criteria andFvpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FVPrice not between", value1, value2, "fvprice");
            return (Criteria) this;
        }

        public Criteria andFdzdateIsNull() {
            addCriterion("FDZDate is null");
            return (Criteria) this;
        }

        public Criteria andFdzdateIsNotNull() {
            addCriterion("FDZDate is not null");
            return (Criteria) this;
        }

        public Criteria andFdzdateEqualTo(Date value) {
            addCriterion("FDZDate =", value, "fdzdate");
            return (Criteria) this;
        }

        public Criteria andFdzdateNotEqualTo(Date value) {
            addCriterion("FDZDate <>", value, "fdzdate");
            return (Criteria) this;
        }

        public Criteria andFdzdateGreaterThan(Date value) {
            addCriterion("FDZDate >", value, "fdzdate");
            return (Criteria) this;
        }

        public Criteria andFdzdateGreaterThanOrEqualTo(Date value) {
            addCriterion("FDZDate >=", value, "fdzdate");
            return (Criteria) this;
        }

        public Criteria andFdzdateLessThan(Date value) {
            addCriterion("FDZDate <", value, "fdzdate");
            return (Criteria) this;
        }

        public Criteria andFdzdateLessThanOrEqualTo(Date value) {
            addCriterion("FDZDate <=", value, "fdzdate");
            return (Criteria) this;
        }

        public Criteria andFdzdateIn(List<Date> values) {
            addCriterion("FDZDate in", values, "fdzdate");
            return (Criteria) this;
        }

        public Criteria andFdzdateNotIn(List<Date> values) {
            addCriterion("FDZDate not in", values, "fdzdate");
            return (Criteria) this;
        }

        public Criteria andFdzdateBetween(Date value1, Date value2) {
            addCriterion("FDZDate between", value1, value2, "fdzdate");
            return (Criteria) this;
        }

        public Criteria andFdzdateNotBetween(Date value1, Date value2) {
            addCriterion("FDZDate not between", value1, value2, "fdzdate");
            return (Criteria) this;
        }

        public Criteria andFsxamtIsNull() {
            addCriterion("FSXAmt is null");
            return (Criteria) this;
        }

        public Criteria andFsxamtIsNotNull() {
            addCriterion("FSXAmt is not null");
            return (Criteria) this;
        }

        public Criteria andFsxamtEqualTo(BigDecimal value) {
            addCriterion("FSXAmt =", value, "fsxamt");
            return (Criteria) this;
        }

        public Criteria andFsxamtNotEqualTo(BigDecimal value) {
            addCriterion("FSXAmt <>", value, "fsxamt");
            return (Criteria) this;
        }

        public Criteria andFsxamtGreaterThan(BigDecimal value) {
            addCriterion("FSXAmt >", value, "fsxamt");
            return (Criteria) this;
        }

        public Criteria andFsxamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FSXAmt >=", value, "fsxamt");
            return (Criteria) this;
        }

        public Criteria andFsxamtLessThan(BigDecimal value) {
            addCriterion("FSXAmt <", value, "fsxamt");
            return (Criteria) this;
        }

        public Criteria andFsxamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FSXAmt <=", value, "fsxamt");
            return (Criteria) this;
        }

        public Criteria andFsxamtIn(List<BigDecimal> values) {
            addCriterion("FSXAmt in", values, "fsxamt");
            return (Criteria) this;
        }

        public Criteria andFsxamtNotIn(List<BigDecimal> values) {
            addCriterion("FSXAmt not in", values, "fsxamt");
            return (Criteria) this;
        }

        public Criteria andFsxamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FSXAmt between", value1, value2, "fsxamt");
            return (Criteria) this;
        }

        public Criteria andFsxamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FSXAmt not between", value1, value2, "fsxamt");
            return (Criteria) this;
        }

        public Criteria andFsumfkamtIsNull() {
            addCriterion("FSumFKAmt is null");
            return (Criteria) this;
        }

        public Criteria andFsumfkamtIsNotNull() {
            addCriterion("FSumFKAmt is not null");
            return (Criteria) this;
        }

        public Criteria andFsumfkamtEqualTo(BigDecimal value) {
            addCriterion("FSumFKAmt =", value, "fsumfkamt");
            return (Criteria) this;
        }

        public Criteria andFsumfkamtNotEqualTo(BigDecimal value) {
            addCriterion("FSumFKAmt <>", value, "fsumfkamt");
            return (Criteria) this;
        }

        public Criteria andFsumfkamtGreaterThan(BigDecimal value) {
            addCriterion("FSumFKAmt >", value, "fsumfkamt");
            return (Criteria) this;
        }

        public Criteria andFsumfkamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FSumFKAmt >=", value, "fsumfkamt");
            return (Criteria) this;
        }

        public Criteria andFsumfkamtLessThan(BigDecimal value) {
            addCriterion("FSumFKAmt <", value, "fsumfkamt");
            return (Criteria) this;
        }

        public Criteria andFsumfkamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FSumFKAmt <=", value, "fsumfkamt");
            return (Criteria) this;
        }

        public Criteria andFsumfkamtIn(List<BigDecimal> values) {
            addCriterion("FSumFKAmt in", values, "fsumfkamt");
            return (Criteria) this;
        }

        public Criteria andFsumfkamtNotIn(List<BigDecimal> values) {
            addCriterion("FSumFKAmt not in", values, "fsumfkamt");
            return (Criteria) this;
        }

        public Criteria andFsumfkamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FSumFKAmt between", value1, value2, "fsumfkamt");
            return (Criteria) this;
        }

        public Criteria andFsumfkamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FSumFKAmt not between", value1, value2, "fsumfkamt");
            return (Criteria) this;
        }

        public Criteria andFdebiteridIsNull() {
            addCriterion("FDebiterID is null");
            return (Criteria) this;
        }

        public Criteria andFdebiteridIsNotNull() {
            addCriterion("FDebiterID is not null");
            return (Criteria) this;
        }

        public Criteria andFdebiteridEqualTo(Integer value) {
            addCriterion("FDebiterID =", value, "fdebiterid");
            return (Criteria) this;
        }

        public Criteria andFdebiteridNotEqualTo(Integer value) {
            addCriterion("FDebiterID <>", value, "fdebiterid");
            return (Criteria) this;
        }

        public Criteria andFdebiteridGreaterThan(Integer value) {
            addCriterion("FDebiterID >", value, "fdebiterid");
            return (Criteria) this;
        }

        public Criteria andFdebiteridGreaterThanOrEqualTo(Integer value) {
            addCriterion("FDebiterID >=", value, "fdebiterid");
            return (Criteria) this;
        }

        public Criteria andFdebiteridLessThan(Integer value) {
            addCriterion("FDebiterID <", value, "fdebiterid");
            return (Criteria) this;
        }

        public Criteria andFdebiteridLessThanOrEqualTo(Integer value) {
            addCriterion("FDebiterID <=", value, "fdebiterid");
            return (Criteria) this;
        }

        public Criteria andFdebiteridIn(List<Integer> values) {
            addCriterion("FDebiterID in", values, "fdebiterid");
            return (Criteria) this;
        }

        public Criteria andFdebiteridNotIn(List<Integer> values) {
            addCriterion("FDebiterID not in", values, "fdebiterid");
            return (Criteria) this;
        }

        public Criteria andFdebiteridBetween(Integer value1, Integer value2) {
            addCriterion("FDebiterID between", value1, value2, "fdebiterid");
            return (Criteria) this;
        }

        public Criteria andFdebiteridNotBetween(Integer value1, Integer value2) {
            addCriterion("FDebiterID not between", value1, value2, "fdebiterid");
            return (Criteria) this;
        }

        public Criteria andFcheckerid3IsNull() {
            addCriterion("FCheckerID3 is null");
            return (Criteria) this;
        }

        public Criteria andFcheckerid3IsNotNull() {
            addCriterion("FCheckerID3 is not null");
            return (Criteria) this;
        }

        public Criteria andFcheckerid3EqualTo(Integer value) {
            addCriterion("FCheckerID3 =", value, "fcheckerid3");
            return (Criteria) this;
        }

        public Criteria andFcheckerid3NotEqualTo(Integer value) {
            addCriterion("FCheckerID3 <>", value, "fcheckerid3");
            return (Criteria) this;
        }

        public Criteria andFcheckerid3GreaterThan(Integer value) {
            addCriterion("FCheckerID3 >", value, "fcheckerid3");
            return (Criteria) this;
        }

        public Criteria andFcheckerid3GreaterThanOrEqualTo(Integer value) {
            addCriterion("FCheckerID3 >=", value, "fcheckerid3");
            return (Criteria) this;
        }

        public Criteria andFcheckerid3LessThan(Integer value) {
            addCriterion("FCheckerID3 <", value, "fcheckerid3");
            return (Criteria) this;
        }

        public Criteria andFcheckerid3LessThanOrEqualTo(Integer value) {
            addCriterion("FCheckerID3 <=", value, "fcheckerid3");
            return (Criteria) this;
        }

        public Criteria andFcheckerid3In(List<Integer> values) {
            addCriterion("FCheckerID3 in", values, "fcheckerid3");
            return (Criteria) this;
        }

        public Criteria andFcheckerid3NotIn(List<Integer> values) {
            addCriterion("FCheckerID3 not in", values, "fcheckerid3");
            return (Criteria) this;
        }

        public Criteria andFcheckerid3Between(Integer value1, Integer value2) {
            addCriterion("FCheckerID3 between", value1, value2, "fcheckerid3");
            return (Criteria) this;
        }

        public Criteria andFcheckerid3NotBetween(Integer value1, Integer value2) {
            addCriterion("FCheckerID3 not between", value1, value2, "fcheckerid3");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate3IsNull() {
            addCriterion("FCheckerDate3 is null");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate3IsNotNull() {
            addCriterion("FCheckerDate3 is not null");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate3EqualTo(Date value) {
            addCriterion("FCheckerDate3 =", value, "fcheckerdate3");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate3NotEqualTo(Date value) {
            addCriterion("FCheckerDate3 <>", value, "fcheckerdate3");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate3GreaterThan(Date value) {
            addCriterion("FCheckerDate3 >", value, "fcheckerdate3");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate3GreaterThanOrEqualTo(Date value) {
            addCriterion("FCheckerDate3 >=", value, "fcheckerdate3");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate3LessThan(Date value) {
            addCriterion("FCheckerDate3 <", value, "fcheckerdate3");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate3LessThanOrEqualTo(Date value) {
            addCriterion("FCheckerDate3 <=", value, "fcheckerdate3");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate3In(List<Date> values) {
            addCriterion("FCheckerDate3 in", values, "fcheckerdate3");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate3NotIn(List<Date> values) {
            addCriterion("FCheckerDate3 not in", values, "fcheckerdate3");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate3Between(Date value1, Date value2) {
            addCriterion("FCheckerDate3 between", value1, value2, "fcheckerdate3");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate3NotBetween(Date value1, Date value2) {
            addCriterion("FCheckerDate3 not between", value1, value2, "fcheckerdate3");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4IsNull() {
            addCriterion("FCheckerID4 is null");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4IsNotNull() {
            addCriterion("FCheckerID4 is not null");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4EqualTo(Integer value) {
            addCriterion("FCheckerID4 =", value, "fcheckerid4");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4NotEqualTo(Integer value) {
            addCriterion("FCheckerID4 <>", value, "fcheckerid4");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4GreaterThan(Integer value) {
            addCriterion("FCheckerID4 >", value, "fcheckerid4");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4GreaterThanOrEqualTo(Integer value) {
            addCriterion("FCheckerID4 >=", value, "fcheckerid4");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4LessThan(Integer value) {
            addCriterion("FCheckerID4 <", value, "fcheckerid4");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4LessThanOrEqualTo(Integer value) {
            addCriterion("FCheckerID4 <=", value, "fcheckerid4");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4In(List<Integer> values) {
            addCriterion("FCheckerID4 in", values, "fcheckerid4");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4NotIn(List<Integer> values) {
            addCriterion("FCheckerID4 not in", values, "fcheckerid4");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4Between(Integer value1, Integer value2) {
            addCriterion("FCheckerID4 between", value1, value2, "fcheckerid4");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4NotBetween(Integer value1, Integer value2) {
            addCriterion("FCheckerID4 not between", value1, value2, "fcheckerid4");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4FnameIsNull() {
            addCriterion("FCheckerID4_FName is null");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4FnameIsNotNull() {
            addCriterion("FCheckerID4_FName is not null");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4FnameEqualTo(String value) {
            addCriterion("FCheckerID4_FName =", value, "fcheckerid4Fname");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4FnameNotEqualTo(String value) {
            addCriterion("FCheckerID4_FName <>", value, "fcheckerid4Fname");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4FnameGreaterThan(String value) {
            addCriterion("FCheckerID4_FName >", value, "fcheckerid4Fname");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4FnameGreaterThanOrEqualTo(String value) {
            addCriterion("FCheckerID4_FName >=", value, "fcheckerid4Fname");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4FnameLessThan(String value) {
            addCriterion("FCheckerID4_FName <", value, "fcheckerid4Fname");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4FnameLessThanOrEqualTo(String value) {
            addCriterion("FCheckerID4_FName <=", value, "fcheckerid4Fname");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4FnameLike(String value) {
            addCriterion("FCheckerID4_FName like", value, "fcheckerid4Fname");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4FnameNotLike(String value) {
            addCriterion("FCheckerID4_FName not like", value, "fcheckerid4Fname");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4FnameIn(List<String> values) {
            addCriterion("FCheckerID4_FName in", values, "fcheckerid4Fname");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4FnameNotIn(List<String> values) {
            addCriterion("FCheckerID4_FName not in", values, "fcheckerid4Fname");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4FnameBetween(String value1, String value2) {
            addCriterion("FCheckerID4_FName between", value1, value2, "fcheckerid4Fname");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4FnameNotBetween(String value1, String value2) {
            addCriterion("FCheckerID4_FName not between", value1, value2, "fcheckerid4Fname");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate4IsNull() {
            addCriterion("FCheckerDate4 is null");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate4IsNotNull() {
            addCriterion("FCheckerDate4 is not null");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate4EqualTo(Date value) {
            addCriterion("FCheckerDate4 =", value, "fcheckerdate4");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate4NotEqualTo(Date value) {
            addCriterion("FCheckerDate4 <>", value, "fcheckerdate4");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate4GreaterThan(Date value) {
            addCriterion("FCheckerDate4 >", value, "fcheckerdate4");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate4GreaterThanOrEqualTo(Date value) {
            addCriterion("FCheckerDate4 >=", value, "fcheckerdate4");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate4LessThan(Date value) {
            addCriterion("FCheckerDate4 <", value, "fcheckerdate4");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate4LessThanOrEqualTo(Date value) {
            addCriterion("FCheckerDate4 <=", value, "fcheckerdate4");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate4In(List<Date> values) {
            addCriterion("FCheckerDate4 in", values, "fcheckerdate4");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate4NotIn(List<Date> values) {
            addCriterion("FCheckerDate4 not in", values, "fcheckerdate4");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate4Between(Date value1, Date value2) {
            addCriterion("FCheckerDate4 between", value1, value2, "fcheckerdate4");
            return (Criteria) this;
        }

        public Criteria andFcheckerdate4NotBetween(Date value1, Date value2) {
            addCriterion("FCheckerDate4 not between", value1, value2, "fcheckerdate4");
            return (Criteria) this;
        }

        public Criteria andFbankrevdateIsNull() {
            addCriterion("FBankRevDate is null");
            return (Criteria) this;
        }

        public Criteria andFbankrevdateIsNotNull() {
            addCriterion("FBankRevDate is not null");
            return (Criteria) this;
        }

        public Criteria andFbankrevdateEqualTo(Date value) {
            addCriterion("FBankRevDate =", value, "fbankrevdate");
            return (Criteria) this;
        }

        public Criteria andFbankrevdateNotEqualTo(Date value) {
            addCriterion("FBankRevDate <>", value, "fbankrevdate");
            return (Criteria) this;
        }

        public Criteria andFbankrevdateGreaterThan(Date value) {
            addCriterion("FBankRevDate >", value, "fbankrevdate");
            return (Criteria) this;
        }

        public Criteria andFbankrevdateGreaterThanOrEqualTo(Date value) {
            addCriterion("FBankRevDate >=", value, "fbankrevdate");
            return (Criteria) this;
        }

        public Criteria andFbankrevdateLessThan(Date value) {
            addCriterion("FBankRevDate <", value, "fbankrevdate");
            return (Criteria) this;
        }

        public Criteria andFbankrevdateLessThanOrEqualTo(Date value) {
            addCriterion("FBankRevDate <=", value, "fbankrevdate");
            return (Criteria) this;
        }

        public Criteria andFbankrevdateIn(List<Date> values) {
            addCriterion("FBankRevDate in", values, "fbankrevdate");
            return (Criteria) this;
        }

        public Criteria andFbankrevdateNotIn(List<Date> values) {
            addCriterion("FBankRevDate not in", values, "fbankrevdate");
            return (Criteria) this;
        }

        public Criteria andFbankrevdateBetween(Date value1, Date value2) {
            addCriterion("FBankRevDate between", value1, value2, "fbankrevdate");
            return (Criteria) this;
        }

        public Criteria andFbankrevdateNotBetween(Date value1, Date value2) {
            addCriterion("FBankRevDate not between", value1, value2, "fbankrevdate");
            return (Criteria) this;
        }

        public Criteria andFvhostIsNull() {
            addCriterion("FVHost is null");
            return (Criteria) this;
        }

        public Criteria andFvhostIsNotNull() {
            addCriterion("FVHost is not null");
            return (Criteria) this;
        }

        public Criteria andFvhostEqualTo(String value) {
            addCriterion("FVHost =", value, "fvhost");
            return (Criteria) this;
        }

        public Criteria andFvhostNotEqualTo(String value) {
            addCriterion("FVHost <>", value, "fvhost");
            return (Criteria) this;
        }

        public Criteria andFvhostGreaterThan(String value) {
            addCriterion("FVHost >", value, "fvhost");
            return (Criteria) this;
        }

        public Criteria andFvhostGreaterThanOrEqualTo(String value) {
            addCriterion("FVHost >=", value, "fvhost");
            return (Criteria) this;
        }

        public Criteria andFvhostLessThan(String value) {
            addCriterion("FVHost <", value, "fvhost");
            return (Criteria) this;
        }

        public Criteria andFvhostLessThanOrEqualTo(String value) {
            addCriterion("FVHost <=", value, "fvhost");
            return (Criteria) this;
        }

        public Criteria andFvhostLike(String value) {
            addCriterion("FVHost like", value, "fvhost");
            return (Criteria) this;
        }

        public Criteria andFvhostNotLike(String value) {
            addCriterion("FVHost not like", value, "fvhost");
            return (Criteria) this;
        }

        public Criteria andFvhostIn(List<String> values) {
            addCriterion("FVHost in", values, "fvhost");
            return (Criteria) this;
        }

        public Criteria andFvhostNotIn(List<String> values) {
            addCriterion("FVHost not in", values, "fvhost");
            return (Criteria) this;
        }

        public Criteria andFvhostBetween(String value1, String value2) {
            addCriterion("FVHost between", value1, value2, "fvhost");
            return (Criteria) this;
        }

        public Criteria andFvhostNotBetween(String value1, String value2) {
            addCriterion("FVHost not between", value1, value2, "fvhost");
            return (Criteria) this;
        }

        public Criteria andFstatusLikeInsensitive(String value) {
            addCriterion("upper(FStatus) like", value.toUpperCase(), "fstatus");
            return (Criteria) this;
        }

        public Criteria andFbillnoLikeInsensitive(String value) {
            addCriterion("upper(FBillNo) like", value.toUpperCase(), "fbillno");
            return (Criteria) this;
        }

        public Criteria andFcustidLikeInsensitive(String value) {
            addCriterion("upper(FCustID) like", value.toUpperCase(), "fcustid");
            return (Criteria) this;
        }

        public Criteria andFcustidFnameLikeInsensitive(String value) {
            addCriterion("upper(FCustID_FName) like", value.toUpperCase(), "fcustidFname");
            return (Criteria) this;
        }

        public Criteria andFdeptidFnameLikeInsensitive(String value) {
            addCriterion("upper(FDeptID_FName) like", value.toUpperCase(), "fdeptidFname");
            return (Criteria) this;
        }

        public Criteria andFcustidfnameLikeInsensitive(String value) {
            addCriterion("upper(FCustIDFName) like", value.toUpperCase(), "fcustidfname");
            return (Criteria) this;
        }

        public Criteria andFnoteLikeInsensitive(String value) {
            addCriterion("upper(FNote) like", value.toUpperCase(), "fnote");
            return (Criteria) this;
        }

        public Criteria andFcheckerid4FnameLikeInsensitive(String value) {
            addCriterion("upper(FCheckerID4_FName) like", value.toUpperCase(), "fcheckerid4Fname");
            return (Criteria) this;
        }

        public Criteria andFvhostLikeInsensitive(String value) {
            addCriterion("upper(FVHost) like", value.toUpperCase(), "fvhost");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}