package com.hongte.weixin.mybatis.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class XdDkdetailtobank implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FID
     *
     * @mbggenerated
     */
    private Integer fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FStatus
     *
     * @mbggenerated
     */
    private String fstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FBillNo
     *
     * @mbggenerated
     */
    private String fbillno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FCustID
     *
     * @mbggenerated
     */
    private String fcustid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FCustID_FName
     *
     * @mbggenerated
     */
    private String fcustidFname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FDeptID
     *
     * @mbggenerated
     */
    private Integer fdeptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FDeptID_FName
     *
     * @mbggenerated
     */
    private String fdeptidFname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FVBankID
     *
     * @mbggenerated
     */
    private Integer fvbankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FVType
     *
     * @mbggenerated
     */
    private Integer fvtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FVPeriod
     *
     * @mbggenerated
     */
    private BigDecimal fvperiod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FVDebitAmt
     *
     * @mbggenerated
     */
    private BigDecimal fvdebitamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FReceiveDate
     *
     * @mbggenerated
     */
    private Date freceivedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FAllDate
     *
     * @mbggenerated
     */
    private Date falldate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FSendDate
     *
     * @mbggenerated
     */
    private Date fsenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FBillerID
     *
     * @mbggenerated
     */
    private Integer fbillerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FBillerDate
     *
     * @mbggenerated
     */
    private Date fbillerdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FCheckerID
     *
     * @mbggenerated
     */
    private Integer fcheckerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FCheckerDate
     *
     * @mbggenerated
     */
    private Date fcheckerdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FCustIDFName
     *
     * @mbggenerated
     */
    private String fcustidfname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FNote
     *
     * @mbggenerated
     */
    private String fnote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FRate
     *
     * @mbggenerated
     */
    private BigDecimal frate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FStandard
     *
     * @mbggenerated
     */
    private BigDecimal fstandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FCheckerID2
     *
     * @mbggenerated
     */
    private Integer fcheckerid2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FCheckerDate2
     *
     * @mbggenerated
     */
    private Date fcheckerdate2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FVPrice
     *
     * @mbggenerated
     */
    private BigDecimal fvprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FDZDate
     *
     * @mbggenerated
     */
    private Date fdzdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FSXAmt
     *
     * @mbggenerated
     */
    private BigDecimal fsxamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FSumFKAmt
     *
     * @mbggenerated
     */
    private BigDecimal fsumfkamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FDebiterID
     *
     * @mbggenerated
     */
    private Integer fdebiterid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FCheckerID3
     *
     * @mbggenerated
     */
    private Integer fcheckerid3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FCheckerDate3
     *
     * @mbggenerated
     */
    private Date fcheckerdate3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FCheckerID4
     *
     * @mbggenerated
     */
    private Integer fcheckerid4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FCheckerID4_FName
     *
     * @mbggenerated
     */
    private String fcheckerid4Fname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FCheckerDate4
     *
     * @mbggenerated
     */
    private Date fcheckerdate4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FBankRevDate
     *
     * @mbggenerated
     */
    private Date fbankrevdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_DKDetailToBank.FVHost
     *
     * @mbggenerated
     */
    private String fvhost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FID
     *
     * @return the value of dbo.XD_DKDetailToBank.FID
     *
     * @mbggenerated
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FID
     *
     * @param fid the value for dbo.XD_DKDetailToBank.FID
     *
     * @mbggenerated
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FStatus
     *
     * @return the value of dbo.XD_DKDetailToBank.FStatus
     *
     * @mbggenerated
     */
    public String getFstatus() {
        return fstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FStatus
     *
     * @param fstatus the value for dbo.XD_DKDetailToBank.FStatus
     *
     * @mbggenerated
     */
    public void setFstatus(String fstatus) {
        this.fstatus = fstatus == null ? null : fstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FBillNo
     *
     * @return the value of dbo.XD_DKDetailToBank.FBillNo
     *
     * @mbggenerated
     */
    public String getFbillno() {
        return fbillno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FBillNo
     *
     * @param fbillno the value for dbo.XD_DKDetailToBank.FBillNo
     *
     * @mbggenerated
     */
    public void setFbillno(String fbillno) {
        this.fbillno = fbillno == null ? null : fbillno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FCustID
     *
     * @return the value of dbo.XD_DKDetailToBank.FCustID
     *
     * @mbggenerated
     */
    public String getFcustid() {
        return fcustid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FCustID
     *
     * @param fcustid the value for dbo.XD_DKDetailToBank.FCustID
     *
     * @mbggenerated
     */
    public void setFcustid(String fcustid) {
        this.fcustid = fcustid == null ? null : fcustid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FCustID_FName
     *
     * @return the value of dbo.XD_DKDetailToBank.FCustID_FName
     *
     * @mbggenerated
     */
    public String getFcustidFname() {
        return fcustidFname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FCustID_FName
     *
     * @param fcustidFname the value for dbo.XD_DKDetailToBank.FCustID_FName
     *
     * @mbggenerated
     */
    public void setFcustidFname(String fcustidFname) {
        this.fcustidFname = fcustidFname == null ? null : fcustidFname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FDeptID
     *
     * @return the value of dbo.XD_DKDetailToBank.FDeptID
     *
     * @mbggenerated
     */
    public Integer getFdeptid() {
        return fdeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FDeptID
     *
     * @param fdeptid the value for dbo.XD_DKDetailToBank.FDeptID
     *
     * @mbggenerated
     */
    public void setFdeptid(Integer fdeptid) {
        this.fdeptid = fdeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FDeptID_FName
     *
     * @return the value of dbo.XD_DKDetailToBank.FDeptID_FName
     *
     * @mbggenerated
     */
    public String getFdeptidFname() {
        return fdeptidFname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FDeptID_FName
     *
     * @param fdeptidFname the value for dbo.XD_DKDetailToBank.FDeptID_FName
     *
     * @mbggenerated
     */
    public void setFdeptidFname(String fdeptidFname) {
        this.fdeptidFname = fdeptidFname == null ? null : fdeptidFname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FVBankID
     *
     * @return the value of dbo.XD_DKDetailToBank.FVBankID
     *
     * @mbggenerated
     */
    public Integer getFvbankid() {
        return fvbankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FVBankID
     *
     * @param fvbankid the value for dbo.XD_DKDetailToBank.FVBankID
     *
     * @mbggenerated
     */
    public void setFvbankid(Integer fvbankid) {
        this.fvbankid = fvbankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FVType
     *
     * @return the value of dbo.XD_DKDetailToBank.FVType
     *
     * @mbggenerated
     */
    public Integer getFvtype() {
        return fvtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FVType
     *
     * @param fvtype the value for dbo.XD_DKDetailToBank.FVType
     *
     * @mbggenerated
     */
    public void setFvtype(Integer fvtype) {
        this.fvtype = fvtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FVPeriod
     *
     * @return the value of dbo.XD_DKDetailToBank.FVPeriod
     *
     * @mbggenerated
     */
    public BigDecimal getFvperiod() {
        return fvperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FVPeriod
     *
     * @param fvperiod the value for dbo.XD_DKDetailToBank.FVPeriod
     *
     * @mbggenerated
     */
    public void setFvperiod(BigDecimal fvperiod) {
        this.fvperiod = fvperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FVDebitAmt
     *
     * @return the value of dbo.XD_DKDetailToBank.FVDebitAmt
     *
     * @mbggenerated
     */
    public BigDecimal getFvdebitamt() {
        return fvdebitamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FVDebitAmt
     *
     * @param fvdebitamt the value for dbo.XD_DKDetailToBank.FVDebitAmt
     *
     * @mbggenerated
     */
    public void setFvdebitamt(BigDecimal fvdebitamt) {
        this.fvdebitamt = fvdebitamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FReceiveDate
     *
     * @return the value of dbo.XD_DKDetailToBank.FReceiveDate
     *
     * @mbggenerated
     */
    public Date getFreceivedate() {
        return freceivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FReceiveDate
     *
     * @param freceivedate the value for dbo.XD_DKDetailToBank.FReceiveDate
     *
     * @mbggenerated
     */
    public void setFreceivedate(Date freceivedate) {
        this.freceivedate = freceivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FAllDate
     *
     * @return the value of dbo.XD_DKDetailToBank.FAllDate
     *
     * @mbggenerated
     */
    public Date getFalldate() {
        return falldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FAllDate
     *
     * @param falldate the value for dbo.XD_DKDetailToBank.FAllDate
     *
     * @mbggenerated
     */
    public void setFalldate(Date falldate) {
        this.falldate = falldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FSendDate
     *
     * @return the value of dbo.XD_DKDetailToBank.FSendDate
     *
     * @mbggenerated
     */
    public Date getFsenddate() {
        return fsenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FSendDate
     *
     * @param fsenddate the value for dbo.XD_DKDetailToBank.FSendDate
     *
     * @mbggenerated
     */
    public void setFsenddate(Date fsenddate) {
        this.fsenddate = fsenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FBillerID
     *
     * @return the value of dbo.XD_DKDetailToBank.FBillerID
     *
     * @mbggenerated
     */
    public Integer getFbillerid() {
        return fbillerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FBillerID
     *
     * @param fbillerid the value for dbo.XD_DKDetailToBank.FBillerID
     *
     * @mbggenerated
     */
    public void setFbillerid(Integer fbillerid) {
        this.fbillerid = fbillerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FBillerDate
     *
     * @return the value of dbo.XD_DKDetailToBank.FBillerDate
     *
     * @mbggenerated
     */
    public Date getFbillerdate() {
        return fbillerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FBillerDate
     *
     * @param fbillerdate the value for dbo.XD_DKDetailToBank.FBillerDate
     *
     * @mbggenerated
     */
    public void setFbillerdate(Date fbillerdate) {
        this.fbillerdate = fbillerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FCheckerID
     *
     * @return the value of dbo.XD_DKDetailToBank.FCheckerID
     *
     * @mbggenerated
     */
    public Integer getFcheckerid() {
        return fcheckerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FCheckerID
     *
     * @param fcheckerid the value for dbo.XD_DKDetailToBank.FCheckerID
     *
     * @mbggenerated
     */
    public void setFcheckerid(Integer fcheckerid) {
        this.fcheckerid = fcheckerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FCheckerDate
     *
     * @return the value of dbo.XD_DKDetailToBank.FCheckerDate
     *
     * @mbggenerated
     */
    public Date getFcheckerdate() {
        return fcheckerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FCheckerDate
     *
     * @param fcheckerdate the value for dbo.XD_DKDetailToBank.FCheckerDate
     *
     * @mbggenerated
     */
    public void setFcheckerdate(Date fcheckerdate) {
        this.fcheckerdate = fcheckerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FCustIDFName
     *
     * @return the value of dbo.XD_DKDetailToBank.FCustIDFName
     *
     * @mbggenerated
     */
    public String getFcustidfname() {
        return fcustidfname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FCustIDFName
     *
     * @param fcustidfname the value for dbo.XD_DKDetailToBank.FCustIDFName
     *
     * @mbggenerated
     */
    public void setFcustidfname(String fcustidfname) {
        this.fcustidfname = fcustidfname == null ? null : fcustidfname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FNote
     *
     * @return the value of dbo.XD_DKDetailToBank.FNote
     *
     * @mbggenerated
     */
    public String getFnote() {
        return fnote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FNote
     *
     * @param fnote the value for dbo.XD_DKDetailToBank.FNote
     *
     * @mbggenerated
     */
    public void setFnote(String fnote) {
        this.fnote = fnote == null ? null : fnote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FRate
     *
     * @return the value of dbo.XD_DKDetailToBank.FRate
     *
     * @mbggenerated
     */
    public BigDecimal getFrate() {
        return frate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FRate
     *
     * @param frate the value for dbo.XD_DKDetailToBank.FRate
     *
     * @mbggenerated
     */
    public void setFrate(BigDecimal frate) {
        this.frate = frate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FStandard
     *
     * @return the value of dbo.XD_DKDetailToBank.FStandard
     *
     * @mbggenerated
     */
    public BigDecimal getFstandard() {
        return fstandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FStandard
     *
     * @param fstandard the value for dbo.XD_DKDetailToBank.FStandard
     *
     * @mbggenerated
     */
    public void setFstandard(BigDecimal fstandard) {
        this.fstandard = fstandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FCheckerID2
     *
     * @return the value of dbo.XD_DKDetailToBank.FCheckerID2
     *
     * @mbggenerated
     */
    public Integer getFcheckerid2() {
        return fcheckerid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FCheckerID2
     *
     * @param fcheckerid2 the value for dbo.XD_DKDetailToBank.FCheckerID2
     *
     * @mbggenerated
     */
    public void setFcheckerid2(Integer fcheckerid2) {
        this.fcheckerid2 = fcheckerid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FCheckerDate2
     *
     * @return the value of dbo.XD_DKDetailToBank.FCheckerDate2
     *
     * @mbggenerated
     */
    public Date getFcheckerdate2() {
        return fcheckerdate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FCheckerDate2
     *
     * @param fcheckerdate2 the value for dbo.XD_DKDetailToBank.FCheckerDate2
     *
     * @mbggenerated
     */
    public void setFcheckerdate2(Date fcheckerdate2) {
        this.fcheckerdate2 = fcheckerdate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FVPrice
     *
     * @return the value of dbo.XD_DKDetailToBank.FVPrice
     *
     * @mbggenerated
     */
    public BigDecimal getFvprice() {
        return fvprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FVPrice
     *
     * @param fvprice the value for dbo.XD_DKDetailToBank.FVPrice
     *
     * @mbggenerated
     */
    public void setFvprice(BigDecimal fvprice) {
        this.fvprice = fvprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FDZDate
     *
     * @return the value of dbo.XD_DKDetailToBank.FDZDate
     *
     * @mbggenerated
     */
    public Date getFdzdate() {
        return fdzdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FDZDate
     *
     * @param fdzdate the value for dbo.XD_DKDetailToBank.FDZDate
     *
     * @mbggenerated
     */
    public void setFdzdate(Date fdzdate) {
        this.fdzdate = fdzdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FSXAmt
     *
     * @return the value of dbo.XD_DKDetailToBank.FSXAmt
     *
     * @mbggenerated
     */
    public BigDecimal getFsxamt() {
        return fsxamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FSXAmt
     *
     * @param fsxamt the value for dbo.XD_DKDetailToBank.FSXAmt
     *
     * @mbggenerated
     */
    public void setFsxamt(BigDecimal fsxamt) {
        this.fsxamt = fsxamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FSumFKAmt
     *
     * @return the value of dbo.XD_DKDetailToBank.FSumFKAmt
     *
     * @mbggenerated
     */
    public BigDecimal getFsumfkamt() {
        return fsumfkamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FSumFKAmt
     *
     * @param fsumfkamt the value for dbo.XD_DKDetailToBank.FSumFKAmt
     *
     * @mbggenerated
     */
    public void setFsumfkamt(BigDecimal fsumfkamt) {
        this.fsumfkamt = fsumfkamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FDebiterID
     *
     * @return the value of dbo.XD_DKDetailToBank.FDebiterID
     *
     * @mbggenerated
     */
    public Integer getFdebiterid() {
        return fdebiterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FDebiterID
     *
     * @param fdebiterid the value for dbo.XD_DKDetailToBank.FDebiterID
     *
     * @mbggenerated
     */
    public void setFdebiterid(Integer fdebiterid) {
        this.fdebiterid = fdebiterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FCheckerID3
     *
     * @return the value of dbo.XD_DKDetailToBank.FCheckerID3
     *
     * @mbggenerated
     */
    public Integer getFcheckerid3() {
        return fcheckerid3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FCheckerID3
     *
     * @param fcheckerid3 the value for dbo.XD_DKDetailToBank.FCheckerID3
     *
     * @mbggenerated
     */
    public void setFcheckerid3(Integer fcheckerid3) {
        this.fcheckerid3 = fcheckerid3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FCheckerDate3
     *
     * @return the value of dbo.XD_DKDetailToBank.FCheckerDate3
     *
     * @mbggenerated
     */
    public Date getFcheckerdate3() {
        return fcheckerdate3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FCheckerDate3
     *
     * @param fcheckerdate3 the value for dbo.XD_DKDetailToBank.FCheckerDate3
     *
     * @mbggenerated
     */
    public void setFcheckerdate3(Date fcheckerdate3) {
        this.fcheckerdate3 = fcheckerdate3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FCheckerID4
     *
     * @return the value of dbo.XD_DKDetailToBank.FCheckerID4
     *
     * @mbggenerated
     */
    public Integer getFcheckerid4() {
        return fcheckerid4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FCheckerID4
     *
     * @param fcheckerid4 the value for dbo.XD_DKDetailToBank.FCheckerID4
     *
     * @mbggenerated
     */
    public void setFcheckerid4(Integer fcheckerid4) {
        this.fcheckerid4 = fcheckerid4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FCheckerID4_FName
     *
     * @return the value of dbo.XD_DKDetailToBank.FCheckerID4_FName
     *
     * @mbggenerated
     */
    public String getFcheckerid4Fname() {
        return fcheckerid4Fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FCheckerID4_FName
     *
     * @param fcheckerid4Fname the value for dbo.XD_DKDetailToBank.FCheckerID4_FName
     *
     * @mbggenerated
     */
    public void setFcheckerid4Fname(String fcheckerid4Fname) {
        this.fcheckerid4Fname = fcheckerid4Fname == null ? null : fcheckerid4Fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FCheckerDate4
     *
     * @return the value of dbo.XD_DKDetailToBank.FCheckerDate4
     *
     * @mbggenerated
     */
    public Date getFcheckerdate4() {
        return fcheckerdate4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FCheckerDate4
     *
     * @param fcheckerdate4 the value for dbo.XD_DKDetailToBank.FCheckerDate4
     *
     * @mbggenerated
     */
    public void setFcheckerdate4(Date fcheckerdate4) {
        this.fcheckerdate4 = fcheckerdate4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FBankRevDate
     *
     * @return the value of dbo.XD_DKDetailToBank.FBankRevDate
     *
     * @mbggenerated
     */
    public Date getFbankrevdate() {
        return fbankrevdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FBankRevDate
     *
     * @param fbankrevdate the value for dbo.XD_DKDetailToBank.FBankRevDate
     *
     * @mbggenerated
     */
    public void setFbankrevdate(Date fbankrevdate) {
        this.fbankrevdate = fbankrevdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_DKDetailToBank.FVHost
     *
     * @return the value of dbo.XD_DKDetailToBank.FVHost
     *
     * @mbggenerated
     */
    public String getFvhost() {
        return fvhost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_DKDetailToBank.FVHost
     *
     * @param fvhost the value for dbo.XD_DKDetailToBank.FVHost
     *
     * @mbggenerated
     */
    public void setFvhost(String fvhost) {
        this.fvhost = fvhost == null ? null : fvhost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        XdDkdetailtobank other = (XdDkdetailtobank) that;
        return (this.getFid() == null ? other.getFid() == null : this.getFid().equals(other.getFid()))
            && (this.getFstatus() == null ? other.getFstatus() == null : this.getFstatus().equals(other.getFstatus()))
            && (this.getFbillno() == null ? other.getFbillno() == null : this.getFbillno().equals(other.getFbillno()))
            && (this.getFcustid() == null ? other.getFcustid() == null : this.getFcustid().equals(other.getFcustid()))
            && (this.getFcustidFname() == null ? other.getFcustidFname() == null : this.getFcustidFname().equals(other.getFcustidFname()))
            && (this.getFdeptid() == null ? other.getFdeptid() == null : this.getFdeptid().equals(other.getFdeptid()))
            && (this.getFdeptidFname() == null ? other.getFdeptidFname() == null : this.getFdeptidFname().equals(other.getFdeptidFname()))
            && (this.getFvbankid() == null ? other.getFvbankid() == null : this.getFvbankid().equals(other.getFvbankid()))
            && (this.getFvtype() == null ? other.getFvtype() == null : this.getFvtype().equals(other.getFvtype()))
            && (this.getFvperiod() == null ? other.getFvperiod() == null : this.getFvperiod().equals(other.getFvperiod()))
            && (this.getFvdebitamt() == null ? other.getFvdebitamt() == null : this.getFvdebitamt().equals(other.getFvdebitamt()))
            && (this.getFreceivedate() == null ? other.getFreceivedate() == null : this.getFreceivedate().equals(other.getFreceivedate()))
            && (this.getFalldate() == null ? other.getFalldate() == null : this.getFalldate().equals(other.getFalldate()))
            && (this.getFsenddate() == null ? other.getFsenddate() == null : this.getFsenddate().equals(other.getFsenddate()))
            && (this.getFbillerid() == null ? other.getFbillerid() == null : this.getFbillerid().equals(other.getFbillerid()))
            && (this.getFbillerdate() == null ? other.getFbillerdate() == null : this.getFbillerdate().equals(other.getFbillerdate()))
            && (this.getFcheckerid() == null ? other.getFcheckerid() == null : this.getFcheckerid().equals(other.getFcheckerid()))
            && (this.getFcheckerdate() == null ? other.getFcheckerdate() == null : this.getFcheckerdate().equals(other.getFcheckerdate()))
            && (this.getFcustidfname() == null ? other.getFcustidfname() == null : this.getFcustidfname().equals(other.getFcustidfname()))
            && (this.getFnote() == null ? other.getFnote() == null : this.getFnote().equals(other.getFnote()))
            && (this.getFrate() == null ? other.getFrate() == null : this.getFrate().equals(other.getFrate()))
            && (this.getFstandard() == null ? other.getFstandard() == null : this.getFstandard().equals(other.getFstandard()))
            && (this.getFcheckerid2() == null ? other.getFcheckerid2() == null : this.getFcheckerid2().equals(other.getFcheckerid2()))
            && (this.getFcheckerdate2() == null ? other.getFcheckerdate2() == null : this.getFcheckerdate2().equals(other.getFcheckerdate2()))
            && (this.getFvprice() == null ? other.getFvprice() == null : this.getFvprice().equals(other.getFvprice()))
            && (this.getFdzdate() == null ? other.getFdzdate() == null : this.getFdzdate().equals(other.getFdzdate()))
            && (this.getFsxamt() == null ? other.getFsxamt() == null : this.getFsxamt().equals(other.getFsxamt()))
            && (this.getFsumfkamt() == null ? other.getFsumfkamt() == null : this.getFsumfkamt().equals(other.getFsumfkamt()))
            && (this.getFdebiterid() == null ? other.getFdebiterid() == null : this.getFdebiterid().equals(other.getFdebiterid()))
            && (this.getFcheckerid3() == null ? other.getFcheckerid3() == null : this.getFcheckerid3().equals(other.getFcheckerid3()))
            && (this.getFcheckerdate3() == null ? other.getFcheckerdate3() == null : this.getFcheckerdate3().equals(other.getFcheckerdate3()))
            && (this.getFcheckerid4() == null ? other.getFcheckerid4() == null : this.getFcheckerid4().equals(other.getFcheckerid4()))
            && (this.getFcheckerid4Fname() == null ? other.getFcheckerid4Fname() == null : this.getFcheckerid4Fname().equals(other.getFcheckerid4Fname()))
            && (this.getFcheckerdate4() == null ? other.getFcheckerdate4() == null : this.getFcheckerdate4().equals(other.getFcheckerdate4()))
            && (this.getFbankrevdate() == null ? other.getFbankrevdate() == null : this.getFbankrevdate().equals(other.getFbankrevdate()))
            && (this.getFvhost() == null ? other.getFvhost() == null : this.getFvhost().equals(other.getFvhost()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_DKDetailToBank
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFid() == null) ? 0 : getFid().hashCode());
        result = prime * result + ((getFstatus() == null) ? 0 : getFstatus().hashCode());
        result = prime * result + ((getFbillno() == null) ? 0 : getFbillno().hashCode());
        result = prime * result + ((getFcustid() == null) ? 0 : getFcustid().hashCode());
        result = prime * result + ((getFcustidFname() == null) ? 0 : getFcustidFname().hashCode());
        result = prime * result + ((getFdeptid() == null) ? 0 : getFdeptid().hashCode());
        result = prime * result + ((getFdeptidFname() == null) ? 0 : getFdeptidFname().hashCode());
        result = prime * result + ((getFvbankid() == null) ? 0 : getFvbankid().hashCode());
        result = prime * result + ((getFvtype() == null) ? 0 : getFvtype().hashCode());
        result = prime * result + ((getFvperiod() == null) ? 0 : getFvperiod().hashCode());
        result = prime * result + ((getFvdebitamt() == null) ? 0 : getFvdebitamt().hashCode());
        result = prime * result + ((getFreceivedate() == null) ? 0 : getFreceivedate().hashCode());
        result = prime * result + ((getFalldate() == null) ? 0 : getFalldate().hashCode());
        result = prime * result + ((getFsenddate() == null) ? 0 : getFsenddate().hashCode());
        result = prime * result + ((getFbillerid() == null) ? 0 : getFbillerid().hashCode());
        result = prime * result + ((getFbillerdate() == null) ? 0 : getFbillerdate().hashCode());
        result = prime * result + ((getFcheckerid() == null) ? 0 : getFcheckerid().hashCode());
        result = prime * result + ((getFcheckerdate() == null) ? 0 : getFcheckerdate().hashCode());
        result = prime * result + ((getFcustidfname() == null) ? 0 : getFcustidfname().hashCode());
        result = prime * result + ((getFnote() == null) ? 0 : getFnote().hashCode());
        result = prime * result + ((getFrate() == null) ? 0 : getFrate().hashCode());
        result = prime * result + ((getFstandard() == null) ? 0 : getFstandard().hashCode());
        result = prime * result + ((getFcheckerid2() == null) ? 0 : getFcheckerid2().hashCode());
        result = prime * result + ((getFcheckerdate2() == null) ? 0 : getFcheckerdate2().hashCode());
        result = prime * result + ((getFvprice() == null) ? 0 : getFvprice().hashCode());
        result = prime * result + ((getFdzdate() == null) ? 0 : getFdzdate().hashCode());
        result = prime * result + ((getFsxamt() == null) ? 0 : getFsxamt().hashCode());
        result = prime * result + ((getFsumfkamt() == null) ? 0 : getFsumfkamt().hashCode());
        result = prime * result + ((getFdebiterid() == null) ? 0 : getFdebiterid().hashCode());
        result = prime * result + ((getFcheckerid3() == null) ? 0 : getFcheckerid3().hashCode());
        result = prime * result + ((getFcheckerdate3() == null) ? 0 : getFcheckerdate3().hashCode());
        result = prime * result + ((getFcheckerid4() == null) ? 0 : getFcheckerid4().hashCode());
        result = prime * result + ((getFcheckerid4Fname() == null) ? 0 : getFcheckerid4Fname().hashCode());
        result = prime * result + ((getFcheckerdate4() == null) ? 0 : getFcheckerdate4().hashCode());
        result = prime * result + ((getFbankrevdate() == null) ? 0 : getFbankrevdate().hashCode());
        result = prime * result + ((getFvhost() == null) ? 0 : getFvhost().hashCode());
        return result;
    }
}