package com.hongte.weixin.mybatis.domain;

import java.io.Serializable;

public class XdKkdetailKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_KKDetail.FID
     *
     * @mbggenerated
     */
    private Integer fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_KKDetail.FEntryID
     *
     * @mbggenerated
     */
    private Integer fentryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.XD_KKDetail
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_KKDetail.FID
     *
     * @return the value of dbo.XD_KKDetail.FID
     *
     * @mbggenerated
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_KKDetail.FID
     *
     * @param fid the value for dbo.XD_KKDetail.FID
     *
     * @mbggenerated
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_KKDetail.FEntryID
     *
     * @return the value of dbo.XD_KKDetail.FEntryID
     *
     * @mbggenerated
     */
    public Integer getFentryid() {
        return fentryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_KKDetail.FEntryID
     *
     * @param fentryid the value for dbo.XD_KKDetail.FEntryID
     *
     * @mbggenerated
     */
    public void setFentryid(Integer fentryid) {
        this.fentryid = fentryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_KKDetail
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        XdKkdetailKey other = (XdKkdetailKey) that;
        return (this.getFid() == null ? other.getFid() == null : this.getFid().equals(other.getFid()))
            && (this.getFentryid() == null ? other.getFentryid() == null : this.getFentryid().equals(other.getFentryid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_KKDetail
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFid() == null) ? 0 : getFid().hashCode());
        result = prime * result + ((getFentryid() == null) ? 0 : getFentryid().hashCode());
        return result;
    }
}