package com.hongte.weixin.mybatis.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class XdKkdetail extends XdKkdetailKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_KKDetail.FPeriod
     *
     * @mbggenerated
     */
    private BigDecimal fperiod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_KKDetail.FDate
     *
     * @mbggenerated
     */
    private Date fdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_KKDetail.FPerRev
     *
     * @mbggenerated
     */
    private BigDecimal fperrev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_KKDetail.FPerRevNote
     *
     * @mbggenerated
     */
    private String fperrevnote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_KKDetail.FBenjin
     *
     * @mbggenerated
     */
    private BigDecimal fbenjin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_KKDetail.FLixi
     *
     * @mbggenerated
     */
    private BigDecimal flixi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_KKDetail.FActRev
     *
     * @mbggenerated
     */
    private BigDecimal factrev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_KKDetail.FAmtAll
     *
     * @mbggenerated
     */
    private BigDecimal famtall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_KKDetail.FOver
     *
     * @mbggenerated
     */
    private Boolean fover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_KKDetail.FOvered
     *
     * @mbggenerated
     */
    private Boolean fovered;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_KKDetail.FActDate
     *
     * @mbggenerated
     */
    private Date factdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_KKDetail.FPIndex
     *
     * @mbggenerated
     */
    private BigDecimal fpindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_KKDetail.FBankRate
     *
     * @mbggenerated
     */
    private BigDecimal fbankrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_KKDetail.FCust
     *
     * @mbggenerated
     */
    private BigDecimal fcust;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_KKDetail.FCustID
     *
     * @mbggenerated
     */
    private Integer fcustid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.XD_KKDetail.FECustName
     *
     * @mbggenerated
     */
    private String fecustname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.XD_KKDetail
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_KKDetail.FPeriod
     *
     * @return the value of dbo.XD_KKDetail.FPeriod
     *
     * @mbggenerated
     */
    public BigDecimal getFperiod() {
        return fperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_KKDetail.FPeriod
     *
     * @param fperiod the value for dbo.XD_KKDetail.FPeriod
     *
     * @mbggenerated
     */
    public void setFperiod(BigDecimal fperiod) {
        this.fperiod = fperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_KKDetail.FDate
     *
     * @return the value of dbo.XD_KKDetail.FDate
     *
     * @mbggenerated
     */
    public Date getFdate() {
        return fdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_KKDetail.FDate
     *
     * @param fdate the value for dbo.XD_KKDetail.FDate
     *
     * @mbggenerated
     */
    public void setFdate(Date fdate) {
        this.fdate = fdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_KKDetail.FPerRev
     *
     * @return the value of dbo.XD_KKDetail.FPerRev
     *
     * @mbggenerated
     */
    public BigDecimal getFperrev() {
        return fperrev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_KKDetail.FPerRev
     *
     * @param fperrev the value for dbo.XD_KKDetail.FPerRev
     *
     * @mbggenerated
     */
    public void setFperrev(BigDecimal fperrev) {
        this.fperrev = fperrev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_KKDetail.FPerRevNote
     *
     * @return the value of dbo.XD_KKDetail.FPerRevNote
     *
     * @mbggenerated
     */
    public String getFperrevnote() {
        return fperrevnote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_KKDetail.FPerRevNote
     *
     * @param fperrevnote the value for dbo.XD_KKDetail.FPerRevNote
     *
     * @mbggenerated
     */
    public void setFperrevnote(String fperrevnote) {
        this.fperrevnote = fperrevnote == null ? null : fperrevnote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_KKDetail.FBenjin
     *
     * @return the value of dbo.XD_KKDetail.FBenjin
     *
     * @mbggenerated
     */
    public BigDecimal getFbenjin() {
        return fbenjin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_KKDetail.FBenjin
     *
     * @param fbenjin the value for dbo.XD_KKDetail.FBenjin
     *
     * @mbggenerated
     */
    public void setFbenjin(BigDecimal fbenjin) {
        this.fbenjin = fbenjin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_KKDetail.FLixi
     *
     * @return the value of dbo.XD_KKDetail.FLixi
     *
     * @mbggenerated
     */
    public BigDecimal getFlixi() {
        return flixi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_KKDetail.FLixi
     *
     * @param flixi the value for dbo.XD_KKDetail.FLixi
     *
     * @mbggenerated
     */
    public void setFlixi(BigDecimal flixi) {
        this.flixi = flixi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_KKDetail.FActRev
     *
     * @return the value of dbo.XD_KKDetail.FActRev
     *
     * @mbggenerated
     */
    public BigDecimal getFactrev() {
        return factrev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_KKDetail.FActRev
     *
     * @param factrev the value for dbo.XD_KKDetail.FActRev
     *
     * @mbggenerated
     */
    public void setFactrev(BigDecimal factrev) {
        this.factrev = factrev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_KKDetail.FAmtAll
     *
     * @return the value of dbo.XD_KKDetail.FAmtAll
     *
     * @mbggenerated
     */
    public BigDecimal getFamtall() {
        return famtall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_KKDetail.FAmtAll
     *
     * @param famtall the value for dbo.XD_KKDetail.FAmtAll
     *
     * @mbggenerated
     */
    public void setFamtall(BigDecimal famtall) {
        this.famtall = famtall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_KKDetail.FOver
     *
     * @return the value of dbo.XD_KKDetail.FOver
     *
     * @mbggenerated
     */
    public Boolean getFover() {
        return fover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_KKDetail.FOver
     *
     * @param fover the value for dbo.XD_KKDetail.FOver
     *
     * @mbggenerated
     */
    public void setFover(Boolean fover) {
        this.fover = fover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_KKDetail.FOvered
     *
     * @return the value of dbo.XD_KKDetail.FOvered
     *
     * @mbggenerated
     */
    public Boolean getFovered() {
        return fovered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_KKDetail.FOvered
     *
     * @param fovered the value for dbo.XD_KKDetail.FOvered
     *
     * @mbggenerated
     */
    public void setFovered(Boolean fovered) {
        this.fovered = fovered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_KKDetail.FActDate
     *
     * @return the value of dbo.XD_KKDetail.FActDate
     *
     * @mbggenerated
     */
    public Date getFactdate() {
        return factdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_KKDetail.FActDate
     *
     * @param factdate the value for dbo.XD_KKDetail.FActDate
     *
     * @mbggenerated
     */
    public void setFactdate(Date factdate) {
        this.factdate = factdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_KKDetail.FPIndex
     *
     * @return the value of dbo.XD_KKDetail.FPIndex
     *
     * @mbggenerated
     */
    public BigDecimal getFpindex() {
        return fpindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_KKDetail.FPIndex
     *
     * @param fpindex the value for dbo.XD_KKDetail.FPIndex
     *
     * @mbggenerated
     */
    public void setFpindex(BigDecimal fpindex) {
        this.fpindex = fpindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_KKDetail.FBankRate
     *
     * @return the value of dbo.XD_KKDetail.FBankRate
     *
     * @mbggenerated
     */
    public BigDecimal getFbankrate() {
        return fbankrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_KKDetail.FBankRate
     *
     * @param fbankrate the value for dbo.XD_KKDetail.FBankRate
     *
     * @mbggenerated
     */
    public void setFbankrate(BigDecimal fbankrate) {
        this.fbankrate = fbankrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_KKDetail.FCust
     *
     * @return the value of dbo.XD_KKDetail.FCust
     *
     * @mbggenerated
     */
    public BigDecimal getFcust() {
        return fcust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_KKDetail.FCust
     *
     * @param fcust the value for dbo.XD_KKDetail.FCust
     *
     * @mbggenerated
     */
    public void setFcust(BigDecimal fcust) {
        this.fcust = fcust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_KKDetail.FCustID
     *
     * @return the value of dbo.XD_KKDetail.FCustID
     *
     * @mbggenerated
     */
    public Integer getFcustid() {
        return fcustid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_KKDetail.FCustID
     *
     * @param fcustid the value for dbo.XD_KKDetail.FCustID
     *
     * @mbggenerated
     */
    public void setFcustid(Integer fcustid) {
        this.fcustid = fcustid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.XD_KKDetail.FECustName
     *
     * @return the value of dbo.XD_KKDetail.FECustName
     *
     * @mbggenerated
     */
    public String getFecustname() {
        return fecustname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.XD_KKDetail.FECustName
     *
     * @param fecustname the value for dbo.XD_KKDetail.FECustName
     *
     * @mbggenerated
     */
    public void setFecustname(String fecustname) {
        this.fecustname = fecustname == null ? null : fecustname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_KKDetail
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        XdKkdetail other = (XdKkdetail) that;
        return (this.getFid() == null ? other.getFid() == null : this.getFid().equals(other.getFid()))
            && (this.getFentryid() == null ? other.getFentryid() == null : this.getFentryid().equals(other.getFentryid()))
            && (this.getFperiod() == null ? other.getFperiod() == null : this.getFperiod().equals(other.getFperiod()))
            && (this.getFdate() == null ? other.getFdate() == null : this.getFdate().equals(other.getFdate()))
            && (this.getFperrev() == null ? other.getFperrev() == null : this.getFperrev().equals(other.getFperrev()))
            && (this.getFperrevnote() == null ? other.getFperrevnote() == null : this.getFperrevnote().equals(other.getFperrevnote()))
            && (this.getFbenjin() == null ? other.getFbenjin() == null : this.getFbenjin().equals(other.getFbenjin()))
            && (this.getFlixi() == null ? other.getFlixi() == null : this.getFlixi().equals(other.getFlixi()))
            && (this.getFactrev() == null ? other.getFactrev() == null : this.getFactrev().equals(other.getFactrev()))
            && (this.getFamtall() == null ? other.getFamtall() == null : this.getFamtall().equals(other.getFamtall()))
            && (this.getFover() == null ? other.getFover() == null : this.getFover().equals(other.getFover()))
            && (this.getFovered() == null ? other.getFovered() == null : this.getFovered().equals(other.getFovered()))
            && (this.getFactdate() == null ? other.getFactdate() == null : this.getFactdate().equals(other.getFactdate()))
            && (this.getFpindex() == null ? other.getFpindex() == null : this.getFpindex().equals(other.getFpindex()))
            && (this.getFbankrate() == null ? other.getFbankrate() == null : this.getFbankrate().equals(other.getFbankrate()))
            && (this.getFcust() == null ? other.getFcust() == null : this.getFcust().equals(other.getFcust()))
            && (this.getFcustid() == null ? other.getFcustid() == null : this.getFcustid().equals(other.getFcustid()))
            && (this.getFecustname() == null ? other.getFecustname() == null : this.getFecustname().equals(other.getFecustname()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.XD_KKDetail
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFid() == null) ? 0 : getFid().hashCode());
        result = prime * result + ((getFentryid() == null) ? 0 : getFentryid().hashCode());
        result = prime * result + ((getFperiod() == null) ? 0 : getFperiod().hashCode());
        result = prime * result + ((getFdate() == null) ? 0 : getFdate().hashCode());
        result = prime * result + ((getFperrev() == null) ? 0 : getFperrev().hashCode());
        result = prime * result + ((getFperrevnote() == null) ? 0 : getFperrevnote().hashCode());
        result = prime * result + ((getFbenjin() == null) ? 0 : getFbenjin().hashCode());
        result = prime * result + ((getFlixi() == null) ? 0 : getFlixi().hashCode());
        result = prime * result + ((getFactrev() == null) ? 0 : getFactrev().hashCode());
        result = prime * result + ((getFamtall() == null) ? 0 : getFamtall().hashCode());
        result = prime * result + ((getFover() == null) ? 0 : getFover().hashCode());
        result = prime * result + ((getFovered() == null) ? 0 : getFovered().hashCode());
        result = prime * result + ((getFactdate() == null) ? 0 : getFactdate().hashCode());
        result = prime * result + ((getFpindex() == null) ? 0 : getFpindex().hashCode());
        result = prime * result + ((getFbankrate() == null) ? 0 : getFbankrate().hashCode());
        result = prime * result + ((getFcust() == null) ? 0 : getFcust().hashCode());
        result = prime * result + ((getFcustid() == null) ? 0 : getFcustid().hashCode());
        result = prime * result + ((getFecustname() == null) ? 0 : getFecustname().hashCode());
        return result;
    }
}